### PR TITLE
Test smooth scrolling

### PR DESCRIPTION
**Pull request by steverydz**
This branch contains work from https://github.com/canonical-web-and-design/ubuntu.com/pull/9055 and adds [CSS smooth scroll behaviour](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior).

### CODE REVIEW

**Comment by steverydz** [comment]
https://github.com/canonical-web-and-design/ubuntu.com/pull/9055#issuecomment-766714123

@elioqoshi I've made this as a separate branch as it's a global behaviour change. Would you be able to do a QA? Aside from the advantage pages, other places using in-page scroll include /tutorials, /desktop/statistics, tabs on /appliance/hardware#intel-nuc. You'll probably find more if you click around a bit.

**Comment by elioqoshi** [comment]
@steverydz Sure, happy to do a thorough QA review. 

> Demo starting at https://ubuntu-com-9080.demos.haus

I am however unable to see the smooth scroll effect on the demo link. Am I doing something wrong?

**Comment by steverydz** [comment]
@elioqoshi sorry, the scroll should be working now

**Comment by elioqoshi** [comment]
@steverydz Sorry just got around with a bit of space to test this properly. Here is already one small thing which might be improved, not critical though so let me know your thoughts:

- On layouts like on Tutorials, clicking on an an anchor link on the sidebar, makes the page view scroll to the very top of the page. It should scroll to the top of the content (right below the navigation bar of the site instead ideally. I assume this was the former behaviour and was not affected by smooth scrolling and we can eventually track this in a separate issue.

**Comment by elioqoshi** [comment]
@steverydz I don't think there are any other cases where smooth scrolling would be present on Ubuntu.com The only thing applicable would be on docs platforms of other products like MAAS, but that's not within this scope.

**Comment by elioqoshi** [comment]
@steverydz were you able to have a look at this yet? It might be worth to go ahead with this PR and do another PR to address the improvements I mentioned.

**Comment by steverydz** [comment]
> @steverydz were you able to have a look at this yet? It might be worth to go ahead with this PR and do another PR to address the improvements I mentioned.

@elioqoshi no, I haven't had time - perhaps someone on the web squad could take a look?

**Comment by elioqoshi** [comment]
@steverydz Sure, will check!

**Comment by elioqoshi** [comment]
@SirSamTumless Can we check who can take this on?

**Comment by elioqoshi** [comment]
@anthonydillon if you could have a look at this and merge it, we can do the improvements I mentioned in a separate PR at a later point.

**Comment by anthonydillon** [comment]
@elioqoshi should this smooth scroll when you select a platform to the quantity input? If so, I don't think it's doing it for me on Firefox.

**Comment by elioqoshi** [comment]
@anthonydillon you mean on the Advantage buy subscription page, right?

It doesn't work for me neither right now. Not sure what changed, I am pretty sure this worked fine when I first reviewed it. Any clue @steverydz ?

**Comment by steverydz** [comment]
@elioqoshi @anthonydillon It will only smooth scroll if the field isn't already in the viewport, so if you can already see the field the page won't scroll, it will just focus.

**Comment by elioqoshi** [comment]
@steverydz Yeah I am aware. It's not smooth scrolling if the field is outside the viewport though. I just tested it in responsive design mode on Firefox desktop

**Comment by steverydz** [comment]
@elioqoshi it's working in Chrome but not Firefox for me. I don't remember if I tested Firefox or not now, so not sure if it was working before?

**Comment by elioqoshi** [comment]
@steverydz interesting, I am pretty sure it was working before...

In that case we would still have to do these changes before merging.

**Comment by anthonydillon** [comment]
@elioqoshi Hey I checked again and this is working as expected. Is the main purpose of this to make the scroll to the cart nicer in advantage?

**Comment by elioqoshi** [comment]
@anthonydillon This should make all automatic scrolling in all places on Ubuntu.com smooth. That includes advantage, but also /tutorials, /desktop/statistics, tabs on /appliance/hardware#intel-nuc.

**Comment by elioqoshi** [comment]
@anthonydillon not sure but there is no smooth scrolling for me on Firefox. It only works on Chrome right now.

**Comment by anthonydillon** [comment]
@elioqoshi This is what it looks like for me on Firefox. Do you not get this?
Peek 2021-03-01 09-33

**Comment by elioqoshi** [comment]
@anthonydillon I am getting that. However smooth scrolling within the subscription steps is not working on Firefox, but it works on Chrome (you can try it on a smaller mobile view in Responsive Design mode)

**Comment by anthonydillon** [comment]
This only change in focus is on the quantity input which is likely within view?

**Comment by elioqoshi** [comment]
> This only change in focus is on the quantity input which is likely within view?

I tried it when it's not in view, especially on mobile. The scrolling is not smooth, which is okay (but not consistent on most Desktops) but mostly noticeable on mobile.

Here is a preview of Firefox Desktop where you can see that happening on 0:04. Putting the subscription on the basket though (0:11) activates a smooth scrolling animation though.


https://user-images.githubusercontent.com/5436686/109631130-f3500680-7b45-11eb-8625-20827e699318.mov

This works fine on Chrome Desktop though. You can see smooth scrolling is activated consistently:
https://user-images.githubusercontent.com/5436686/109631534-52158000-7b46-11eb-9470-2b7fdaddf42b.mov

Funnily, Chrome and Firefox for Android both display issues with smooth scrolling here, similar to Firefox Desktop. In summary only Chrome Desktop works as intended.

**Comment by anthonydillon** [comment]
Seems like this browser feature is not reliable enough at the moment.

**Comment by elioqoshi** [comment]
This would be an improvement in its current state anyway so we should go ahead and merge it and eventually improve it later on once possible.

**Review by anthonydillon — APPROVED** [review]
LGTM :+1:

**Pull request merged**
