### PR TITLE
Telco bubble

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

- Updates /telco pages

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/telco
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Compare against found in the [brief](https://docs.google.com/document/d/1oZV1VdLUPl8zt3fTgX-B3j9ksY8Esq4PWnEAI_cwOmg/edit#)
- Make sure navigation and contact form works

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/4185

### CODE REVIEW

**Comment by carkod** [comment]
Some issues:
- CNF, OpenRan, Magma, VNF forms is not working https://ubuntu-com-10012.demos.haus/telco/cnf#get-in-touch
- Can you remove (rebase) the duplicated commits? E.g. `Updates contact-us button` seems to be duplicated 4 times.

**Comment by carkod** [comment]
@SirSamTumless who is the Pdm? Maciej?

**Comment by SirSamTumless** [comment]
@marowid is the PdM

**Comment by marowid** [comment]
Can we have the top navigation menu for telco in this order ?
Overview
VNF
CNF
OpenRAN
Magma
Onboarding Network Functions

**Comment by marowid** [comment]
Issue: Contact form works only on main /telco page, others are not

**Review by carkod — APPROVED** [review]

**Comment by SirSamTumless** [comment]
@marowid Please can you give this a +1 if you're happy changes

**Comment by marowid** [comment]
+1 from me

**Pull request merged**
