### PR TITLE
Update banner illustration on /embedded page

### LINKED ISSUE #6513: [ILLUSTRATIONS UPDATE] /embedded
Please update Embedded - "Ubuntu is the new standard for embedded Linux" from the [copy doc](https://docs.google.com/document/d/15Tz87YRg4SnX4DWGOSl2TDTHLSStJoma879xHnF0nuo/edit?usp=drivesdk)

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

- Update banner illustration on /embedded page

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/embedded
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- See that the illustrations has been updated per the [copy doc](https://docs.google.com/document/d/15Tz87YRg4SnX4DWGOSl2TDTHLSStJoma879xHnF0nuo/edit#) and accept them please

## Issue / Card

Fixes #6513

### CODE REVIEW

**Comment by barrymcgee** [comment]
# [Codecov](https://codecov.io/gh/canonical-web-and-design/ubuntu.com/pull/6518?src=pr&el=h1) Report
> Merging [#6518](https://codecov.io/gh/canonical-web-and-design/ubuntu.com/pull/6518?src=pr&el=desc) into [master](https://codecov.io/gh/canonical-web-and-design/ubuntu.com/commit/897c4d2b2123206b11cce18d09be41b6479d71e0&el=desc) will **not change** coverage by `%`.
> The diff coverage is `n/a`.

**Comment by anasereijo** [comment]
don't merge: I have more illustrations for this page now - updating the copydoc

**Comment by anasereijo** [comment]
@pmahnke all illustrations are now updated in the copydoc. I also added the size as a comment

**Comment by pmahnke** [comment]
@anasereijo ready for re-review

**Comment by anasereijo** [comment]
@pmahnke looking good

**Pull request merged**
