### PR TITLE
CVE search and pagination

### LINKED ISSUE #7056: Build CVE search form and search results page including pagination

### PR DESCRIPTION
**Pull request by steverydz**
## Done

- Add basic search to /security/cve
- Add pagination to /security/cve

## QA

- Check out this feature branch
- Run the following commands
- `docker-compose up -d`
- `dotrun --env DATABASE_URL=postgres://postgres:pw@localhost:5432/postgres` (exit command once site is ready)
- `dotrun exec python3 webapp/security/fixtures/load_sample_cve.py`
- `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/security/cve
- Add the query string `?limit=1` to the URL and check that there is working pagination
- Enter `cve` in the search box and submit the form and check that there is a result
- Enter `gitlab` in the package field and submit the form and check that there is a result
- Change the priority in the dropdown and submit the form and check that there is a result
- Enter the same values in all three form fields (set priority to `medium`) and submit the form and check that there is a result

## Issue / Card

Fixes #7056

### CODE REVIEW

**Comment by steverydz** [comment]
@anthonydillon would you be able to review this please as you've already had the test data setup?

**Comment by anthonydillon** [comment]
@steverydz Sure, I had to remove the db as it causes master to fail but will recall the commands and if not ask you.

**Comment by steverydz** [comment]
> Code looks ok but getting `FAILED: Can't locate revision identified by '959f2c1919bf'` when trying to run it.

@carkod have you got any ideas why Ant is getting this error when trying to run the site?

**Comment by carkod** [comment]
@steverydz yeah I always get that when we change the schema. @anthonydillon you have to drop the db schema and create it again and then `dotrun`

**Comment by steverydz** [comment]
@carkod in what context do you run that? `dotrun exec`?

**Comment by anthonydillon** [comment]
@carkod A full set of commands would be appreciated.

**Comment by carkod** [comment]
Here are some instructions until we can deal with this with `dotrun`

1. Initiate the dev database `docker-compose up -d`
2. `docker ps` and check that a container called `db` has been created. 
3. Exec into the container `docker exec -ti db bash`
4. Login to the db `psql -U postgres`
5. Execute queries to clean the database. `DROP SCHEMA public CASCADE;` and after `CREATE SCHEMA public;`
6. Exit the db and the container (Ctrl + D) and `dotrun`

**Comment by steverydz** [comment]
@anthonydillon would you be able to do a QA review. The instructions that Carlos left [here](https://github.com/canonical-web-and-design/ubuntu.com/pull/7242#issuecomment-616435249) seem to do the trick.

**Comment by anthonydillon** [comment]
## QA
- The entered search term or package should persist in the fields when submitted.
- When I go to http://0.0.0.0:8001/security/cve?limit=1 I get no records, is this right?
- There is no clear explanation of what is being filtered and how to clear them

Let me know if these are out od scope for this branch?

**Pull request merged**
