### PR TITLE
updated to the latest security datasheet

### PR DESCRIPTION
**Pull request by nmav**
## Done

- [Updated the datasheet to the latest on cybersecurity]

### CODE REVIEW

**Review by carkod — APPROVED** [review]
LGTM

**Comment by nmav** [comment]
Thank you @carkod ! Does it need something more for the page to be updated?

**Comment by carkod** [comment]
> Thank you @carkod ! Does it need something more for the page to be updated?

Yes, we are deploying now to production, it should be there in a few minutes

**Comment by nmav** [comment]
Thank you a lot!

**Pull request merged**
