### PR TITLE
7139 ceph copy

### LINKED ISSUE #7139: [COPY UPDATE] index.html - Ceph
Please update index.html - Ceph from the [copy doc](https://docs.google.com/document/d/17VnBygL00hXjLSECXMo3bF7KOCT5oZGFBLo6Qd6rF3A/edit?usp=drivesdk)

- [x] Update ctas
- [x] Update diagram
- [x] Add video

### PR DESCRIPTION
**Pull request by deadlight**
## Done

Updated ceph page

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/ceph
- Compare to [copydoc](https://docs.google.com/document/d/17VnBygL00hXjLSECXMo3bF7KOCT5oZGFBLo6Qd6rF3A/edit)
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)

## Issue / Card

Fixes #7139

### CODE REVIEW

**Comment by pmahnke** [comment]
@deadlight is the video meant to be part of the strip below? The copy doc looks like it might be.  Also the diagram suggests a caption, can/do we do that?

**Comment by deadlight** [comment]
@pmahnke sure, I can try putting the video in the strip below.

I didn't see the caption (it's not a new change to the doc, it was previously not built) but I'm happy to put it in.

**Comment by deadlight** [comment]
@pmahnke I've moved the video and have added a caption to the diagram. Ready for re-review

**Comment by pmahnke** [comment]
@deadlight thanks, it now fits the layout of the copydoc... but I agree, the video looks lost here, perhaps a designer can help us out?  But I think this could go live and we fix later if needs be.

**Comment by spencerbygraves** [comment]
@deadlight @pmahnke if we're just talking about the strip with the video, I think it will look fine with `is-bordered` added to the strip above:

image

**Pull request merged**
