### PR TITLE
Build: Overview Default suru strip - /iot

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Added a new suru strip pattern to the code base and used it in the header of the internet-of-things page.

## QA
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Go to /internet-of-things
- Check it matches [the design](https://github.com/canonical-web-and-design/web-squad/issues/1459)

## Issue / Card
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1311
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1459

## Screenshots
Screenshot_2019-07-23 Ubuntu for the Internet of Things Ubuntu

### CODE REVIEW

**Comment by anasereijo** [comment]
@anthonydillon can you add `.u-vertically-center` to the text?

**Comment by anasereijo** [comment]
Please don't close this as this demo is being used as testing

**Comment by anthonydillon** [comment]
@anasereijo you got it

**Comment by anasereijo** [comment]
looks good, please just fix mobile as per our conversation. thanks

**Comment by anthonydillon** [comment]
@anasereijo done, ready for review.

**Comment by anasereijo** [comment]
nice

**Pull request merged**
