### PR TITLE
Reinstate all search except server docs search

### PR DESCRIPTION
**Pull request by carkod**
## Done

Reinstate all search except server docs search.
According to [google bot crawl history]( https://ubuntu.com/server/docs/search?q=%E6%B7%B1%E5%9C%B3%E5%A4%96%E5%9B%B4%E8%81%94%E7%B3%BB%E3%80%90) most of the spamming comes from google bot spamming specifically `/server/docs/search`, so there is a very high chance that only /server/docs is being spammed, all other searches should be safe to be put back.

## QA

Go to the following pages and use the search box:

- https://ubuntu-com-11759.demos.haus/
- https://ubuntu-com-11759.demos.haus/core/services/guide
- https://ubuntu-com-11759.demos.haus/kubernetes/docs
- https://ubuntu-com-11759.demos.haus/core/docs
- https://ubuntu-com-11759.demos.haus/tutorials
- https://ubuntu-com-11759.demos.haus/ceph/docs
- https://ubuntu-com-11759.demos.haus/openstack/docs
- https://ubuntu-com-11759.demos.haus/security/livepatch/docs
- https://ubuntu-com-11759.demos.haus/security/certifications/docs

Fixes #5577

### CODE REVIEW

**Comment by nottrobin** [comment]
Question:

- K8s docs doesn't have search - should it?
- None of these pages have `noindex` apart from the main site search - how certain are we that *only* server docs has been indexed?

Assuming this doesn't worry you, :+1: merge away.

**Comment by carkod** [comment]
> ## Done
> Reinstate all search except server docs search. According to [google bot crawl history](https://ubuntu.com/server/docs/search?q=%E6%B7%B1%E5%9C%B3%E5%A4%96%E5%9B%B4%E8%81%94%E7%B3%BB%E3%80%90) most of the spamming comes from google bot spamming specifically `/server/docs/search`, so there is a very high chance that only /server/docs is being spammed, all other searches should be safe to be put back.
> 
> ## QA
> Go to the following pages and use the search box:
> 
> * https://ubuntu-com-11759.demos.haus/
> * https://ubuntu-com-11759.demos.haus/core/services/guide
> * https://ubuntu-com-11759.demos.haus/kubernetes/docs
> * https://ubuntu-com-11759.demos.haus/core/docs
> * https://ubuntu-com-11759.demos.haus/tutorials
> * https://ubuntu-com-11759.demos.haus/ceph/docs
> * https://ubuntu-com-11759.demos.haus/openstack/docs
> * https://ubuntu-com-11759.demos.haus/security/livepatch/docs
> * https://ubuntu-com-11759.demos.haus/security/certifications/docs

Point 1: I don't know, I didn't do that one. Most of our searches were kind of requested by the respective teams I guess I can add it maybe in a different PR?
Point 2: right, It does worry me, I think now updating to the new search version will suffice?

**Comment by nottrobin** [comment]
> Point 1: I don't know, I didn't do those docs. I guess I can add it maybe in a different PR?

No let's definitely not include it in this PR. It's just 'cos you mentioned it - I wasn't sure if you expected it to have search.

> Point 2: right, It does worry me, I think now updating to the new search version will suffice?

I'll check.

**Comment by nottrobin** [comment]
> > Point 2: right, It does worry me, I think now updating to the new search version will suffice?
> 
> I'll check.

OK I searched Google for all these URLs. Nothing. I'll merge and release this now.

**Review by nottrobin — APPROVED** [review]

**Pull request merged**
