### PR TITLE
Move openstack diagram to own section

### LINKED ISSUE #6463: [COPY UPDATE] what-is-openstack - "What is OpenStack"
Move the diagram from the hero section to its own section

[copy doc](https://docs.google.com/document/d/15xrgIq_KUwHaCyFoI7-yS_JmBbsoyXJ4GpRMFAa7_is/edit?usp=drivesdk)

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Move the openstack diagram at the top of the page to it's own section and made it full width.

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/openstack/what-is-openstack
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- See that the diagram at the top of the page has it's own section and is full width

## Issue / Card

Fixes #6463

### CODE REVIEW

**Comment by anasereijo** [comment]
- [ ]  add `is-bordered` to the hero section to make it look separate from the diagram. This will look even better when we apply suru here.

Screenshot 2020-01-28 at 11 46 48

**Comment by steverydz** [comment]
@anasereijo Border added to hero

**Comment by anasereijo** [comment]
@steverydz I'm really sorry but I forgot to ask you to make the diagram 850px wide and left aligned. soz!!!

**Comment by steverydz** [comment]
@anasereijo done

**Comment by anasereijo** [comment]
@steverydz Looks good! Thanks

**Pull request merged**
