### PR TITLE
ES & DE VMware to OpenStack takeover & engage pages

### LINKED ISSUE #6543: [Whitepaper] VMWare to Openstack (Spanish)] - Build takeover and engage page
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/1KzOTpN3grKr86V6CLjMYxlkqYjIscjvUKzAAuZKQVgk/edit#gid=0) and [the past takeover](https://ubuntu.com/engage/vmware-to-charmed-openstack?utm_source=Takeover&utm_medium=Takeover&utm_campaign=CY19_DC_Openstack_WBN_VMwaretoOpenstack).
 
- [x] build takeover
- [x] build engage page
- [x] add takeover to `/takeovers/index.html`
- [x] add takeover to `/index.html`
- [x] add engage page to `/engage/index.html`
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

- Added German and Spanish versions of the VMWare To Charmed OpenStack takeover and engage pages.
  - Also added a Spanish version of the engage form

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Set your browser language to German and refresh the page until you see a takeover with the title "Migration von VMware zu OpenStack". See that it matches the [brief](https://docs.google.com/spreadsheets/d/17rhx6XrSyrr3lUA0HUwIww3xz0cgrdKry1VoCVJchjg/edit#gid=2113339190)
- Follow the CTA on the takeover to the engage page. See that it matches the [copy doc](https://docs.google.com/document/d/15ipwZJaEZhW9tMe6ISsRfEebrjaw1U5Pznfm5SQqY5k/edit).
- Test the page on https://cards-dev.twitter.com/validator, see that the card displays the correct title, description and image.
- Complete and submit the form, see that you are returned to https://pages.ubuntu.com/VMwaretoOpenStack_DE.html
- Visit the homepage again, set your browser's language to Spanish and repeat the process.
  - The takeover should have the title "De VMware a Charmed OpenStack", and match [this brief](https://docs.google.com/spreadsheets/d/1KzOTpN3grKr86V6CLjMYxlkqYjIscjvUKzAAuZKQVgk/edit#gid=877682240)
  - The engage page should match [this copy doc](https://docs.google.com/document/d/1_8SmEU9ESXbl1kGSTvivr1mj0JzV8rSSZe_jPSgLNLk/edit), and the form should return you to https://pages.ubuntu.com/VMwaretoOpenStack_ES.html
- Visit /engage and see that both engage pages are listed.
- Visit /takeovers and see that both takeovers are listed.

## Issue / Card

Fixes #6543 & #6544

### CODE REVIEW

**Comment by nottrobin** [comment]
When I submitted the form, I wasn't taken to https://pages.ubuntu.com/VMwaretoOpenStack_DE.html. Instead, I stayed on the same page, and the form seemed to have cleared with nothing happening. But when I scrolled up I saw this:

image

**Comment by SirSamTumless** [comment]
When I filled the form it displays a text box at the top of the page' "Thank you, someone, from our team, will be in touch within one working day" rather than taking you to the thank you page.

It needs the URL; https://pages.ubuntu.com/VMwaretoOpenStack_DE.html

**Comment by sowasred2012** [comment]
@nottrobin @SirSamTumless - that issue is fixed, but I see now that https://pages.ubuntu.com/VMwaretoOpenStack_DE.html is in English, @Khutch25 should that be the case?

**Comment by SirSamTumless** [comment]
@sowasred2012 Yep, we don't have translated thank-you pages.

**Comment by sowasred2012** [comment]
@SirSamTumless but https://pages.ubuntu.com/VMwaretoOpenStack_ES.html is in Spanish?

**Comment by SirSamTumless** [comment]
That's new! I will let @Khutch25 confirm...

**Comment by Khutch25** [comment]
@sowasred2012 Sorry for the confusion! We technically don't need the thank you pages for any form fill, so we're going to forgo the TY page for both the German and Spanish VMware to OpenStack pages.

**Comment by SirSamTumless** [comment]
> @sowasred2012 Sorry for the confusion! We technically don't need the thank you pages for any form fill, so we're going to forgo the TY page for both the German and Spanish VMware to OpenStack pages.

Ignore this - I have chatted to Kelly and we're fine to leave the thank-you pages as they are.

**Comment by Khutch25** [comment]
I have two changes if possible:

1) The 'Webinar ansehen' and 'Vea el webinar' buttons do not take you to #webinar on the page - can that be updated?

2) Just got confirmation that a partner will be joining the webinar, can you add this sentence to the bottom of the body copy section (below the checklist):

(on German page)
Zudem sollten Sie das Webinar "Von VMware zu Charmed OpenStack" ansehen, um in einer Demonstration zu erfahren, wie eine IT Workload mit Hilfe von Hystax von VMware zu Charmed OpenStack migriert wird.

(on Spanish page)
Este webinar también proporciona una demostración que muestra cómo migrar una carga de trabajo de TI de VMware a Charmed OpenStack utilizando la herramienta de migración de la nube como servicio de Hystax.

Thank you :)

**Comment by sowasred2012** [comment]
@SirSamTumless @Khutch25 just updated with your feedback 👍

**Comment by SirSamTumless** [comment]
@Khutch25 https://pages.ubuntu.com/VMwaretoOpenStack_DE.html links to the wrong whitepaper.

**Comment by steverydz** [comment]
@sowasred2012 
- [ ] The German takeover CTA has different text from the copy doc
- [ ] The German engage page doesn't match the copy doc
- [ ] The Spanish engage page has a paragraph at the end which isn't in the copy doc

**Comment by sowasred2012** [comment]
>     * [ ]  The German takeover CTA has different text from the copy doc
- There's four options in the brief, I've used Option 3 "Webinar ansehen"

>     * [ ]  The Spanish engage page has a paragraph at the end which isn't in the copy doc
- That was added via [feedback](https://github.com/canonical-web-and-design/ubuntu.com/pull/6565#issuecomment-582385227) from @Khutch25

**Pull request merged**
