### PR TITLE
Update /download/flavours

### LINKED ISSUE #6637: [ILLUSTRATIONS UPDATE] /download/flavours
Ubuntu flavours   Ubuntu (1)

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Update /download/flavours

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/download/flavours
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Check that the page matches [the design](https://user-images.githubusercontent.com/36884067/74353931-82ab4000-4db2-11ea-8c11-83e2ca3df8c3.png)

## Issue / Card

Fixes #6637

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- Can you add no border-top to the first item so on small screens is doesn't add the top line:
image

**Comment by steverydz** [comment]
@anthonydillon done

**Comment by anasereijo** [comment]
@steverydz 👍

**Comment by steverydz** [comment]
@anthonydillon could you approve this if you're happy with it?

**Pull request merged**
