### PR TITLE
Swap webpack with esbuild

### PR DESCRIPTION
**Pull request by jpmartinspt**
## Done

- Build JS with esbuild instead of webpack.

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Check JS across the site works well.

### CODE REVIEW

**Comment by anthonydillon** [comment]
Wow, this is very impressive. After a short click around all the areas on the site, I found no errors in the JS.

Before:
```
time ./run exec yarn run build-js
 
Yarn dependencies haven't changed. To force an update, delete .yarn.canonical-webteam-www.ubuntu.com-cdbd18cb.hash.
Pip dependencies haven't changed. To force an update, delete .pip.canonical-webteam-www.ubuntu.com-cdbd18cb.hash.
 
yarn run v1.22.5
warning package.json: License should be a valid SPDX license expression
$ webpack && yarn run build-global-nav && yarn run build-cookie-policy && yarn run build-latest-news
17 assets
orphan modules 706 KiB [orphan] 250 modules
runtime modules 3.58 KiB 17 modules
cacheable modules 502 KiB
  modules by path ./static/js/src/ 443 KiB
    modules by path ./static/js/src/*.js 48.8 KiB 15 modules
    modules by path ./static/js/src/*.js + 1 modules 30 KiB 4 modules
    modules by path ./static/js/src/*.js + 2 modules 125 KiB 3 modules
    modules by path ./static/js/src/*.js + 3 modules 72.3 KiB 2 modules
    3 modules
  modules by path ./node_modules/ 59.6 KiB
    modules by path ./node_modules/@babel/runtime/helpers/*.js 8.72 KiB 22 modules
    5 modules
webpack 5.21.2 compiled successfully in 12901 ms
warning package.json: License should be a valid SPDX license expression
$ cp node_modules/@canonical/global-nav/dist/global-nav.js static/js/dist/
warning package.json: License should be a valid SPDX license expression
$ cp node_modules/@canonical/cookie-policy/build/js/cookie-policy.js static/js/dist/
warning package.json: License should be a valid SPDX license expression
$ cp node_modules/@canonical/latest-news/dist/latest-news.js static/js/dist
Done in 14.92s.
./run exec yarn run build-js  1.69s user 0.72s system 11% cpu 20.442 total
```

After: 
```
time ./run exec yarn run build-js
 
Yarn dependencies haven't changed. To force an update, delete .yarn.canonical-webteam-www.ubuntu.com-cdbd18cb.hash.
Pip dependencies haven't changed. To force an update, delete .pip.canonical-webteam-www.ubuntu.com-cdbd18cb.hash.
 
yarn run v1.22.5
warning package.json: License should be a valid SPDX license expression
$ node build.js && yarn run build-global-nav && yarn run build-cookie-policy && yarn run build-latest-news
Built contributions.js
Built desktop-statistics.js
Built chassisAnimation.js
Built image-download.js
Built tutorials.js
Built forms.js
Built ua-entitlements-callout.js
Built release-chart.js
Built sticky-nav.js
Built cve.js
Built appliance.js
Built ua-product-selector.js
Built tco-calculator.js
Built tabotronic.js
Built imageBuilder.js
Built main.js
Built ua-payment-modal.js
warning package.json: License should be a valid SPDX license expression
$ cp node_modules/@canonical/global-nav/dist/global-nav.js static/js/dist/
warning package.json: License should be a valid SPDX license expression
$ cp node_modules/@canonical/cookie-policy/build/js/cookie-policy.js static/js/dist/
warning package.json: License should be a valid SPDX license expression
$ cp node_modules/@canonical/latest-news/dist/latest-news.js static/js/dist
Done in 1.12s.
./run exec yarn run build-js  1.39s user 0.52s system 34% cpu 5.563 total
```

**Comment by hatched** [comment]
Impressive 🤯 

Running just the js build I was getting ~14.7s for `yarn run webpack` and ~250ms for `node build.js`.

If that wasn't fast enough you could write a bash script an interface with the esbuild CLI directly.... maybe diminishing returns ;)

**Comment by carkod** [comment]
And you were also able to reduce the number of config files and dependencies... interesting, I wonder which are the drawbacks xD

**Comment by hatched** [comment]
@carkod it's (currently) considerably less configurable than the alternatives and still requires third party plugins for some of the more advanced functionality like sass and svg asset imports. But I expect that these issues will be smoothed over in time.

**Comment by anthonydillon** [comment]
@jpmartinspt @hatched can we merge this one then?

**Comment by hatched** [comment]
I'll let @jpmartinspt have the final say but it looks good from me (after CI passes 😉 )

**Comment by jpmartinspt** [comment]
@anthonydillon rebased and fixed CI. Happy to get it merged, might be worth asking in stand-up tomorrow for QA just for peace of mind.

**Comment by anthonydillon** [comment]
Thanks can you stick labels on to kick off a proper review.

**Review by hatched — APPROVED** [review]
\o/

**Comment by anthonydillon** [comment]
@ClementChaumel @pmahnke did you want to run through forms and advantage first?

**Comment by ClementChaumel** [comment]
LGTM on advantage. :+1: 
I'll need to update my code on the monthly branch once this is merged

**Comment by pmahnke** [comment]
I am seeing some JS errors on /blog 

image

The form seems to function fine, but I don't know what this is... but it isn't on live.

**Comment by anthonydillon** [comment]
I think that is the issue I resolved the other day. Could you rebase @jpmartinspt

**Comment by jpmartinspt** [comment]
@anthonydillon rebased.

**Comment by anthonydillon** [comment]
@pmahnke this should work now

**Review by pmahnke — APPROVED** [review]
+1 look good

**Comment by anthonydillon** [comment]
@jpmartinspt great work, prepping for release giving us time to monitor sentry and issues coming in.

**Pull request merged**
