### PR TITLE
Build AI edge webinar takeover and engage page

### LINKED ISSUE #6555: [Webinar] AI] - Build takeover and engage page
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/11RDq5vNUpgdy3UU_51d-QtGiptq5Fgz_tdOFbgx3zec/edit#gid=2113339190) and [design](https://github.com/canonical-web-and-design/web-squad/issues/2292):
 
- [x] build takeover
- [x] build engage page
- [x] add takeover to `/takeovers/index.html`
- [x] add takeover to `/index.html`
- [x] add engage page to `/engage/index.html`
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

### PR DESCRIPTION
**Pull request by steverydz**
## Done

- Build AI edge webinar engage page
- Add AI edge engage webinar page to /engage
- Build AI edge webinar takeover
- Add AI edge webinar takeover to /takeovers
- Add AI edge webinar takeover to homepage

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Refresh until you see the takeover titled "Artificial Intelligence at the edge in a 5G world"
- Check that the takeover matches the [brief](https://docs.google.com/spreadsheets/d/11RDq5vNUpgdy3UU_51d-QtGiptq5Fgz_tdOFbgx3zec/edit?ts=5e3d4646#gid=2113339190)
- Go to /takeovers
- Check that the "Artificial Intelligence at the edge in a 5G world" takeover is at the bottom of the page
- Click the CTA link in the takeover matches [the brief](https://docs.google.com/spreadsheets/d/11RDq5vNUpgdy3UU_51d-QtGiptq5Fgz_tdOFbgx3zec/edit?ts=5e3d4646#gid=1271849439) and [the copy doc](https://docs.google.com/document/d/1edSyC9pffQ6zF8GJrehQWtSGVTqkuLNjXhrqPhmdXbc/edit)
- Go to /engage
- Check that the AI edge webinar engage card is shown at the bottom of the page
- 

## Issue / Card

Fixes #6555

### CODE REVIEW

**Comment by pmahnke** [comment]
@SirSamTumless are we meant to remove any takeovers?

**Comment by anasereijo** [comment]
Looks good 👍 
@SirSamTumless can you double-check with Marketing if this ok to go?

**Comment by SirSamTumless** [comment]
@pmahnke This is supposed to replace the Ubuntu masters takeover

**Comment by steverydz** [comment]
@SirSamTumless @pmahnke done - replaced masters with ai edge

**Comment by SirSamTumless** [comment]
This good to go!

**Pull request merged**
