### PR TITLE
Dropdown visual improvements

### PR DESCRIPTION
**Pull request by ClementChaumel**
## Done

- Updated the table's dropdowns according to the [designs](https://app.zeplin.io/project/601d6513b99f24a8412ecfa5/screen/6036811573cb392a12077b84)

## QA

- go to https://ubuntu-com-9373.demos.haus/advantage?test_backend=true and check each tab on a subscription

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/3878
and https://app.zenhub.com/workspaces/web--ubuntu-clan-5931746dba512f05402b61f6/issues/canonical-web-and-design/web-squad/3903

## Screenshots

New:
image

machines
image

ESM
image

Livepatch
image

Certifications
image

### CODE REVIEW

**Comment by anasereijo** [comment]
@ClementChaumel THIS IS (almost) PIXEL PERFECT 🥇 thanks for your hard work!

I have 2 tiny things though... but it's just me being annoying :)

Screenshot 2021-03-12 at 14 40 23

Screenshot 2021-03-12 at 14 47 57

**Comment by anasereijo** [comment]
2 tiny things on mobile (hopefully!)

Screenshot 2021-03-12 at 15 05 36

**Comment by albertkol** [comment]
@ClementChaumel You have codecov checks complaining, I have no idea why.. try fetching remote and rebase, maybe that will get rid of it.

**Review by albertkol — APPROVED** [review]
:+1:

**Pull request merged**
