### PR TITLE
Update /openstack/install

### LINKED ISSUE #6592: [ILLUSTRATIONS UPDATE] /openstack/install
[copydoc](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc/edit)

**Hero**

- [x] suru `p-strip--suru-image`

- [x] illustration: https://assets.ubuntu.com/v1/2b03a6b4-Install+Openstack.svg

**Need more help?**

- [x] illustration: https://assets.ubuntu.com/v1/0e5f4269-questions.svg

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Update illustrations on /openstack/install

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/openstack/install
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Check that the illustrations have been updated as per [the issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/6592)

## Also check the following to make sure the hero's are legible on small screens:
- /ceph
- /desktop/statistics
- /internet-of-things/digital-signage
- /kubeflow
- /kubernetes/features
- /kubernetes/install

## Issue / Card

Fixes #6592

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- The hero image strip is on small screens shows the gradient. It's hard to read the links:
image

**Comment by anasereijo** [comment]
**Hero section**

- [ ] title should be part in the same `div` as the paragraph

- [ ] text to be `col-7` and illustration `col-5`

**Contact us section:**

- [ ] delete `is-deep`

- [ ] illustration width: 200px

**Comment by anasereijo** [comment]
> ## QA
> * The hero image strip is on small screens shows the gradient. It's hard to read the links:
>   image

@anthonydillon thanks for spotting that. I believe there is a discussion about this in Vanilla. Need to check if there is a decision or not regarding this issue.

**Comment by steverydz** [comment]
@anasereijo shall we change the type of suru in the hero for now?

**Comment by anasereijo** [comment]
is it possible to make these links neutral on small screens and apply the solution discussed [here](https://github.com/canonical-web-and-design/vanilla-framework/issues/2622)?

**Comment by steverydz** [comment]
@anasereijo 

> is it possible to make these links neutral on small screens and apply the solution discussed [here](https://github.com/canonical-web-and-design/vanilla-framework/issues/2622)?

The neutral links would apply globally - small and large screens

So the solution is to use bold and underline for the links?

**Comment by steverydz** [comment]
@anasereijo after talking with @anthonydillon I've removed the gradient for suru-image on small screens. What do you think about that?

**Comment by anasereijo** [comment]
> @anasereijo after talking with @anthonydillon I've removed the gradient for suru-image on small screens. What do you think about that?

I think by doing that it we are not fixing the issue... we shouldn't stop using suru on mobile just because of that. 

Can we make the links become white (`inverted`) and then doing what was proposed on [vanilla](https://github.com/canonical-web-and-design/vanilla-framework/issues/2622): `.p-link--inverted {color: inherit; font-weight: bold; text-decoration: underline;}`

**Comment by steverydz** [comment]
@anasereijo done

**Comment by anasereijo** [comment]
amazing @steverydz 🥇 any way to make sure that in situations like this one that will happen? should in https://ubuntu.com/_docs/strips ?

**Comment by steverydz** [comment]
> amazing @steverydz  any way to make sure that in situations like this one that will happen? should in https://ubuntu.com/_docs/strips ?

It'll happen for any `suru--image` with links in

**Comment by steverydz** [comment]
@anthonydillon are you good with this? If so can you approve?

**Comment by anthonydillon** [comment]
I really feel like this is a hack that is not good. We are not stopping to use suru on mobile but just removing the gradient. @anasereijo Why does this suru revert to a gradent when other suru's continue to be a suru on small screens?

**Comment by anasereijo** [comment]
> I really feel like this is a hack that is not good. We are not stopping to use suru on mobile but just removing the gradient. @anasereijo Why does this suru revert to a gradent when other suru's continue to be a suru on small screens?

@anthonydillon because we couldn't figure out how to make this suru shape work in small screens. The solution we found at the time was to make it a full width gradient

**Pull request merged**
