### PR TITLE
Add feedback link

### LINKED ISSUE #9827: /certified Model detail pages should include a feedback link
## Summary

The legacy certification.ubuntu.com site has a Feedback section on each model details page. For example, https://certification.ubuntu.com/hardware/201710-25838 has a section

_Feedback
If there is an issue with the information for this system, please let us know ._

That url goes to a launchpad answers form that includes the canonical id for the model. My team gets these emails, and we know that people request feedback.

## Process

If you visit any model details page you will see that there is no way to provide feedback, but there should be.

## Current and expected result

Now that we've transitioned to ubuntu.com/certified, I would like to see a way for the user to give feedback that notifies my team and also includes information about the page for which the user is providing feedback.

### PR DESCRIPTION
**Pull request by carkod**
## Done

Add feedback link

## QA

check https://ubuntu-com-9906.demos.haus/certified/201710-25838 has feedback link at the bottom of the page

## Issue / Card

Fixes #9827

### CODE REVIEW

**Comment by davegoddard42** [comment]
@carkod The 'l' in "let us know" should be a capital letter. Otherwise all good.

**Comment by anasereijo** [comment]
@carkod can you add the class `is-shallow` to that strip?

**Comment by carkod** [comment]
All done

**Review by codersquid — APPROVED** [review]
I've checked a demo page with and without components and things look fine.

The feedback link includes the expected strings.

looks good.

**Comment by anasereijo** [comment]
lgtm thanks @carkod

**Comment by davegoddard42** [comment]
@carkod - looks good. Nice work

**Pull request merged**
