### PR TITLE
/model-driven-operations: Add "Why use Juju" diagrams

### PR DESCRIPTION
**Pull request by mmanciop**
## Done

- Use the adjusted "Why use Juju" diagrams for Jaas.ai provided by @waynecrosby 

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- [List additional steps to QA the new features or prove the bug has been resolved]

## Screenshots
ubuntu com_model-driven-operations (1)

### CODE REVIEW

**Review by anthonydillon — COMMENTED** [review]
Code and QA looks good, just need a design +1

**Comment by waynecrosby** [comment]
@anthonydillon Looks like the edges of the SVGs are being clipped, I've updated them and attached new links below, can you update them please:
Left:
https://assets.ubuntu.com/v1/0d754471-why-use-juju-diagram-left-update.svg

Right:
https://assets.ubuntu.com/v1/ace14664-why-use-juju-diagram-right-update.svg

**Comment by mmanciop** [comment]
@anthonydillon tried in local, LGTM

**Review by anthonydillon — APPROVED** [review]
LGTM :+1:

**Pull request merged**
