### PR TITLE
Update /robotics/ros-esm page

### LINKED ISSUE #9673: [COPY DOC] /robotics/esm - "ROS Extended Security Maintenance"
Please update /robotics/esm - "ROS Extended Security Maintenance" based on the [copy doc](https://docs.google.com/document/d/1oiz_006n9U1Ya50wdSkKIyj_jsxSr92FdCpkDU4kpHs/edit?ts=60898010#heading=h.odnh1uuyfmr1).

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

- Update text on the ros esm page
- Redirect from /robotics/esm to /robotics/ros-esm

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/robotics/ros-esm
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Compare to the [copy doc](https://docs.google.com/document/d/1oiz_006n9U1Ya50wdSkKIyj_jsxSr92FdCpkDU4kpHs/edit?ts=60898010#) and test the redirect

## Issue / Card

Fixes #9673

### CODE REVIEW

**Comment by anasereijo** [comment]
@pmahnke is this ready to review?

**Comment by pmahnke** [comment]
@anasereijo sure, this was mostly text updates, but please give it look over, there was a new strip added.

**Comment by anasereijo** [comment]
LGTM 👍 
@bethcollins92 can you please review?

**Review by bethcollins92 — APPROVED** [review]
Tested redirect and copy - LGTM. I tested the newsletter and was redirected to correct thank-you page but I can't remember how to check if it was submitted to marketo correctly if this needs checking

**Comment by pmahnke** [comment]
@bethcollins92 fixed, it was entirely a backend problem with Marketo

**Comment by GAN-Canonical** [comment]
@pmahnke In the section "what is ROS ESM?" the first paragraph was copied twice.
Therefore the second paragraph of the section is missing.

**Comment by pmahnke** [comment]
@GAN-Canonical I have [put in a fix for this](https://github.com/canonical-web-and-design/ubuntu.com/pull/9745).  Next time, could you create a new issue? Then it will be linked up better for us.

**Pull request merged**
