### PR TITLE
Scroll to the subscription content if it is off the screen

### PR DESCRIPTION
**Pull request by huwshimi**
## Done

- Scroll to the subscription content if it is off the screen.

## QA

- Visit [/advantage?test_backend=true](https://ubuntu-com-10256.demos.haus/advantage?test_backend=true).
- Scroll down until all the subscription details is visible on the screen.
- Click on a subscription and the window shouldn't scroll.
- Click on the top subscription.
- Scroll down until just the free personal token card on the left is visible.
- Click on the free personal token card.
- You should get scrolled up until the top of the details is visible.

## Issue / Card

Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/93.

## Screenshots

scroll

### CODE REVIEW

**Comment by huwshimi** [comment]
@wgx what do you think? Is this somewhat how you imagined it?

**Review by ClementChaumel — APPROVED** [review]

**Comment by wgx** [comment]
@huwshimi Would it be possible to test this with a longer list of subscriptions. This behaviour is designed to fix an edge case where the user has 20 (or 100!) contract items in that list.

**Comment by huwshimi** [comment]
> @huwshimi Would it be possible to test this with a longer list of subscriptions. This behaviour is designed to fix an edge case where the user has 20 (or 100!) contract items in that list.

I've updated this to have 20 ua subs (+ the free sub). At the moment the list is set to the height of the content on the right, but do we need that to allow more to appear on the page before it starts scrolling?

**Comment by wgx** [comment]
@huwshimi thanks - I think this will work great, and is nice and usable. UX+1

**Pull request merged**
