### PR TITLE
add MWC banner to /telco

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

- added an MWC banner to /telco

## QA

- View the site in your web browser at: https://ubuntu-com-11282.demos.haus/telco
    - Be sure to test on mobile, tablet and desktop screen sizes
- See that the banner matches the [design](https://github.com/canonical-web-and-design/web-squad/issues/4832)

## Issue / Card

Fixes #https://github.com/canonical-web-and-design/web-squad/issues/4833

## Screenshots

Screenshot from 2022-02-24 15-20-55

### CODE REVIEW

**Review by mtruj013 — APPROVED** [review]
LGTM!

**Comment by pmahnke** [comment]
@spencerbygraves @sowasred2012 I think that suru looks really dark with the logo... do we have a grey strip? Also, it is very low on the page and likely not that useful... not sure what to do about that.

**Comment by spencerbygraves** [comment]
@pmahnke I'm not sure a light grey strip would be prominent enough on that long page. As for the position, my design wasn't supposed to be a suggestion, sorry. I'm not sure where Julie would want it.

**Comment by pmahnke** [comment]
@sowasred2012 I think after the logo cloud sounds good.

**Pull request merged**
