### PR TITLE
Add finance newsletter signup

### PR DESCRIPTION
**Pull request by carkod**
## Done
Add finance option to newsletter signup

## QA

- Go to https://ubuntu-com-11664.demos.haus/blog
- Sign up for newsletters with the finance option checked (make a note of the email you use)
- Check that your submission has appeared in Marketo (Scott can help you with this if you need)

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/5449#event-6707591309

## Help

[QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html) - [Commit guidelines](https://canonical-web-and-design.github.io/practices/workflow/commit-messages.html)

### CODE REVIEW

**Comment by carkod** [comment]
@caldav to update Perkuto templates

**Comment by sowasred2012** [comment]
@caldav do you have an update on this?

**Comment by sowasred2012** [comment]
We have a meeting on Thursday 23rd to go through adding this new option in Perkuto/Marketo etc

**Review by minkyngkm — APPROVED** [review]
QA done in marketo - LGTM 👍
image

**Pull request merged**
