### PR TITLE
Takeovers from Discourse

### LINKED ISSUE #8406: Takeovers from discourse module
## Summary

- Add new discourse module changes to ubuntu project
- Modify the templates to accommodate new layout

### PR DESCRIPTION
**Pull request by carkod**
## Done

- Takeovers to Discourse

## QA

- Go to the demo homepage and check that the takeover is appearing.
- Go to the demo `/takeovers` and check that the rest of the takeovers are appearing
- Go to the [index table on Discourse](https://discourse.ubuntu.com/t/about-the-engage-pages-category/17229/2) and check that the data is consistent with this content (only active=true takovers are showing)

### Additional checks
- Change the index topic (line 279) of `app.py` to 18033 to check that the Spanish takeover is showing (you'll have to change your browser language to Spanish to test this). This data comes from the test [takeover data](https://discourse.ubuntu.com/t/test-engage-pages/18033), and it has a parameter active = true. On production we don't show this takeover, this is merely for testing.
- You can also break the markdown and see what happens. The expected result is that a default takeover of Ubuntu 20.10 is displayed instead.
- You may also want to play around with the `lang-skip` column to make sure e.g. first takeover does not show for italian.

## Issue / Card

Fixes #8406

### CODE REVIEW

**Review by anthonydillon — APPROVED** [review]
LGTM thanks for the hard work on this one :+1:

**Review by caldav — APPROVED** [review]
This is awesome, thanks!

**Review by nottrobin — DISMISSED** [review]
Please just check sure we are absolutely sure this won't break the site if Discourse is unavailable. We need to be sure of that before merging.

**Comment by anthonydillon** [comment]
Checked and found that the homepage displays the static takeover, the engage page renders with an empty list and the engage pages themselves 404.

**Comment by carkod** [comment]
> Please just check sure we are absolutely sure this won't break the site if Discourse is unavailable. We need to be sure of that before merging.

So @anthonydillon checked, can you approve it?

**Pull request merged**
