### PR TITLE
Add tutorials to the nav + update urls

### LINKED ISSUE #6538: Add 'Tutorials' to the nav on mobile view
We should have Tutorials as a link in the nav as per the following example:

Screenshot_20200202-144832__01__01

This will help the user to go back to Tutorials landing page when in a tutorial

Screenshot_20200202-144842__01

---
*Reported from: https://ubuntu.com/tutorials?_ga=2.86754584.1263552606.1580654828-404771543.1545472351*

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

- Add tutorials to the footer
- Add tutorials secondary nav
- Update all old tutorials.u.c urls to /tutorials

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/tutorials
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- On small screens, see that tutorials is in the header
- See that all the references (e.g. Download mega menu) now points to the /tutorials urls

## Issue / Card

Fixes #6538

### CODE REVIEW

**Comment by anasereijo** [comment]
@pmahnke looks good 👍 can you also add it to the other tutorial pages?

Screenshot 2020-02-03 at 11 34 43

**Comment by pmahnke** [comment]
@steverydz two things

1. It might be better to look at this instead of your PR for redirects, I think I found a lot more?
2. I am not sure how you built the secondary nav in tutorials to add the existing title... so my fix doesn't cover this.

I am inclinded to get this approve and have another that fixes the mobile header when you are in a tutorial.  What do you think?

**Comment by steverydz** [comment]
@pmahnke makes sense.

The nav was hard coded using a variable for the title itself

**Comment by steverydz** [comment]
@pmahnke If you remove lines 273-275 from /static/sass/_pattern_navigation.scss that should fix the mobile nav

**Comment by pmahnke** [comment]
@steverydz commited, but I am not seeing it? could it be the logic in _navigation.html

```
        {% if breadcrumbs %}
        <h5 class="p-navigation--secondary__logo u-hide--nav-threshold-up">
          <a class="p-navigation--secondary__banner" href="{{ breadcrumbs.section.path }}">
            {{ breadcrumbs.section.title }}
          </a>
        </h5>
        {% endif %}
```

**Comment by steverydz** [comment]
@pmahnke I think I'm misunderstanding what you're trying to do. If you're trying to show the orange "Tutorials" heading then you would need to remove the `u-hide--nav-threshold-down` class from the `h5`, but we don't show this anywhere else that I can see.

**Comment by anasereijo** [comment]
Developer dropdown:

Screenshot 2020-02-03 at 15 34 55

**Comment by pmahnke** [comment]
@anasereijo I fixed the dev dropdown, anything else, we will have to put into a new issue (like tutorials mobile issue) do I can get this fix up.

**Pull request merged**
