### PR TITLE
Copy update on /gcp/pro

### PR DESCRIPTION
**Pull request by minkyngkm**
## Done

- [List of work items including drive-bys - remember to add the why and what of this work.]

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/gcp/pro
- Be sure to test on mobile, tablet and desktop screen sizes
- Please check page against [copy doc](https://docs.google.com/document/d/1zR1m6CH1POU5tnzNzgNYanG2_EGQtKVNR3_dPew1pf4/edit) and resolve comments

## Issue / Card

Fixes [#4667](https://github.com/canonical-web-and-design/web-squad/issues/4667)

## Help

[QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html) - [Commit guidelines](https://canonical-web-and-design.github.io/practices/workflow/commit-messages.html)

### CODE REVIEW

**Review by anthonydillon — APPROVED** [review]
LGTM :+1:

**Comment by anthonydillon** [comment]
To fast Min. @lechsandecki had some changes to add. Feel free to add here @lechsandecki

**Comment by lechsandecki** [comment]
apologies for the last-minute change. I just made a small update in the opening paragraph to align it with AWS and Azure. See the change in copy doc.

should be:
"offering pay-as-you-go billing on your existing GCP invoice."

**Comment by minkyngkm** [comment]
Sorry I've merged it too fast! I've updated those changes on this [PR](https://github.com/canonical-web-and-design/ubuntu.com/pull/11003) for the `/aws/pro` page together.

**Pull request merged**
