### PR TITLE
Update homepage illustrations

### LINKED ISSUE #6446: [ILLUSTRATIONS UPDATE] index u.com
Please update index - "The leading operating system for PCs, IoT devices, servers and the cloud" from the [copy doc](https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit?usp=drivesdk)

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Update the homepage with the new illustrations

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Check that the illustrations in the 'Ubuntu is an open source software operating system that runs from the desktop, to the cloud, to all your internet connected things' section are the same as [the copy doc](https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit)
- Check that the illustrations have a hover state

## Issue / Card

Fixes #6446

### CODE REVIEW

**Comment by anasereijo** [comment]
@steverydz the new illustration for "The number one platform for containers" section isn't updated as per copydoc

**Comment by steverydz** [comment]
> @steverydz the new illustration for "The number one platform for containers" section isn't updated as per copydoc

@anasereijo It's using https://assets.ubuntu.com/v1/8700ffb2-containers.svg which is the link from the copy doc.

**Comment by steverydz** [comment]
@anasereijo I've added a comment to the copy doc. Could give me an asset which is the five small dots and the large one altogether? It's quite fiddly adding each dot individually.

**Comment by anasereijo** [comment]
> @anasereijo I've added a comment to the copy doc. Could give me an asset which is the five small dots and the large one altogether? It's quite fiddly adding each dot individually.

Hi @steverydz, I left a comment in the copydoc with a link

**Comment by anasereijo** [comment]
looks good

**Pull request merged**
