### PR TITLE
5250 improve blog post template

### LINKED ISSUE #5250: Improve blog post template
## Summary

On upgrade-to-django2 branch, update the blog post template to match the look and feel of (for example): https://blog.ubuntu.com/2019/05/28/ubuntu-server-development-summary-28-may-2019

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

- updated blog post template to match current blog e.g. https://blog.ubuntu.com/2019/04/09/speed-up-your-ros-snap-builds
- added tag template to match current blog e.g https://blog.ubuntu.com/tag/robotics

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [/blog/speed-up-your-ros-snap-builds](http://0.0.0.0:8001/blog/speed-up-your-ros-snap-builds)
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Ensure that the page looks and behaves similarly to https://blog.ubuntu.com/2019/04/09/speed-up-your-ros-snap-builds
- Click any of the tag links in the top of the page, and see that the page you then see looks and behaves similarly to https://blog.ubuntu.com/tag/robotics

## Issue / Card

Fixes #5250 

## Notes
The related posts section at the bottom of the page currently shows posts from multiple languages, this issue is being addressed [here](https://github.com/canonical-web-and-design/canonicalwebteam.blog/issues/71).

### CODE REVIEW

**Comment by anasereijo** [comment]
- [ ] navigation is missing

- [ ] the author page (/author/kyrofa/) looks very different from what we currently have. is this something we need to add to the backlog?

- [ ] share on facebook doesn't show text or image from the article

_how it looks like_

Screenshot 2019-06-05 at 10 54 25

_how it should look like (from the current version)_

Screenshot 2019-06-05 at 10 54 31

- [ ] share on Twitter displays a different URL

_how the demo looks like_
Screenshot 2019-06-05 at 10 56 05

_how it looks like online_

Screenshot 2019-06-05 at 10 56 12

- [ ] LinkedIn - I get an error when trying to share

- [ ] when clicking on Tags it takes me to the homepage. It should take us to that tag landing page

- [ ] on the online version we should an Internet of Things card on the right side and on the demo we show a Contact us card. Please match with what we currently have online

- [ ] newsletter sign up: move the word interested to the 2nd line

- [ ] Robotics is missing from the newsletter sign up

- [ ] related posts aren't showing the ones we have online. one it's in Japanese?

**Comment by solazio** [comment]
@sowasred2012 a few comments... not sure if you can fix them here, if not open new issues

- [ ] when you click on the author link it takes you to https://admin.insights.ubuntu.com/author/kyrofa/?_ga=2.179429156.1273720660.1559637660-1385128011.1555488464 instead of https://blog.ubuntu.com/author/kyrofa
- [ ] when you want to share on social media the link created takes you to blog.ubuntu.com instead of u.c/blog
- [ ] when you click on a tag it takes you to u.c/blog instead of u.c/blog/tag/[tagname]
- [ ] the blog navigation is missing

**Comment by sowasred2012** [comment]
This is currently blocked by work being done on https://github.com/canonical-web-and-design/canonicalwebteam.blog:

1: we don't have a /blog/tag/<tag> endpoint yet, to be addressed by [this issue](https://github.com/canonical-web-and-design/canonicalwebteam.blog/issues/73).

2: the facebook sharing link doesn't yet include an image, but soon will as part of a refactor @tbille is working on now.

3: the Japanese posts issue, to be addressed by [this issue](https://github.com/canonical-web-and-design/canonicalwebteam.blog/issues/71).

**Comment by sowasred2012** [comment]
@anasereijo @solazio this is (_finally_) ready to be reviewed again!

**Pull request merged**
