### PR TITLE
UA shop: prevent decimal place being added to quantity input

### LINKED ISSUE #8397: Its possible to buy a subscription for half a machine
You can get a very cheap subscription for just half of one machine: 

image

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

- Made it impossible to add fractional quantities of a product

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/advantage/subscribe
- Log in with SSO
- Start the product selection, when you get to the quantity input, try to type a number with a decimal point i.e 0.2, 1.7 etc etc etc
- See that the decimal point is automatically removed

## Issue / Card

Fixes #8397

### CODE REVIEW

**Comment by wgx** [comment]
👍🏼

**Comment by anthonydillon** [comment]
When entering 2.5 its converted to 25 which is unexpected to the user. I also get an error in the console: 
```
Uncaught TypeError: products[lineItem.get(...)[0]] is undefined
    calculateSubtotal https://ubuntu-com-8412.demos.haus/static/js/src/ua-product-selector.js?v=49b432c:193
    calculateSubtotal https://ubuntu-com-8412.demos.haus/static/js/src/ua-product-selector.js?v=49b432c:192
    buildCartHTML https://ubuntu-com-8412.demos.haus/static/js/src/ua-product-selector.js?v=49b432c:60
    updateCart https://ubuntu-com-8412.demos.haus/static/js/src/ua-product-selector.js?v=49b432c:456
    render https://ubuntu-com-8412.demos.haus/static/js/src/ua-product-selector.js?v=49b432c:350
    push https://ubuntu-com-8412.demos.haus/static/js/src/utils/state.js:48
    updateCartState https://ubuntu-com-8412.demos.haus/static/js/src/ua-product-selector.js?v=49b432c:493
    handleCartAction https://ubuntu-com-8412.demos.haus/static/js/src/ua-product-selector.js?v=49b432c:245
    init https://ubuntu-com-8412.demos.haus/static/js/src/ua-product-selector.js?v=49b432c:54
    init https://ubuntu-com-8412.demos.haus/static/js/src/ua-product-selector.js?v=49b432c:51
    productSelector https://ubuntu-com-8412.demos.haus/static/js/src/ua-product-selector.js?v=49b432c:19
    <anonymous> https://ubuntu-com-8412.demos.haus/static/js/src/ua-product-selector.js?v=49b432c:542
ua-product-selector.js:193:45
```

**Comment by anthonydillon** [comment]
I would suggest using the browser validation for this:
```
<input autocomplete="off" class="js-product-input" type="number" name="quantity" placeholder="0" min="1" step="1" data-stage="form" onwheel="this.blur()" onblur="form.reportValidity()" pattern="\d+" />
```

**Review by anthonydillon — APPROVED** [review]
LGTM and I'll follow up with a fix for the console errors.

**Pull request merged**
