### PR TITLE
Extend the search when activated

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Extend the search input full width to match the [design](https://app.zeplin.io/project/5ffdb21a3714151de9cf750c/screen/5fff03c52885841ced879a74)

## QA
- Check out the demo
- Activate the search
- See that it extends across the entire navigation
- Click the X and see that closes
- Check small screens work as before

## Issue / Card
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9291

## Screenshots
image

### CODE REVIEW

**Review by ClementChaumel — COMMENTED** [review]
:+1:

**Comment by anasereijo** [comment]
@cassiocassio's feedback: https://github.com/canonical-web-and-design/ubuntu.com/issues/9291#issuecomment-806688172

**Comment by anasereijo** [comment]
@anthonydillon nice job, thanks a lot! 🥇 

I'm also a bit 50/50 like @cassiocassio regarding the `dropdown-window-overlay`. Without a dropdown, I don't think it's necessary to have it but at the same time I quite like it visually - it's focusing on search. Hopefully, we will soon have the dropdown so maybe worth keeping it?

> * I feel the light-box effect will be appropriate when we are wanting to help the user focus on a set of search suggestions, as @anasereijo sketched, I'm 5050 if it's needed/a bit heavy at this initial stage

Could you please check smaller screens as discussed? Giving you a -1 because of that, soz! :)

**Comment by anthonydillon** [comment]
@cassiocassio thanks, added an esc key listener.

@anasereijo thanks, I have limited to hidden navigation to only large screens.

**Comment by anasereijo** [comment]
awesome! 👍

**Comment by cassiocassio** [comment]
Ah sorry I checked the [esc] key thanks

but too late!  I just noticed

- there's a little jump in height when you open and close

**Comment by cassiocassio** [comment]
- As a (future) enhancement, can we do closing the dialog when clicking outside? I see we do that for light-boxed contact forms...

**Comment by anasereijo** [comment]
I saw the same earlier but for some reason I don't see that anymore 

> 
> * there's a little jump in height when you open and close
> 
>

**Comment by anthonydillon** [comment]
@cassiocassio I can't replicate the movement. Is there a viewport size of browser your are getting it on?

**Comment by anthonydillon** [comment]
@cassiocassio I have added the close when clicking outside of the active search

**Comment by cassiocassio** [comment]
👍

**Review by tbille — APPROVED** [review]

**Pull request merged**
