### PR TITLE
22.04 refresh

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

- Updates for the 22.04 release, see the [epic](https://app.zenhub.com/workspaces/-web-tribe-5931746dba512f05402b61f6/issues/canonical-web-and-design/web-squad/4982)

## QA

**Note: Download links wont work**

- https://ubuntu-com-11501.demos.haus/download/desktop/thank-you?version=22.04&architecture=amd64 - [copydoc](https://docs.google.com/document/d/187Vg9I0Jjlp1_yAjYtHdoEwFCJeVOaz9Kzeb6kptMpA/edit)
- https://ubuntu-com-11501.demos.haus/download/raspberry-pi/thank-you?version=22.04&architecture=desktop-arm64+raspi - [copydoc](https://docs.google.com/document/d/1RXsLbMB-LJVwiG0gAi0HgVEJvZ9_GIU3ESLJ6KmBb54/edit#)
- https://ubuntu-com-11501.demos.haus/server - [copydoc](https://docs.google.com/document/d/1jh4UiFpZutluiUV0z_IYEr7YMAJxA_3WPcnnZuBms6c/edit)
- https://ubuntu-com-11501.demos.haus/desktop/developers - [copydoc](https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit#)
- https://ubuntu-com-11501.demos.haus/desktop/flavours - [copydoc](https://docs.google.com/document/d/1M5nkigcSRzq1YVjiXOZkeU4EUCqT0uYBR3Y_sjxM-wM/edit)
- https://ubuntu-com-11501.demos.haus/desktop/organisations - [copydoc](https://docs.google.com/document/d/1RuxCA6GYh9UriNv26HCZP9UHo4b4_9fYaaMtGQuH_xc/edit#)
- https://ubuntu-com-11501.demos.haus/download/raspberry-pi - [copydoc](https://docs.google.com/document/d/1KgnSBa8mbR7qwlxxtqbE5a1wXh5GjtVums8TIB7IGVw/edit)
- https://ubuntu-com-11501.demos.haus/download - [copydoc](https://docs.google.com/document/d/1ScuTtdrm3-iAvizTDxksVTAerV6QkCUN8Sg60uUlJsk/edit#)

## Issue / Card

Fixes https://app.zenhub.com/workspace/o/canonical-web-and-design/web-squad/issues/4982

### CODE REVIEW

**Comment by anthonydillon** [comment]
QA notes:

- [ ] On the homepage takeover the text is not selectable 
- [ ] On /download/alternative-downloads there are a few mentions of 20.04 LTS
- [ ] On /desktop/organisations there is a placeholder image for some of the heading icons
- [ ] On /certified/desktops, do we need to add 22.04 LTS as a filter option
- [ ] On /server, the title should be "What’s new in 22.04 **LTS**"
- [ ] On /download/xilinx, the title of the download is 22.04 but the link is to 20.04
- [ ] On /download/server/thank-you-s390x, the download buttons have not been updated
- [ ] On /download/alternative-downloads, the link "Instructions for the 22.04 Ubuntu Live installer" should have LTS. Also on that page should the copy change as it refers to 20.04 above.

**Comment by anthonydillon** [comment]
- [ ] On /aws/pro, should we add 22.04 to the list?

**Comment by local-optimum** [comment]
Feedback from current status:
- Flavours page: Needs a header image, 'Looking for Ubuntu?' could do with an Ubuntu logo to make it stand out.
- Thank you page: Could be a glitch from the link, but the message says thank you for your contribution but also still includes the donation widget.
- Raspi download thank you page doesn't work for me
- Desktop for developers: Graph is still in a separate line to 'operating system developers prefer' it should be smaller and adjacent to the text. VERY out of date laptop image on the 'by developers, for developers' section
- Desktop for organisations: Looking good! Banner image needs updating though
- Install Raspberry Pi: good apart from text wrapping on the Zero 2 W, if we remove the space between '2W' would it fit on one line? I think that would be okay
- Download Ubuntu desktop : LGTM :)

**Comment by pmahnke** [comment]
- [ ] very minor, but on /download, the link to the flavours page is a redirect, could be /desktop/flavours directly

**Review by anthonydillon — APPROVED** [review]
Code and QA - LGTM :+1:

**Comment by anthonydillon** [comment]
@local-optimum would you mind having a quick review and giving your +1 if everything in the demo is looking correct.

**Pull request merged**
