### PR TITLE
WIP: Generated actions test

### PR DESCRIPTION
**Pull request by evilnick**
## Done

Adding generated actions

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)

### CODE REVIEW

**Comment by evilnick** [comment]
@pmahnke 
I added one page here: <https://ubuntu-com-8117.demos.haus/kubernetes/docs/charm-kubernetes-master>

This is what it *should* look like:
image

**Comment by pmahnke** [comment]
@evilnick I got rid of `u-table-layout--auto` and made the col-7 to col-10 and it looks better but still a bit squished

image

**Comment by evilnick** [comment]
@pmahnke yeah, that is better than the description not showing at all! I used u-table-layout--auto to give the description a better share of the space. Any idea why it wasn't showing up?

**Comment by pmahnke** [comment]
@evilnick I also think you can get rid of one of the rows... you have the table in a new row

```html
<div class="row">
  <div class="col-2">
    <h5>
      cis-benchmark
    </h5>
  </div>
  <div class="col-10">
    <p>
      Run the CIS Kubernetes Benchmark against snap-based components.
    </p>
    <p>
      This action has the following parameters:
    </p>
    <table class="u-table-layout--auto">
      <thead>
        <tr>
          <th>
            parameter
          </th>
          <th>
            Description
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <pre>apply</pre>
          </td>
          <td>
            <p>
              Apply remediations to address benchmark failures. The default, 'none', will not attempt to fix any reported failures. Set to 'conservative' to resolve simple failures. Set to 'dangerous' to attempt to resolve all failures.
            </p>
            <p>
              Note: Applying any remediation may result in an unusable cluster.
            </p>
            <p>
              <strong>Default:</strong> none
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <pre>config</pre>
          </td>
          <td>
            <p>
              Archive containing configuration files to use when running kube-bench. The default value is known to be compatible with snap components. When using a custom URL, append '#&lt;hash_type&gt;=&lt;checksum&gt;' to verify the archive integrity when downloaded.
            </p>
            <p>
              <strong>Default:</strong> https://github.com/charmed-kubernetes/kube-bench-config/archive/cis-1.5.zip#sha1=cb8e78712ee5bfeab87d0ed7c139a83e88915530
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <pre>release</pre>
          </td>
          <td>
            <p>
              Set the kube-bench release to run. If set to 'upstream', the action will compile and use a local kube-bench binary built from the master branch of the upstream repository: https://github.com/aquasecurity/kube-bench
            </p>
            <p>
              This value may also be set to an accessible archive containing a pre-built kube-bench binary, for example: https://github.com/aquasecurity/kube-bench/releases/download/v0.0.34/kube-bench_0.0.34_linux_amd64.tar.gz#sha256=f96d1fcfb84b18324f1299db074d41ef324a25be5b944e79619ad1a079fca077
            </p>
            <p>
              <strong>Default:</strong> https://github.com/aquasecurity/kube-bench/releases/download/v0.2.3/kube-bench_0.2.3_linux_amd64.tar.gz#sha256=429a1db271689aafec009434ded1dea07a6685fee85a1deea638097c8512d548
            </p>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
```

**Comment by evilnick** [comment]
this is what it looked like when I made the original template in vanilla:
image
(the docs-demo site has a slightly outdated version which doesn't do auto-layout)

**Comment by evilnick** [comment]
@pmahnke and thanks, I'll drop the extra row

**Comment by pmahnke** [comment]
@anthonydillon do you have any thoughts?

**Comment by evilnick** [comment]
okay, I have worked out a different template that doesn't use tables. It doesn't look as good but at least it works. I'm going to raise an issue on `u-table-layout--auto` not behaving as expected in a grid as we may want to use it in future. Thanks

**Pull request closed without merging**
