### PR TITLE
Build engage page and takeover - OpenStack deployment guide (es)

### LINKED ISSUE #3175: Broken image
Under "BOOTSTACK FULLY MANAGED CLOUD CUSTOMERS" the Peer1 logo isn't working.

---
*Reported from: https://www.ubuntu.com/cloud/managed-cloud*

### PR DESCRIPTION
**Pull request by bethcollins92**
## Done

- Build engage page
- Build takeover
- Add them to the 3 pages
- Build social banner

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/es/guía-implementación-openstack and check content matches [copy doc](https://docs.google.com/document/d/1nyF_VA2b5K-Un_Ty9LJBo3Ph4taMlUxv7RdoN4W6ngk/edit) and [brief](https://docs.google.com/spreadsheets/d/16J2T4D9VW0ZUyfBMht_G_z7Ia0mnHKIMcyV_22s4WJk/edit?ts=5f479112#gid=1271849439)
- Change browser primary language to Spanish and check takeover. 
- Check [social banner](https://tools.demos.haus/?title=Gu%C3%ADa+para+la+implementaci%C3%B3n+de+OpenStack&subtitle=Superar+los+desaf%C3%ADos+de+la+adopci%C3%B3n+de+OpenStack+siguiendo+un+proceso+de+adopci%C3%B3n+probado&illustration_url=https%3A%2F%2Fassets.ubuntu.com%2Fv1%2Fdcb2963c-openstack%2Bcloud%2Boutlines.svg&background=dark#banner-form-modal)
- Test the engage page on [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

## Issue / Card

Fixes #3175

### CODE REVIEW

**Comment by bethcollins92** [comment]
@SirSamTumless could you find out the link for the PDF for this please?

**Review by steverydz — COMMENTED** [review]
Looks good, just needs the PDF

**Comment by carkod** [comment]
Need to add this to discourse

**Comment by SirSamTumless** [comment]
@Khutch25 Could you please provide the PDF link?

**Comment by Khutch25** [comment]
@SirSamTumless Very sorry! That is here: https://drive.google.com/file/d/1kzBOp3s01VG31oCkXdoBt3GYkGmknSHR/view?usp=sharing

**Comment by pmahnke** [comment]
@Khutch25 doesn't the pdf have to be on Marketo to count it correctly?

**Comment by Khutch25** [comment]
> @Khutch25 doesn't the pdf have to be on Marketo to count it correctly?

@pmahnke Yes, thank you! 🤦‍♀️  Here's the Marketo link: https://pages.ubuntu.com/rs/066-EOV-335/images/OpenStack_deployment_Spanish.pdf

**Review by steverydz — APPROVED** [review]
LGTM :+1:

**Pull request merged**
