### PR TITLE
Build plan selector changes

### LINKED ISSUE #8870: [ESM Apps] Build plan selector changes
Build the changes specified in [web-squad#3556](https://github.com/canonical-web-and-design/web-squad/issues/3556).

### PR DESCRIPTION
**Pull request by ClementChaumel**
## Done

- I've built [this UI](https://github.com/canonical-web-and-design/master-epics/issues/234#issuecomment-746178227)
- I'm still working on the logic to add esm apps to cart but in the meantime the UI is ready for review

## QA

- View the site at: https://ubuntu-com-8969.demos.haus/advantage/subscribe?test_backend=true
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes #8870 

## Screenshots

image

### CODE REVIEW

**Comment by anasereijo** [comment]
Hey @ClementChaumel 

this is looking great, just a couple of amends:

- [ ] the list should be in one 1 col (correct me if I'm wrong @matthewpaulthomas )
- [ ] align the ESM for apps and section below with the list
Ubuntu-Advantage-for-Infrastructure-Ubuntu
 

- [ ] add extra padding at the bottom to create more space between that section and footer
Ubuntu-Advantage-for-Infrastructure-Ubuntu (1)

**Comment by ClementChaumel** [comment]
Fixed it @anasereijo !

**Comment by anasereijo** [comment]
@ClementChaumel thanks! Looks cool!

Sorry, I just noticed the following:

- [ ] make the list ticked like the other options

Screenshot 2021-01-05 at 11 44 06

- [ ] Also, the text has changed on 14.04 LTS. Please check my design and @matthewpaulthomas [UX ticket](https://github.com/canonical-web-and-design/web-squad/issues/3556)

**Comment by ClementChaumel** [comment]
I've updated the bullet point according to this doc which I believe is the most up to date
https://docs.google.com/document/d/10ldSK8T0Tc-QK7OVZmbs_p-rOH8ujphZGzhfO0QaOi8/edit
Correct me if I'm wrong @matthewpaulthomas

**Comment by anasereijo** [comment]
@ClementChaumel design wise it's a +1  👍

**Comment by matthewpaulthomas** [comment]
Looks promising! Sorry I didn’t realise this until trying it out, but: We shouldn’t offer ESM Apps if you’ve just told us that you’re running Ubuntu 14.04 where it isn’t available. In that case, the checkbox should become unchecked (if it wasn’t already), and then the section should be hidden. [Spec updated](https://docs.google.com/document/d/1K65n3NpZCh7EWDXKLhG31seGJ2jKbW6lqw3BwV2mlnU/edit#bookmark=id.55cdfyqi5b1r).

> make the list ticked like the other options

I almost always agree with Ana, but … I think ticked bullets should be for things someone might realistically want to check the presence of. Like, for example, [the “What you’ll need:” list at the start of a tutorial](https://ubuntu.com/tutorials/how-to-install-ubuntu-desktop-on-raspberry-pi-4#1-overview). The list of features in a UA plan also falls into this category (especially now that there are checkboxes for other UA features below). But not the “You can:” list. Those aren’t things anyone would tick off; they’re alternative courses of action. So if there was [an appropriate icon](https://github.com/canonical-web-and-design/vanilla-framework/issues/3403) for those, it would be an arrow, not a tick. (To put it another way: If this list should have ticked icons, what would be an example of a list that should use the default Vanilla list styling instead?)

**Comment by anasereijo** [comment]
> I almost always agree with Ana, but … I think ticked bullets should be for things someone might realistically want to check the presence of. Like, for example, [the “What you’ll need:” list at the start of a tutorial](https://ubuntu.com/tutorials/how-to-install-ubuntu-desktop-on-raspberry-pi-4#1-overview). The list of features in a UA plan also falls into this category (especially now that there are checkboxes for other UA features below). But not the “You can:” list. Those aren’t things anyone would tick off; they’re alternative courses of action. So if there was [an appropriate icon](https://github.com/canonical-web-and-design/vanilla-framework/issues/3403) for those, it would be an arrow, not a tick. (To put it another way: If this list should have ticked icons, what would be an example of a list that should use the default Vanilla list styling instead?)

Thanks, @matthewpaulthomas these are good points! Let's keep it as it is 👍

**Review by matthewpaulthomas — CHANGES_REQUESTED** [review]
The new elements look good.

**Comment by ClementChaumel** [comment]
I've updated the page according to @matthewpaulthomas 's comments.
I've also made the ESM Apps checkbox functional with a small caveat. It will add UA Apps products to the cart and will override the selected UA Infra product. The reason for this is that "combined" products are missing from the product listing and I'm currently using the "UA Apps only" products as placeholders. I'll switch them as soon as they are added.
image

I still don't know what the other 2 checkboxes are supposed to do.

**Comment by ClementChaumel** [comment]
I've updated the selector to use the correct products and disabled it when desktop is selected because those combined products don't exist for desktop

**Review by matthewpaulthomas — CHANGES_REQUESTED** [review]
> I still don't know what the other 2 checkboxes are supposed to do.

If you check either of them, Infra is included in your plan even if you selected ESM Apps. I’m sorry I didn’t spell out this logic before.

What’s supposed to happen:
 • | “Include ESM Apps” is unchecked | “Include ESM Apps” is checked
-|-|-
Neither of the “other software or updates” checkboxes are checked | UA Infra | UA Apps
Either/both of the “other software or updates” checkboxes are checked | UA Infra | UA Infra+Apps

(I’ve been asked a couple of times: Does this mean “Security updates for OpenStack, Ceph or MAAS, or certified Windows drivers for KVM guests” could be a single checkbox? Yes, it _could_ be, and probably that would make more sense code-wise … but it would be an awful jumble to read.)

What happens in the branch now:
 • | “Include ESM Apps” is unchecked | “Include ESM Apps” is checked
-|-|-
Neither of the “other software or updates” checkboxes are checked | ✔️ UA Infra | ❌ UA Infra+Apps
Either/both of the “other software or updates” checkboxes are checked | ✔️ UA Infra | ✔️ UA Infra+Apps

**Comment by ClementChaumel** [comment]
Thanks that table helped a lot! I've wired the "Other software" checkboxes they should work as expected now.

**Comment by matthewpaulthomas** [comment]
Thanks, the checkboxes all seem to be doing the right thing now.

I didn’t pay enough attention to this earlier:

> I've updated the selector to use the correct products and disabled it when desktop is selected because those combined products don't exist for desktop

That surprises me. [The price book](https://docs.google.com/spreadsheets/d/1AECioud9wmtg4-h7KY1yyRboz2DwjTJt6ESm0GaVVbM/edit) doesn’t list _any_ of the combined products, so how are you determining which ones exist?

Anyway, even if  Infra+Apps Desktop products don’t exist, you should still be able to select Apps Desktop Essential (which _is_ in the price book), and currently you can’t, because the ESM Apps section disappears when you choose Desktop.

Instead I suggest:
- [ ] If someone chooses “Desktop”, the ESM Apps section remains present.
  - [ ] But if there really are no Desktop combined products, the “other software or updates” section becomes hidden, because it would never have any effect.
  - [ ] If someone then says yes to ESM Apps for Desktop, the tech support section becomes hidden, because Apps Desktop Standard/Advanced don’t exist.

**Comment by anasereijo** [comment]
@ClementChaumel what's the status of this?

**Comment by ClementChaumel** [comment]
> @ClementChaumel what's the status of this?

@anasereijo As I understand it, UA Apps is on hold while we build monthly subs

**Comment by anasereijo** [comment]
> > @ClementChaumel what's the status of this?
> 
> @anasereijo As I understand it, UA Apps is on hold while we build monthly subs

@SirSamTumless can you confirm?

**Comment by SirSamTumless** [comment]
That is correct.

**Pull request closed without merging**
