### PR TITLE
Update the docs linkchecker actions

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
- Update the docs linkchecker actions
- Add linkchecker actions to external OpenStack docs

## QA
- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4023

### CODE REVIEW

**Comment by albertkol** [comment]
@anthonydillon we seem to be both updating the current docs git actions. I am doing it in my PR: https://github.com/canonical-web-and-design/ubuntu.com/pull/9533

I'd prefer to have my PR update them as it does some extra stuff, I am explaining in the PR. Let me know what you think about it.

**Comment by albertkol** [comment]
@anthonydillon 
The openstak rules seem nice and clean, but I am curious why do you have to exclude `.css` links, `http://localhost*` and `http://localhost:8001`? 

Are localhost links used in anchor tags? Should they be not plain text?

**Comment by anthonydillon** [comment]
> I'd prefer to have my PR update them as it does some extra stuff, I am explaining in the PR. Let me know what you think about it.

Yeah spotted that, that's fine.

> The openstak rules seem nice and clean, but I am curious why do you have to exclude .css links, http://localhost* and http://localhost:8001?

Exactly there are localhost links in the docs and I'm ignoring css as its crawling images in the css file which are failing.

**Review by albertkol — APPROVED** [review]
:+1:

**Pull request merged**
