### PR TITLE
WIP add azure pro pages

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

- Added /azure/ebook and updated /azure/private-offer

## QA

- View the site in your web browser at: 
  - https://ubuntu-com-11266.demos.haus/azure/ebook
  - https://ubuntu-com-11266.demos.haus/azure/private-offer
    - Be sure to test on mobile, tablet and desktop screen sizes
- See that the design looks good
- Test the form on the ebook page, see that you're able to download the ebook (Blocked: waiting on the asset)
- See that the copy matches the copy doc (Blocked: they don't exist yet)

### CODE REVIEW

**Comment by spencerbygraves** [comment]
Thanks @sowasred2012 a few comments from me...

### Both pages

- Can we make the h2 font weight 300 please
- Both form strips should have the same size heading and hr underneath

### Ebook

- Can you drop the logos below the hero please, same as the other page
- Give the form a grey background please, same as the other page
- Flip the bottom two strips so we have grey form > white > grey

### Private offer

- I think this text should be h2 "Uplevel Ubuntu journey by activating this private Azure Marketplace offer"

Thanks

**Comment by sowasred2012** [comment]
Cheers @spencerbygraves - just made those changes

**Comment by spencerbygraves** [comment]
Thanks for the changes @sowasred2012, looks good.

**Comment by lechsandecki** [comment]
could you share the copy doc for both pages, please? I have a few small adjustments.

**Comment by sowasred2012** [comment]
Closing this PR - we're blocked on the ebook, so I've created the private offer page in a [separate PR](https://github.com/canonical-web-and-design/ubuntu.com/pull/11285) we can get live sooner, with another ebook PR to follow.

**Comment by KhachatryanM** [comment]
@sowasred2012  Hey Scott, I'm attaching the final version of the ebook. https://drive.google.com/file/d/1rg-A6UHKRd0Eu20kWDHTm6kgW_tN7b9w/view?usp=sharing 

I was unable to find the pages, it shows an error from my side. But based on what I saw earlier, here are a couple of comments, 1. if possible spread out the logos under the cover image, 2. the book on the ebook landing page is merging with the background, can we give it a shadow or some other way make it pop? 3. Can the required fields in the forms for both pages be a little closer together or this is standard and can't be changed? 4. Also if download / Get the offer buttons can be green to get more attention? 

There is also a quick fix in the text, but I would love to see the design the send the right comment. Thank you!

**Comment by sowasred2012** [comment]
@KhachatryanM this PR was closed and broken down into two separate ones. The private offer page is now live, and the ebook PR is here: https://github.com/canonical-web-and-design/ubuntu.com/pull/11286

**Pull request closed without merging**
