### PR TITLE
Add topped suru strip to IoT gateways page

### PR DESCRIPTION
**Pull request by MeltySnow**
## Done

Added topped suru strip to IoT gateways page.

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/internet-of-things/gateways
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Ensure that the design matches the [specification](https://github.com/canonical-web-and-design/web-squad/issues/1462)

## Issue / Card

Fixes canonical-web-and-design/web-squad#1462

## Screenshots

image

### CODE REVIEW

**Comment by anasereijo** [comment]
Looks really nice @MeltySnow!

As we are updating this page could we please also change the following:
- [ ] Webinars and case studies section make it light grey `p-strip--light`
- [ ] Quote: make the background white

Thank you

**Comment by MeltySnow** [comment]
@anasereijo Done!

**Comment by anasereijo** [comment]
@MeltySnow thank you 👍

**Comment by solazio** [comment]
@MeltySnow can you please fix the conflicts and then I will give it QA +1

**Comment by MeltySnow** [comment]
@solazio I've resolved the conflicts.

**Pull request merged**
