### PR TITLE
Update /desktop/statistics hero

### PR DESCRIPTION
**Pull request by solazio**
## Done

- Update hero on `/desktop/statistics`

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [/desktop/statistics](http://0.0.0.0:8001/desktop/statistics)
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1582)

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/1583

## Screenshots

[if relevant, include a screenshot]

### CODE REVIEW

**Comment by anasereijo** [comment]
as discussed yesterday, we need to fix the pixelated suru folds. maybe @anthonydillon can help us.

**Comment by anthonydillon** [comment]
@solazio You need to play with the linear-gradients. I would suggest changing them to `49%`

```css
linear-gradient(to bottom left, rgba(228,228,228,0.5) 0%, rgba(228,228,228,0.5) 49%, rgba(228,228,228,0) 50%, rgba(228,228,228,0) 100%),linear-gradient(to bottom left, rgba(119,41,83,0.16) 0%, rgba(119,41,83,0.16) 49%, rgba(119,41,83,0) 50%, rgba(119,41,83,0) 100%),linear-gradient(to bottom left, rgba(255,255,255,0) 0%, rgba(255,255,255,0) 49.0%, #fff 50%, #fff 100%),linear-gradient(-89deg, #e95420 0%, #772953 38%, #2c001e 85%)
```

**Comment by sowasred2012** [comment]
@solazio LGTM :+1:

**Comment by anasereijo** [comment]
@solazio looks good! 👍

**Pull request merged**
