### PR TITLE
Update the content for the Azure proivate offer page

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Update the content for the Azure proivate offer page

## QA
- Open the demo and go to /azure/private-offer
- Check the content matches the suggestions in [the copy doc](https://docs.google.com/document/d/1ZgV1ZiyHJe3UNQkj0I-OCpZ4MIAWLHheig2Q2rclcuk/edit?ts=60d4d594)
- Please approve the suggestions if correct

## Issue / Card
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4221

## Screenshots
image

### CODE REVIEW

**Review by SirSamTumless — APPROVED** [review]

**Comment by SirSamTumless** [comment]
@lindseylopez This has been done and now needs your review. Please give it a PdM+1 if you're happy with the changes based on the demo above.

**Comment by lindseylopez** [comment]
@Sam Thomas ***@***.***> and @Anthony Dillon
***@***.***> I am happy with the changes - PdM+1.

**Comment by lindseylopez** [comment]
Hi Team, wondering the status of this? we really need it done by tomorrow. @SirSamTumless

**Comment by SirSamTumless** [comment]
@lindseylopez This was merged 4 days ago - as per the history above so will have been live by then.

**Pull request merged**
