### PR TITLE
Image builder

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
This branch contains the entire Image builder feature.

## QA

QA at http://imagebuilder.staging.demo.haus/build

- Go to /build
- Sign in
- Select a board, OS and optionally add some snaps.
- Click Build
- You should see a thank you page
- You will **not** receive the completed email as the webhook is targeting production. (It's likely @nottrobin will get the email which he may kindly forward for your QA)
- Once you have the email click the links in the email and check they work

Fixes https://github.com/canonical-web-and-design/web-squad/issues/2387

### CODE REVIEW

**Comment by matthewpaulthomas** [comment]
- [ ] The “You need an Ubuntu One account” box looks to me like a sidebar/promotion, not an integral part of the flow. In [web-squad#2351](https://github.com/canonical-web-and-design/web-squad/issues/2351) I’ve moved the /advantage equivalent to the left. Can we do the same here, please, putting it below the intro paragraph? As a bonus, this lets us drop both the box border and the section separator.

- [ ] Before signing in, steps 2 and 3 are `<section class="`…`u-disable">` inside `<div class="u-disable">`, where `.u-disable {opacity: .2;`…`}`. This results in step 1 having opacity 0.2, but steps 2 and 3 having opacity 0.2 × 0.2 = 0.04. This is both inconsistent, and too light to serve the purpose of letting you know what steps will be involved. I think you need a separate `<section class="`…`u-disable">` around each step.

- [ ] “Got an app that isn’t in the Snap Store? Learn how to publish it as a snap” should never be disabled, as I explained [on Zeplin](https://app.zeplin.io/project/5e33f5075368883e5da9d0bf/screen/5e4fe76fc1b203753a5fa869): “This paragraph is the only part of the flow that should be enabled when you’re signed out — because following the link will help you decide whether Snap Store snaps are practical for your device.”

- [ ] It’s a bit unpolished that when signed out, we say “We’ll email you at once the build is ready.” Could we drop the “at” in that case?

- [ ] The section footer is focused on Ubuntu Core, when you’re moderately likely not to use Ubuntu Core. The section footer seen on [/internet-of-things](https://ubuntu.com/internet-of-things) would be more appropriate.

I’m pausing there because I see the URL is still `/core/build`, so I’m not sure if this is the latest code.

**Comment by anthonydillon** [comment]
@matthewpaulthomas some feed back:
Image builder feedback - 20 March 2020
- Tweak messaging on choosing OS - we are offering complex reasons when it should be more like "for dev and test", "for production".
- core - for production
- step three... remove 'packages' from the paragraph and make it clear its snaps only
- reshape around 20.04 classic and core 20 only
- pi 3,4 and nuc only
- snap appliance maker with classic

**Comment by cassiocassio** [comment]
- "best" for security might tempt users to pick that when they will not have a good experience

- don't offer lots of choice, e.g. 64 vs 32, proffer the best / most likely e.g. pi4 -> 64 bit, others probably 32

- emphasise classic for tinkering prototyping and core for production/final deploy when you don't need to interact, care more about secuitiy

- so:: grey out / only allow confined snaps on core images, allow everything on classic images

**Comment by anthonydillon** [comment]
Don't think we need this one anymore.

**Comment by anthonydillon** [comment]
Sorry not this one

**Comment by anthonydillon** [comment]
@matthewpaulthomas @nottrobin could you please QA this demo and let me know if you're happy. Once you are we can land without linking to it for end to end testing.

**Comment by matthewpaulthomas** [comment]
- [ ] The vertical spacing is a bit wonky. Logically, these values should be in order from smaller to same/larger:
  Between | And | Currently this much space
  -|-|-
  step 1 | step 2 | 5.5rem (4rem + 1.5rem)
  “You are signed in as…”| step 1 | 9.1rem (1.1rem + 4rem + 4rem)
  “Build image” | section footer | 3.2rem (0.6rem + 1.1rem + 1.5rem)

- [ ] “Pi2”, “Pi3“, and “Pi4” should be “Pi 2”, “Pi 3”, and “Pi 4” ([copydoc](https://docs.google.com/document/d/1Hw_8dWAAUpHHm5Z_XNUVJaSVE5k5i2Vt6WANcJYUZvY/edit#heading=h.tb6rip976rup)).
- [ ] “Classic” should not be present ([copydoc](https://docs.google.com/document/d/1Hw_8dWAAUpHHm5Z_XNUVJaSVE5k5i2Vt6WANcJYUZvY/edit#heading=h.ix83by6p2jc5)):
  Current | Expected
  -|-
  Classic 16.04 | 16.04 LTS
  Classic 18.04 | 18.04 LTS 32-bit
  Classic 64-bit 18.04 | 18.04 LTS 64-bit

- [ ] “For Ubuntu Core this will be snaps, for Ubuntu Classic it will be snaps or packages” should not be present ([copydoc](https://docs.google.com/document/d/1Hw_8dWAAUpHHm5Z_XNUVJaSVE5k5i2Vt6WANcJYUZvY/edit#heading=h.ljqjptgrq3m)), since (a) snaps are a kind of package and (b) we aren’t currently offering any other kind of package.

- [ ] Hovering over the search field reveals a tooltip, “Please fill out this field” (a result of `required=""`). This is confusing because it’s a live search, not a submitted one — and because you don’t, in fact, need to “fill out” the field to get a working image.

- [ ] Even though their listboxes are different heights, it still looks awkward for “No matching snaps” and “No snaps to preinstall” not to be aligned. In addition, list empty states are generally horizontally centered, and vertically centered _or_ slightly-above-centered. With a bit of skulduggery, both of these could be fixed at once — perhaps by giving them the same `bottom:` value.

 - [ ] “No snaps to preinstall” is correct in one sense (no snaps _selected_ to preinstall), but not the most obvious sense (no snaps _available_ to preinstall). Would be simpler just to say “None yet”.

- [ ] The architecture notice is good work, but has warts:
  - Shouldn’t really be a notification, since notifications are implicitly temporary things, while this always happens.
  - Even if it should be a notification, beginning “Information:” would be redundant (I’ve submitted [vanilla-framework#3007](https://github.com/canonical-web-and-design/vanilla-framework/pull/3007) to fix this in Vanilla’s example).
  - “its” should be “it’s”.
  - “Your selected architecture is amd64” is a bit confusing, since I didn’t select an architecture.
  - If you have chosen Ubuntu Core, “If you are missing a snap its probably not supported by this architecture” may be true for armhf, but for amd64 I think the more likely reason is one of [the other three](https://docs.google.com/document/d/1Hw_8dWAAUpHHm5Z_XNUVJaSVE5k5i2Vt6WANcJYUZvY/edit#heading=h.ljqjptgrq3m) — “Only public, stable-level, strictly-confined snaps can be added in Ubuntu Core”.

  Not sure how to fix all that yet. I guess the architecture needs to be inserted into that existing explanation.

- [ ] Not required for merging, but the snap lists would be _so_ much more pleasant to use if they could be navigated with Up, Down, and Enter, with Tab / Shift+Tab instead navigating between the two lists.

- [ ] It’s odd for the “We’ll email you” section to be grey, because it means the white section of the page starts before the beginning of the form and ends before the end of the form.

- [ ] “I agree to receive information about Canonical’s products and services” was a temporary placeholder. Should now be “I agree to receive a one-time message when the build is complete” (compulsory) and “Send me more news about Ubuntu on IoT devices” (optional) ([copydoc](https://docs.google.com/document/d/1Hw_8dWAAUpHHm5Z_XNUVJaSVE5k5i2Vt6WANcJYUZvY/edit#heading=h.ljqjptgrq3m)).

I can’t test beyond clicking the button because of `KeyError: 'LAUNCHPAD_TOKEN'`.

**Comment by anthonydillon** [comment]
> Even though their listboxes are different heights, it still looks awkward for “No matching snaps” and “No snaps to preinstall” not to be aligned. In addition, list empty states are generally horizontally centered, and vertically centered or slightly-above-centered. With a bit of skulduggery, both of these could be fixed at once — perhaps by giving them the same bottom: value.

Left this one as it will take sometime to get right so please create an issue for it.

> The architecture notice is good work, but has warts:

I have updated parts of the point but not the core vs classic as mixing thenm can result in different archs.

> Not required for merging, but the snap lists would be so much more pleasant to use if they could be navigated with Up, Down, and Enter, with Tab / Shift+Tab instead navigating between the two lists.

Left, due to time.

> “I agree to receive information about Canonical’s products and services” was a temporary placeholder. Should now be “I agree to receive a one-time message when the build is complete” (compulsory) and “Send me more news about Ubuntu on IoT devices” (optional) (copydoc).


This will require backend work as currently we just don't track you if you do not tick the checkbox but something we need to fix.

**Comment by matthewpaulthomas** [comment]
> Left this one as it will take sometime to get right so please create an issue for it.

Reported as #7359.

> This will require backend work as currently we just don't track you if you do not tick the checkbox but something we need to fix.

What do you mean by “don’t track you”? The checkbox really shouldn’t appear as-is — it looks like a non-sequitur.

A couple more issues:

- [ ] The browser can give the search field an autocomplete menu that obscures the search results. Can be fixed with `automplete="off"`.

- [ ] The search field clear button should not be present when the search field is empty.

**Comment by anthonydillon** [comment]
> What do you mean by “don’t track you”? The checkbox really shouldn’t appear as-is — it looks like a non-sequitur.

We should prevent sending marketing material but not the image build emails as these are operational. If we want the user to agree to some form of t&cs then do we have these or need to have them created?

> A couple more issues:

Addressed your points in this PR: https://github.com/canonical-web-and-design/ubuntu.com/pull/7360

**Comment by matthewpaulthomas** [comment]
> We should prevent sending marketing material but not the image build emails as these are operational.

Fair enough, but then please use a checkbox label that distinguishes it from the compulsory message. Something like “Also send me news about Ubuntu on IoT devices”

**Comment by anthonydillon** [comment]
@matthewpaulthomas thanks, done in https://github.com/canonical-web-and-design/ubuntu.com/pull/7360

**Comment by clagom** [comment]
This is probably a “nice to have” follow up and not a blocker, but on mobile would be nice if the page scrolled automatically to the next step once a choice is made. Otherwise the UI is hidden.

**Comment by nottrobin** [comment]
@clagom filed https://github.com/canonical-web-and-design/ubuntu.com/issues/7372

**Comment by nottrobin** [comment]
Approving this for now so we can get it merged for a soft-launch. On live it can be tested fully end-to-end, which should include sending emails as it should.

We can then decide if there are any issues that are significant enough to block the proper launch, where we actually start pointing people to /build.

**Comment by clagom** [comment]
> @clagom filed #7372

Thanks @nottrobin

**Pull request merged**
