### PR TITLE
Change date format on subscription

### PR DESCRIPTION
**Pull request by ClementChaumel**
## Done

- update date format to dd MMM yyyy

## QA

- Check out those date formats!

## Screenshots
image

Fixes canonical-web-and-design/commercial-squad#421

### CODE REVIEW

**Comment by wgx** [comment]
Why do they need the dots:
image


Why not just 10 Dec 2021.. instead of 10.Dec.2021 ?

**Comment by ClementChaumel** [comment]
> Why do they need the dots: image
> 
> Why not just 10 Dec 2021.. instead of 10.Dec.2021 ?

@wgx updated, PTAL!

**Comment by wgx** [comment]
LGTM! +1

**Review by albertkol — APPROVED** [review]
:+1:

**Pull request merged**
