### PR TITLE
Update text, data and one calculation on /openstack/tco-calculator

### LINKED ISSUE #9224: [COPY UPDATE] charmed-osm.com
Please edit chared-osm.com based on the [copy doc](https://docs.google.com/document/d/1mKfttykmrc4ub_LkqdRGIE_x9WgR1NGr7ulxrLvIZXk/edit?ts=60224421#heading=h.m6z8ibpxu8wt).

### LINKED ISSUE #9244: [COPY UPDATE] tco-calculator - "Private cloud TCO calculator"
Please update tco-calculator - "Private cloud TCO calculator" from the [copy doc](https://docs.google.com/document/d/1n3ExZwFVlw5LyAp7O3CgPthVgx8yRX5-Wg_gBQLf73c/edit?usp=drivesdk) and [sheet](https://docs.google.com/spreadsheets/d/1qOFmJ2zOy0MNqANk1IQnrBgOPhLxwoj7g8Nvyl4y_Ic/edit#gid=0)

Thanks for pointing this out. It looks like the page hasn't been updated after the changes in the pricing in autumn last year.

@Peter Mahnke 

I've updated both the copy doc and the spreadsheet.

Cells changed:

- I36
- I37
- I38
- I45

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

- Updated /openstack/tco-calculator based on pricing changes
- Includes a change in calculations for managed services

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/openstack/tco-calculator
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Compare the text chage to the [copy doc](https://docs.google.com/document/d/1n3ExZwFVlw5LyAp7O3CgPthVgx8yRX5-Wg_gBQLf73c/edit#)
- Compare the calc changes to the [google sheet](https://docs.google.com/spreadsheets/d/1qOFmJ2zOy0MNqANk1IQnrBgOPhLxwoj7g8Nvyl4y_Ic/edit#gid=0)

@tytus-kurek can you check the calculations?

## Issue / Card

Fixes #9244

### CODE REVIEW

**Comment by tytus-kurek** [comment]
@pmahnke the demo page above does not lead me to the TCO calculator page.

**Comment by pmahnke** [comment]
@tytus-kurek yes, it is a demo of the _whole_ site, you have to navigate to it - https://ubuntu-com-9245.demos.haus/openstack/tco-calculator

**Comment by tytus-kurek** [comment]
@pmahnke the data seem to be incorrect again. The default yearly operational cost for managed cloud consisting of 12 nodes should be $65,700. Unless it is, you can assume something is wrong.

I believe what happened in the past is that the calculator on the page got disconnected from the calculator in the spreadsheet. This was because our sales wanted to have 12 nodes by default (9 cloud nodes + 3 infra nodes), while the calculator allowed for 9 as a minimum (just 9 cloud nodes). And the change was only made to the calculator on the page, while it wasn't made to the calculator in the spreadsheet.

I updated the spreadsheet again to avoid any further confusion. Again, cells I43 and I45 have been changed. It looks like it requires another iteration. I'm sorry about that.

**Comment by SirSamTumless** [comment]
@tytus-kurek Can you re-review this please?

**Comment by tytus-kurek** [comment]
Looks good now.

Tytus Kurek | Owner | ITsteer

tkurek@itsteer.com | +48 790 207 297 | www.itsteer.com <tkurek@itsteer.com>

[image: ITsteer] <http://www.itsteer.com/>

**Review by SirSamTumless — APPROVED** [review]

**Pull request merged**
