### PR TITLE
Fix lost renewal bug

### PR DESCRIPTION
**Pull request by albertkol**
## Done

- Fix lost renewal bug

## QA

- Go to https://ubuntu-com-9896.demos.haus?email=email@address.com
- The email address should have an account with both `lost` and `active` renewals

### CODE REVIEW

**Comment by anthonydillon** [comment]
@albertkol sorry your QA steps are too vague. I have gone to the link provided but the standard homepage. Could you provide more detail, please?

**Comment by anthonydillon** [comment]
Why is there no issue for this?

**Comment by albertkol** [comment]
@anthonydillon I created an issue. I thought it's small enough to pass by without one.

I was hoping @alnvdl would take a look instead. He would have more context.. i.e. if my solution is correct; or the email address to QA with;

Here is the context:
https://pastebin.canonical.com/p/HqhRhbVzQd/

**Review by alnvdl — CHANGES_REQUESTED** [review]
This would work for the case in hand, but a more lasting solution would be to only display renewals that have `status == "pending"`.

As for reproducing this, one can test this by creating multiple renewals with different states (lost, pending, closed) in ua-contracts. The renewal guide in was updated a while ago to include such an example: https://github.com/CanonicalLtd/ua-contracts/blob/develop/docs/renewals.md

A list of the possible statuses is available here: https://github.com/CanonicalLtd/ua-contracts/blob/develop/internal/store/store.go#L888-L937

**Comment by albertkol** [comment]
@alnvdl made the change. Back with you. I tested it to reproduce the problem with the email address from the pastebin. The renewal shows up now.

**Review by anthonydillon — APPROVED** [review]
LGTM to fix a live issue

**Pull request merged**
