### PR TITLE
Private cloud takeover

### LINKED ISSUE #6092: [Private Cloud Build WBN] - Build takeover and engage page
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/1dV2RFXNnpLnZBo_Gx_iuyv3qwhppGSyXE3_3dweLbQY/edit#gid=0) and [design](1955):
 
- [x] build takeover
- [x] build engage page
- [x] add takeover to `/takeovers/index.html`
- [x] add takeover to `/index.html`
- [x] add engage page to `/engage/index.html`
- [x] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

- Added private cloud build takeover and webinar

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Refresh the page until you see a takeover with the title "Lessons learned from 100+ Private Cloud Builds"
- See that it matches the [design](https://github.com/canonical-web-and-design/web-squad/issues/1976#issuecomment-552889722) and the [brief](https://docs.google.com/spreadsheets/d/1dV2RFXNnpLnZBo_Gx_iuyv3qwhppGSyXE3_3dweLbQY/edit#gid=2113339190)
- Click the CTA to visit the engage page
- See that it matches the [design](https://github.com/canonical-web-and-design/web-squad/issues/1976#issuecomment-552889722) and the [copy doc](https://docs.google.com/document/d/1EHDg2pDy3KB1DU2hwihoTrCWudTXjAClv0OuJMNmJIc/edit?usp=sharing)
- Test the page on https://cards-dev.twitter.com/validator, ensure the preview contains an image, title and description

## Issue / Card

Fixes #6092

### CODE REVIEW

**Comment by anasereijo** [comment]
- [ ]  The illustration is too big, delete `style="width: 300px;"` and leave the original size

**Comment by Lukewh** [comment]
Seems the Twitter card image isn't in the HTML

**Comment by sowasred2012** [comment]
@Lukewh have noticed the card validator sometimes doesn't pick it up on the first attempt, not sure why. This is what I see when I validate it:

Screenshot 2019-11-13 at 09 36 15

**Comment by Lukewh** [comment]
Surely it depends on which takeover loads when Twitter makes the request? As they cycle through you're not guaranteed to get the takeover you want... Twitter will then also cache the image for x amount of time.

I don't actually see why we're adding individual takeover open-graph images because it's unpredictable - we're better off showing a generic image OR having some way to persist the takeover with a url param (ubuntu.com?t=private-cloud). I don't think a hash would work as it's just an in-page anchor.

**Comment by sowasred2012** [comment]
I think we're talking about two different things:
- as part of this PR, there's a meta image on the [engage page](https://ubuntu-com-canonical-web-and-design-pr-6113.run.demo.haus/engage/private-cloud-build-webinar) which, when run through the [validator](https://cards-dev.twitter.com/validator), will show a card with an image, title and description.

- what I think you're talking about is that the u.c homepage itself doesn't have a meta image. I'm not sure we've ever included a meta image with a takeover as, like you and and Forrest Gump's momma always said, you never know what you're gonna get. That said, maybe the homepage should have one? @anasereijo, what do you think?

**Comment by Lukewh** [comment]
@sowasred2012 you're right, I skipped that crucial QA step of "click the CTA" :+1:

**Pull request merged**
