### PR TITLE
Engage resource filter

### PR DESCRIPTION
**Pull request by carkod**
## Done

Add engage pages resource filter

## QA

- Check https://ubuntu-com-10159.demos.haus/engage
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Select different resources from the dropdown and check that they filter the list of engage pages

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/3874

## Screenshots

Screenshot 2021-08-11 at 15 58 42

### CODE REVIEW

**Comment by pmahnke** [comment]
@carkod why do you have the buttons in the header?

image


Also, what about the tag support that is in the [brief](https://docs.google.com/document/d/17441iNCV46X72YCLSf8Kv-2tl-JXysBagB6-3VaOpKE/edit) and I just created an issue for it, but mentioned in planning.

**Comment by carkod** [comment]
> @carkod why do you have the buttons in the header?
> 
> image
> 
> Also, what about the tag support that is in the [brief](https://docs.google.com/document/d/17441iNCV46X72YCLSf8Kv-2tl-JXysBagB6-3VaOpKE/edit) and I just created an issue for it, but mentioned in planning.

Well, I took the liberty to make some improvements, since new people in Marketing may not know how to add engage pages. Also in terms of UX, there was an awkward separation between title and filters, so I added the strip, and filled it up with that content. Do you want me to remove them?

Also, do you think we should I use a button to submit or do you prefer to update after selection (referring to [the other PR comment](https://github.com/canonical-web-and-design/ubuntu.com/pull/10145)?

**Comment by pmahnke** [comment]
@carkod that seems very internally focused, this page is for end-users... please remove them.

**Comment by carkod** [comment]
> @carkod that seems very internally focused, this page is for end-users... please remove them.

Done.

**Comment by carkod** [comment]
Superseeded by https://github.com/canonical-web-and-design/ubuntu.com/pull/10192

**Pull request closed without merging**
