### PR TITLE
Update the /managed page

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
- Updated the copy on the /managed page.

## QA
- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/managed
- Check the content matches the [copy doc](https://docs.google.com/document/d/17zJ4vTutqVpn0XzUI784BHdJov8cGW1ttDwIjsvcEzE/edit#heading=h.qp7hfvggs6wp)

## Issue / Card
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3074

## Screenshots
image

### CODE REVIEW

**Review by steverydz — APPROVED** [review]
Code looks good. I'll leave the QA to marketing and design

**Comment by SirSamTumless** [comment]
Sent to Nilay, Sarah and Davide for review.

**Comment by meralonso** [comment]
@anthonydillon page is looking good. I have a few changes, please see design below 

Managed - Overview

**Comment by anthonydillon** [comment]
@meralonso Thanks for the design. I have applied the differences.

**Comment by anthonydillon** [comment]
@SirSamTumless thanks, has marketing been made aware of this PR?

**Comment by SirSamTumless** [comment]
This is good to go!

**Pull request merged**
