### PR TITLE
Fix top website 404s

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

- redirects for favicons.ico, favicons.png, robots.txt, humans.txt, usn/atom.xml
- added a sitemap.xml generated from https://www.xml-sitemaps.com/

# QA

- download this branch
- run the site and make sure everything looks ok
- go to:
    - http://0.0.0.0:8001/favicon.ico
    - http://0.0.0.0:8001/favicon.png
    - http://0.0.0.0:8001/humans.txt
    - http://0.0.0.0:8001/robots.txt
    - http://0.0.0.0:8001/static/files/sitemap.xml
    - http://0.0.0.0:8001/usn/atom.xml
- see that they all make sense

## Screenshots

```
               .-.
         .-'``(   )
      ,`\ \    `-`.
     /   \ '``-.   `
   .-.  ,       `___:
  (   ) :        ___
   `-`  `       ,   :
     \   / ,..-`   ,
      `./ /    .-.`
         `-..-(   )
               `-`
```
### greylog 

image

### CODE REVIEW

**Comment by anasereijo** [comment]
@pmahnke, sorry but the designer in me can't let this go:

Would look awesome these were left aligned :) :) :)

https   ubuntu com canonical web and design pr 5336 run demo haus static files humans txt

**Comment by solazio** [comment]
@anasereijo the indentation has been fixed now. Can you please review again.

**Comment by anasereijo** [comment]
@solazio looks the same

**Comment by solazio** [comment]
@anasereijo use hard refresh when you check as it might be cached. It looks fine for me.
image

**Comment by anasereijo** [comment]
@solazio 👍

**Pull request merged**
