### PR TITLE
add /advantage link to /support subnav

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

Added "Your subscriptions", linking to /advantage, to /support subnav

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/support
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
-See that there is a link to "Your subscriptions" in the subnav
- Follow the link and check you arrive at /advantage, and the subnav is still present
- On any page, see that "Your subscriptions" is present in the "Support" section of the footer navigation

## Issue / Card

Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8600

### CODE REVIEW

**Comment by sowasred2012** [comment]
@pmahnke (or whoever QAs this) have added a "UX needed" label to this cos I have a question: the link is in the /support subnav, but since /advantage doesn't live under /support, the subnav disappears once you get to the page - is that OK? It seems weird to me.

**Comment by sowasred2012** [comment]
@nottrobin would love your feedback on this.

To summarise: we have added /advantage as a subnavigation item to /support's navigation. We want /advantage _not_ to move to /support/advantage, but to still share the same navigation. This is a change from how we setup navigation everywhere else, but that's what has been requested.

What I've done (and will document in the readme if you agree with it), is add an `alias` key to the support entry in navigation.yaml, and if the current URL path matches either the entry's path or alias, it will show the subnav. What do you think?

**Comment by sowasred2012** [comment]
@matthewpaulthomas thanks for the tip! Turns out "persist" on a navigation object does what we were wanting here...

**Comment by matthewpaulthomas** [comment]
Visible merge conflict in the payment dialog:

image

**Comment by sowasred2012** [comment]
@matthewpaulthomas needed rebasing - updated

**Comment by matthewpaulthomas** [comment]
✔ /advantage signed out
✔ /advantage/subscribe signed out
✔ Purchase dialog
✔ /advantage/subscribe/thank-you
   (BTW, paying does not take me to /advantage/subscribe/thank-you. Why not?)

✔ /advantage signed in
✔ /advantage/subscribe signed in

✔ global footer

⚠ This is not a complete fix for #8600 because it doesn’t change the “Products” menu.

**Comment by sowasred2012** [comment]
@matthewpaulthomas good point - I've updated that link in global-nav (https://github.com/canonical-web-and-design/global-nav/pull/162), and updated the version of global-nav here.

**Comment by sowasred2012** [comment]
Don't merge yet - `advantage-shop` branch is currently being demoed to Mark.

**Review by steverydz — APPROVED** [review]
LGTM :+1:

**Pull request merged**
