### PR TITLE
Redesign wizard

### PR DESCRIPTION
**Pull request by ClementChaumel**
## Done

- Implemented [this design](https://app.zeplin.io/project/601d6513b99f24a8412ecfa5/screen/604f8218789166993567404f)
- And [this behaviour](https://www.figma.com/proto/eUNwJ9cJXWaNWjIZlxMLnC/UA-Shop?node-id=23%3A20813&viewport=2224%2C-984%2C0.42681482434272766&scaling=min-zoom)
- Replaced the previous state management by redux in prevision of the react rewrite.

## QA

- Go to https://ubuntu-com-9458.demos.haus/advantage/subscribe?test_backend=true
- Play around with the product selector and verify that it behaves correctly
- Verify that the UI is matching the designs
- Make a purchase using 5555 5555 5555 4444444444.... and check that it goes through correctly

## Issue / Card

Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9432 and https://github.com/canonical-web-and-design/web-squad/issues/3900

Blocked because copy is missing from feature coverage section @lechsandecki :
image

### CODE REVIEW

**Comment by anasereijo** [comment]
Hey, @ClementChaumel nice work! Some amendments, hopefully not too much work for you.
(I will review small screens on a separate comment)

screencapture-ubuntu-com-9458-demos-haus-advantage-subscribe-2021-03-25-12_16_31



Screenshot 2021-03-25 at 12 45 18

**Comment by anasereijo** [comment]
@ClementChaumel few things on small screens:

Screenshot 2021-03-25 at 14 17 39

Screenshot 2021-03-25 at 14 20 42

**Review by anthonydillon — APPROVED** [review]
LGTM must simpler to follow but due to the size may have missed some out of place logic. It's worth getting CS team to QA.

**Comment by elioqoshi** [comment]
Thanks @ClementChaumel !

This is more of a visual thing but I feel the spacing is off in the version selection information box (bottom):
image

Also there is no modal appearing when clicking on "Are you using an older version?" in the ubuntu version step. 

Further, on very low width's we might want to break the 2 columns into a single column a bit earlier, otherwise this happens:

image

**Comment by anasereijo** [comment]
This is looking much better, thanks!

Just one thing a few things on small screens:
Maybe I didn't explain it properly, but on smaller screens, I was expecting to see the Infrastructure and Applications cards on the same row and the Apps + Infra down below and full width. And when the screen gets too small (around 455px wide) we will see 1 card per row, making them full width. I can jump on a call and explain it better if you want.

I also noticed this:
Screenshot 2021-03-29 at 10 26 54

**Comment by anasereijo** [comment]
> This is more of a visual thing but I feel the spacing is off in the version selection information box (bottom) (@anasereijo is that right?):
> image
> 

yeah, I noticed the same @elioqoshi but @ClementChaumel said that's vanilla. Would be nice to fix it though if not too much work (or we can propose to fix next cycle?) See below what I designed. I split the container into two 2 cols:

Screenshot 2021-03-29 at 10 32 31

**Comment by elioqoshi** [comment]
Small thing here in the modal but not a dealbreaker:

grafik

As this might a Vanilla thing, this should not block us here. Merci @ClementChaumel !

**Comment by ClementChaumel** [comment]
> Small thing here in the modal but not a dealbreaker:
> 
> grafik
> 
> As this might a Vanilla thing, this should not block us here. Merci @ClementChaumel !

I've opened an issue to discuss this in the vanilla repo https://github.com/canonical-web-and-design/vanilla-framework/issues/3674

**Pull request merged**
