### PR TITLE
Add release names on the chart

### LINKED ISSUE #10850: Could we include names with the 16.04, 18.04, 20.04 etc?
Would it be possible to get the names added here for the ones without?  This is confusing to people outside Canonical as well as new hires (like, me!).

Thanks!

---
*Reported from: https://ubuntu.com/about/release-cycle*

### PR DESCRIPTION
**Pull request by minkyngkm**
## Done

- Added release names on `/about/release-cycle`

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/about/release-cycle
- Be sure to test on mobile, tablet and desktop screen sizes
- [Demo](https://ubuntu-com-10919.demos.haus/about/release-cycle)

## Issue / Card

Fixes #10850 

## Screenshots

image

## Help

[QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html) - [Commit guidelines](https://canonical-web-and-design.github.io/practices/workflow/commit-messages.html)

### CODE REVIEW

**Comment by minkyngkm** [comment]
Hi @davegoddard42! Does these names need to be added on mobile as well? Here is [Demo](https://ubuntu-com-10919.demos.haus/about/release-cycle) :)

**Comment by davegoddard42** [comment]
@minkyngkm yes please! Do you need a design for that?

PS. Looking awesome 👍

**Comment by minkyngkm** [comment]
Thanks! @davegoddard42 just need the names for `Ubuntu 12.04 LTS` and `Ubuntu 10.04 LTS`. Do you know of those names by any chance?

**Comment by davegoddard42** [comment]
Ubuntu 10.04 LTS (Lucid Lynx)

Ubuntu 12.04 LTS (Precise Pangolin)

**Comment by minkyngkm** [comment]
@davegoddard42 Does this look okay on mobile? :) 
image

**Comment by davegoddard42** [comment]
Yeah that's fine. Tables are always hard on mobile. That's clear and
readable. Thanks again.

**Review by mtruj013 — APPROVED** [review]
LGTM!

**Comment by davegoddard42** [comment]
@pmahnke Did you get a chance to check with Marketing if this (removal of Ubuntu) is acceptable? I can ask myself I f you like.

**Pull request merged**
