### PR TITLE
Reduce API calls in details view

### PR DESCRIPTION
**Pull request by carkod**
## Done

Reduce API calls in details view

## QA

- Everything should remain unchanged i.e. download links, content etc...
e.g. https://ubuntu-com-9804.demos.haus/certified/201808-26455

## Issue / Card

Fixes https://github.com/canonical-web-and-design/certification.ubuntu.com/issues/180

### CODE REVIEW

**Comment by codersquid** [comment]
Did you mean to target master?

**Comment by carkod** [comment]
> Did you mean to target master?

wait it's not ready yet

**Comment by codersquid** [comment]
The code changes look ok, but don't you need to regenerate the cassette files for the tests?

**Comment by carkod** [comment]
> The code changes look ok, but don't you need to regenerate the cassette files for the tests?

It's ready now

**Review by codersquid — APPROVED** [review]
lgtm

**Comment by bethcollins92** [comment]
QA LGTM 👍🏼

**Pull request merged**
