### PR TITLE
Restyle site search to match the design

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Restyle site search to match [the design](https://app.zeplin.io/project/5ffdb21a3714151de9cf750c/screen/5ffdb2ce647d0519ad789d5d).

## QA
- Open the demo
- Click on the search and see it reveals the search box and focuses
- When you type a close icon appears which resets the search
- Check on small screens.

## Issue / Card
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9290

### CODE REVIEW

**Comment by carkod** [comment]
I think you may need to remove some styles I added before. If you write too much content the X overlaps with the content

Screenshot 2021-03-19 at 13 11 03

I don't know which is the latest design, but isn't it supposed to extend to the whole width of the nav?
Screenshot 2021-03-19 at 13 14 48

**Comment by wgx** [comment]
Aside from the text overlap issue @carkod notes above, this is fine UX-wise and good to go. 👍🏽

**Comment by anthonydillon** [comment]
@carkod thanks, I've removed all the search styling and it works much better now.

**Review by pmahnke — APPROVED** [review]
it is awesome!

**Comment by anasereijo** [comment]
this is cool, thanks @anthonydillon 
as discussed could you please fix mobile and also fix the underline text

**Pull request merged**
