### PR TITLE
Build page on /certified/why-certified

### PR DESCRIPTION
**Pull request by minkyngkm**
## Done
**BLOCKED:** waiting on a link to the data sheet 
- Build page on `/certified/why-certified`

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
-Please check page against [copy doc](https://docs.google.com/document/d/1q3rOtDgJ_7_seGCP5pbCKyJYzXLvY45y8gis2FSKxXI/edit#)
- Demo at https://ubuntu-com-11132.demos.haus/certified/why-certified

## Issue / Card

Fixes [#4728](https://github.com/canonical-web-and-design/web-squad/issues/4728)

## Screenshots
Why Certified? | Security | Ubuntu (2022-01-10 15-04-43)

## Help

[QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html) - [Commit guidelines](https://canonical-web-and-design.github.io/practices/workflow/commit-messages.html)

### CODE REVIEW

**Comment by carkod** [comment]
Do we have a design, briefs (didn't find any in the issue) or copy docs we can compare with?

**Comment by minkyngkm** [comment]
Hey @carkod thanks for reviewing! Copy doc is [here](https://docs.google.com/document/d/1q3rOtDgJ_7_seGCP5pbCKyJYzXLvY45y8gis2FSKxXI/edit#)

**Review by carkod — APPROVED** [review]
LGTM, just a couple of things:
- The "Up to 10 years security update commitment" has more margin than the other paragraphs, is this intended?
- You seem to be aware of this, the "Read the datasheet" link is not correct

**Comment by davegoddard42** [comment]
LGTM. I need to sort out the data sheet but otherwise this is great

**Comment by minkyngkm** [comment]
@carkod Good catch! I didn't know that. I have made an update for that. Thanks! :)

**Pull request merged**
