### PR TITLE
Update text of /telecommunications page

### LINKED ISSUE #5756: [COPY UPDATE] /telecommunications
Please update /telecommunications from the [copy doc](https://docs.google.com/document/d/15FY_IaT39V81FQcoSoEJpmRRjBX80PJ7uxjgzHnDDws/edit?usp=drivesdk)

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

- A very large update to /telecommunications

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/telecommunications
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Compare to the [copy doc](https://docs.google.com/document/d/15FY_IaT39V81FQcoSoEJpmRRjBX80PJ7uxjgzHnDDws/edit#heading=h.t5nt9uvsqry)
- Provide design guidence - images, layout, double quotes, etc...

## Issue / Card

Fixes #5756

### CODE REVIEW

**Comment by anasereijo** [comment]
@pmahnke this page needs to be redesigned. I will create an issue and design it instead of leaving comments here. What's the deadline for this?

**Comment by anasereijo** [comment]
@pmahnke design here https://github.com/canonical-web-and-design/web-squad/issues/1712

**Comment by pmahnke** [comment]
@anasereijo I have updated the design... I also made the list 8/4 cols to match the below sections and added the Bell logo that was missing, but provided in the mean time.

**Comment by anasereijo** [comment]
- [ ] add bottom padding to the following section:
Open source NFV platform for 5G   Ubuntu

- [ ] remove the bottom border and make it like the previous section
Open source NFV platform for 5G   Ubuntu (1)


- [ ] the following hr lines are not full width, please fix:

Screenshot 2019-09-25 at 16 00 04


note: we should plan to look at our logo clouds across u.com and try to make it work as Lyubo's code (like on MAAS)

**Comment by pmahnke** [comment]
@anasereijo updated

**Comment by anasereijo** [comment]
@pmahnke perfect

**Pull request merged**
