### PR TITLE
Build charmed openstack adoption takeover and engage page

### LINKED ISSUE #7037: [Whitepaper] Charmed OpenStack - OpenStack Adoption Guide] - Build takeover and engage page
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/16TXgQqDczbvzs1vyTAJIbA32VEcHy9QVVe5jFKt3Xis/edit#gid=2113339190) and [design](https://github.com/canonical-web-and-design/web-squad/issues/2502):
 
- [x] build takeover
- [x] build engage page
- [x] add takeover to `/takeovers/index.html`
- [x] add takeover to `/index.html`
- [x] add engage page to `/engage/index.html`
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Built charmed openstack adoption takeover and engage page

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Reload the page until you see the takeover with the heading "A guide to a successful OpenStack adoption and deployment"
- Check that the CTA takes you to /engage/charmed-openstack-adoption-whitepaper
- Check that the form on the engage page works
- Check that the takeover and engage page match [the brief](https://docs.google.com/spreadsheets/d/16TXgQqDczbvzs1vyTAJIbA32VEcHy9QVVe5jFKt3Xis/edit#gid=2113339190) and [the design](https://github.com/canonical-web-and-design/web-squad/issues/2502)
- Test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

## Issue / Card

Fixes #7037

### CODE REVIEW

**Comment by steverydz** [comment]
@SirSamTumless This still needs the PDF linked to on the thankyou page. Also do we know which takeover (if any) is meant to come down?

**Comment by spencerbygraves** [comment]
Thanks @steverydz looks good.

**Comment by SirSamTumless** [comment]
The links are now in [the brief](https://docs.google.com/spreadsheets/d/1bkM14vEn8noJcQVphj9B_iGV6suh6NYoJncmG-5e_D4/edit#gid=877682240).

**Comment by steverydz** [comment]
@SirSamTumless Someone with access needs to update the "Download now" link to the PDF. Once that's done this can go live.

https://pages.ubuntu.com/AdoptionGuide_TY.html

**Comment by SirSamTumless** [comment]
That's good to go!

**Pull request merged**
