### PR TITLE
Fix "Public cloud" from wrapping in the secondary nav

### LINKED ISSUE #7796: Public cloud webpage - Navbar issue
image

---
*Reported from: https://ubuntu.com/public-cloud*

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

- Fix "Public cloud" from wrapping in the secondary nav

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/public-cloud
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- See that the word doesn't wrap like on live.

## Issue / Card

Fixes #7796

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
I don't think this looks very good. I think a design should consider it.
image

**Comment by anthonydillon** [comment]
It also opens us up to issues if the section name is longer.

**Comment by pmahnke** [comment]
@lyubomir-popov could you look at this as you designed the nav.

Basically, it is wrapping, so either:

a. we make the orange box bigger everywhere
b. we add nbsp like have here and live with it
c. ???

**Comment by lyubomir-popov** [comment]
@pmahnke Is this the longest string that has to fit there? If so then reducing the font-size to match the menu to its right (.875rem) should solve it: 

image

**Comment by pmahnke** [comment]
@anthonydillon I lowered the font-size as @lyubomir-popov recommended

**Pull request merged**
