### PR TITLE
[Certified improvements] - update cards on /certified

### PR DESCRIPTION
**Pull request by bethcollins92**
## Done

- Update cards on `/certified` following [design](https://app.zeplin.io/project/60c1ca887b99f18a380e57e9/screen/60f169f609a79e0cf2039ba5)

## QA

- View the page at: https://ubuntu-com-10063.demos.haus/certified
- Check the cards match the [design](https://app.zeplin.io/project/60c1ca887b99f18a380e57e9/screen/60f169f609a79e0cf2039ba5) - this PR is to update the design only, it has the updated copy from the [copy doc](https://docs.google.com/document/d/1pSkPo5fvgrLb-Tjiq_he9MAvPLFX79xiz-H9s2mSXgI/edit) (the copy in the design is out of date).

## Issue / Card

Fixes [#4256](https://github.com/canonical-web-and-design/web-squad/issues/4256)

## Screenshots

Screenshot 2021-07-22 at 11 30 20

### CODE REVIEW

**Comment by anasereijo** [comment]
@bethcollins92 couple of things are not matching the design:

Screenshot 2021-07-22 at 11 47 49

**Comment by bethcollins92** [comment]
@anasereijo wups, fixed - thanks!

**Comment by anasereijo** [comment]
Thanks!

**Review by carkod — APPROVED** [review]
LGTM. Not sure if @davegoddard42 wants to take a look?

**Comment by davegoddard42** [comment]
> LGTM. Not sure if @davegoddard42 wants to take a look?

@carkod LGTM too. The copy not being equal looks weird but we need the copy from the PM - it's been agreed it's coming later.

**Pull request merged**
