### PR TITLE
Add Getting Started with AI takeover and landing page

### PR DESCRIPTION
**Pull request by solazio**
## Done

- Add Getting Started with AI takeover and landing page
- Add mobile CTA to [/engage/451-automotive](http://0.0.0.0:8001/engage/451-automotive) landing page as it was missing

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/), [/engage/451-automotive](http://0.0.0.0:8001/engage/451-automotive) and [/engage/ai-gettingstarted](http://0.0.0.0:8001/engage/ai-gettingstarted)
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Compare to [brief](https://docs.google.com/document/d/1TOfGfuNOGfAjNQEPyOJ0G6JRznwsb-FUe4xL378CG0Q/edit#)
- Check design

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/1220

### CODE REVIEW

**Comment by solazio** [comment]
@WendyS1000 can you please check these:
https://ubuntu-com-canonical-web-and-design-pr-5293.run.demo.haus/
https://ubuntu-com-canonical-web-and-design-pr-5293.run.demo.haus/engage/ai-gettingstarted

**Comment by WendyS1000** [comment]
Looks good from my side. I've tried adding a Marketing + 1 label to this - let me know if what I've done is right.

**Comment by solazio** [comment]
@WendyS1000 I can see the Marketing +1. Thanks

**Comment by anasereijo** [comment]
@solazio social media banner https://assets.ubuntu.com/v1/dd0f6313-social+embedded.jpg

**Comment by anasereijo** [comment]
looks good! 👍

**Comment by WendyS1000** [comment]
Thanks!  Marketing +1

**Pull request merged**
