### PR TITLE
Add takeover and engage page for enterprise kubernetes

### LINKED ISSUE #8115: [Whitepaper] Enterprise K8s challenges - Build the Takeover + Engage page
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/1dboZFvt4v3-xxru2_0ub3uLYQIPT3ouOWcxfjHuKHug/edit#gid=2113339190) and [design](3021):
 
- [ ] build takeover
- [ ] build engage page
- [ ] add takeover to `/takeovers/index.html`
- [ ] add takeover to `/index.html`
- [ ] add engage page to `/engage/index.html`
- [ ] build a [social banner](https://tools.demos.haus/) and use the 1200px x 630px one
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Added takeover and engage page for enterprise kubernetes

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Reload the page until you see the "Five strategies to accelerate Kubernetes in the enterprise" takeover
- Check that it matches [the brief](https://docs.google.com/spreadsheets/d/1dboZFvt4v3-xxru2_0ub3uLYQIPT3ouOWcxfjHuKHug/edit#gid=2113339190)
- Click through to the engage page
- Check that it matches [the brief](https://docs.google.com/spreadsheets/d/1dboZFvt4v3-xxru2_0ub3uLYQIPT3ouOWcxfjHuKHug/edit#gid=1271849439) and [the copy doc](https://docs.google.com/document/d/13N3GiKatgyCyrPyWBer3hTsJHoS7J0H51hVTJC8GAc4/edit)

## Issue / Card

Fixes #8115

### CODE REVIEW

**Comment by SirSamTumless** [comment]
https://pages.ubuntu.com/five-strategies-enterprise-kubernetes.pdf  @steverydz

**Comment by steverydz** [comment]
> https://pages.ubuntu.com/five-strategies-enterprise-kubernetes.pdf @steverydz

@SirSamTumless that link redirects to ubuntu.com ?

**Comment by SirSamTumless** [comment]
https://pages.ubuntu.com/rs/066-EOV-335/images/five-kubernetes-strategies-enterprise.pdf this should work @steverydz

**Comment by anthonydillon** [comment]
@steverydz there are some suggestions to the engage page which looks like that want included. https://docs.google.com/document/d/13N3GiKatgyCyrPyWBer3hTsJHoS7J0H51hVTJC8GAc4/edit

**Review by anthonydillon — APPROVED** [review]
LGTM :+1: with a few suggestions in the engage page copydoc.

**Pull request merged**
