### PR TITLE
Update /openstack/install

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

- Updated /openstack/install per the [copy doc](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc/edit#)

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/openstack/install
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- See that the page matches the [copy doc](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc/edit#)

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/1787

### CODE REVIEW

**Comment by anasereijo** [comment]
Hi @sowasred2012 few amends:

I will send you the amended screenshots soon

**Comment by anasereijo** [comment]
@sowasred2012 2 more things

Screenshot 2019-10-16 at 11 31 49

**Comment by anasereijo** [comment]
Hi @sowasred2012 thanks for doing this.

Just 2 more things:

- [ ] some of the images are white therefore we can't really see the edges. Could you add a [border](https://docs.vanillaframework.io/patterns/images/) to them? 

- [ ] please add some padding between these:

Screenshot 2019-10-16 at 15 32 38
Screenshot 2019-10-16 at 15 32 09

**Comment by sowasred2012** [comment]
@anasereijo thanks - have updated

**Comment by anasereijo** [comment]
@sowasred2012 add a border to this image too:

Screenshot 2019-10-16 at 16 00 04

**Pull request merged**
