### PR TITLE
Update desktop/developers hero

### PR DESCRIPTION
**Pull request by solazio**
## Done

- Update hero on `/desktop/developers`

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [/desktop/developers](http://0.0.0.0:8001/desktop/developers)
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1578)

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/1579

## Screenshots

[if relevant, include a screenshot]

### CODE REVIEW

**Comment by anasereijo** [comment]
@solazio 

- [ ] please fix the image size as per my request on [design ticket](https://github.com/canonical-web-and-design/web-squad/issues/1578)

- [ ] center the image by using  `u-align--center`

- [ ] I suggest deleting this `style="top: 105px; left: 50%;` as it seems like it's not doing anything

**Comment by anasereijo** [comment]
can you please take the `?w=380` from the image link (as we did for another page) as it's making the image look low res? could you also start doing that for all images we come across? thanks

**Comment by pmahnke** [comment]
@anasereijo please

- [ ] remove the `is-divided` from the list in 'Why use Ubuntu for development?'
- [ ] consider removing `is-boardered` from the top banner

**Comment by anasereijo** [comment]
@solazio 

- [ ] make the 'Why use Ubuntu for development?' light grey

- [ ] remove the `is-divided` from the list in 'Why use Ubuntu for development?'

**Comment by anasereijo** [comment]
@solazio perfect 👍

**Pull request merged**
