### PR TITLE
Add extra copy and button to logged out /advantage

### PR DESCRIPTION
**Pull request by ClementChaumel**
## Done

- Added free trial paragraph to logged out /advantage
- Added a button to a pre-filled product selector

## QA

- go to https://ubuntu-com-10006.demos.haus/advantage?test_backend=true
-  Click the button and see that it brings you to a modal where you can start the trial

## Screenshots

image

### CODE REVIEW

**Comment by SirSamTumless** [comment]
@lechsandecki Please 👀  this.

**Comment by wgx** [comment]
This is great. @anasereijo should the text go full-width rather than wrap?

**Comment by anasereijo** [comment]
> This is great. @anasereijo should the text go full-width rather than wrap?

@wgx yes, I agree, although I am not sure if vanilla allows doing that - @ClementChaumel can you please check that?

@ClementChaumel - Can you please add a bit more padding to the top so it matches the bottom?

I am not sure about the hierarchy of these titles - @wgx this one is for you. Is 'Introducing a free trial of ESM Apps' same level as 'Plans for enterprise use'?

**Comment by wgx** [comment]
@anasereijo I think heirarchy is ok for now - this is more of a temporary promo than a permanent thing. Happy with it.

**Comment by lechsandecki** [comment]
looks great. I'd just change "ESM Apps Essential" to "Ubuntu Pro Essential" - this would include Essential: Infra + Apps, and we would also do it for Infra and for Apps separately.

**Comment by lechsandecki** [comment]
ok, and please let's use 30,000 packages instead of 28,000
28k corresponds to the Ubuntu Universe repository, but we need to remember that Ubuntu Main (over 2,500) is also included hence over 30k.

**Comment by ClementChaumel** [comment]
> > This is great. @anasereijo should the text go full-width rather than wrap?
> 
> @wgx yes, I agree, although I am not sure if vanilla allows doing that - @ClementChaumel can you please check that?
> 

Yeah the line length is defined in vanilla

**Comment by ClementChaumel** [comment]
Sorry I messed up this PR somehow, please continue the discussion here: https://github.com/canonical-web-and-design/ubuntu.com/pull/10014

**Pull request closed without merging**
