### PR TITLE
Update pie-chart with suggestions

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

- Updates pie-chart as per suggestions on the [copydoc](https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit#)

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/openstack/consulting or at https://ubuntu-com-10376.demos.haus/openstack/consulting
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)

## Issue / Card

Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10359

## Screenshots

Screenshot from 2021-09-16 14-57-55

### CODE REVIEW

**Comment by long-chung** [comment]
Is this based off an existing pie chart from a previous design?
Wondering why only Ubuntu has a key?
Maybe we should list all the OS's with their respective values?

**Comment by petesfrench** [comment]
@long-chung This is based on suggestions from the [copydoc](https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit#), we spoke about getting a design on it but decided I should just build it and then get a design review and go from there. I tried to base it off other pie-charts I found on the site but it was mostly guess work.
As for the key, this was just a suggestion from the pdm, but I could add in the others if you think it will look better. Would that include the values also?

**Comment by long-chung** [comment]
@petesfrench Hey Peter, The pie chart looks great, all good on that end. 
Just having 1 key was not really helpful, so would be good if you could list all the keys alongside their values.

I knock something out in [Zeplin](https://zpl.io/2G5wLMj). Let me know what you think?

**Comment by petesfrench** [comment]
@long-chung Looks great! I will work on implementing that and let you know when it is done.

**Comment by cristinadresch** [comment]
@petesfrench is this ready for review? could you confirm please

**Comment by petesfrench** [comment]
@cristinadresch @long-chung It is ready for review now. I had to make some changes to make it work with different screen sizes. Including replacing the chart with a table on small screens as the chart wont fit. I could spend more time to make it responsive but then it will have to wait until the next iteration.

**Review by mtruj013 — APPROVED** [review]
LGTM!

**Pull request merged**
