### PR TITLE
1179: add lime telco landing page and takeover

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

- added Lime telco takeover and landing page

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001](http://0.0.0.0:8001)
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Refresh the page until you see a takeover featuring the Lime Systems logo, see that it matches the [brief](https://docs.google.com/document/d/1Dzzfmkaq7_m2Y4ySjkqXcHVDjcYAEsNPbbwz6J64B5I/edit#)
- Click the CTA to visit the landing page, see that it matches the [designs](https://github.com/canonical-web-and-design/web-squad/issues/1174#issuecomment-501216906) and the [copy doc](https://docs.google.com/document/d/126V5e7cQ7ICiP0MAZlrTNsZ_xHknG5VTtcj_T-cUrwM/edit?ts=5cf63918)

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/1179

### CODE REVIEW

**Comment by sowasred2012** [comment]
This is blocked until we get the UTM campaign code, which @WendyS1000 is looking at.

**Comment by WendyS1000** [comment]
@sowasred2012 is this just the demo for the takeover atm? I am waiting for the name of the Lime Salesforce campaign from Sarah/Thibau. (I've broken my phone, so I don't can't access the SSO authentification to log into Salesforce to get the campaign name).

**Comment by anasereijo** [comment]
- Takeover looks perfect! 🥇 
- Landing page: change the logo to be 320px wide

**Comment by anasereijo** [comment]
@WendyS1000 it's also the demo for the landing page. Just click on the takeover button and it'll get you to the LP

**Comment by WendyS1000** [comment]
@sowasred2012 thanks for confirming. Here is the UTM for the takeover: https://ubuntu.com/engage/ubuntu-lime-telco?utm_source=Takeover&utm_medium=Takeover&utm_campaign=FY19_IOT_UbuntuCore_Whitepaper_LimeSDR

@anasereijo I also need to send the link to Sarah to preview. Will keep you posted about any feedback.

**Comment by sowasred2012** [comment]
@WendyS1000 thanks for that - I've just added the campaign codes to the demo.

**Comment by WendyS1000** [comment]
@anasereijo, @sowasred2012 the whitepaper does not seem to be downloading. Can you please douvle check. Thanks! https://pages.ubuntu.com/Whitepaper_LimeSDR_TY.html

**Comment by solazio** [comment]
> @anasereijo, @sowasred2012 the whitepaper does not seem to be downloading. Can you please douvle check. Thanks! https://pages.ubuntu.com/Whitepaper_LimeSDR_TY.html

@WendyS1000, @anasereijo, @sowasred2012  that happens because the pdf is not yet available. It happened the same last week with a takeover.

**Comment by WendyS1000** [comment]
@solazio thanks for clarifying. I have followed up on the final PDF with Sarah.

@anasereijo, @sowasred2012 here is feedback from Sarah. (the header image needs a more telco related image as per her instructions below). 

"Hello, general feedback is similar to the social image. I'd like the landing page and TO to represent more what the whitepaper is about rather than just the Lime whitepaper. So an icon that represents something telecom related and then the Lime logo features somewhere smaller. It doesn't need to be pride of place. Especially on the LP, as they aren't mentioned in the copy (which was intentional) so it particularly doesn't make any sense who they are."

**Comment by anasereijo** [comment]
> @solazio thanks for clarifying. I have followed up on the final PDF with Sarah.
> 
> @anasereijo, @sowasred2012 here is feedback from Sarah. (the header image needs a more telco related image as per her instructions below).
> 
> "Hello, general feedback is similar to the social image. I'd like the landing page and TO to represent more what the whitepaper is about rather than just the Lime whitepaper. So an icon that represents something telecom related and then the Lime logo features somewhere smaller. It doesn't need to be pride of place. Especially on the LP, as they aren't mentioned in the copy (which was intentional) so it particularly doesn't make any sense who they are."

Hey @WendyS1000 thanks for the feedback. I will redesign the takeover. I know it wasn't you briefing me but it would be great to have this kind of ideas for illustrations on the brief before we do all the design and build work - I will leave a comment for Sarah on the brief. Thank you

**Comment by anasereijo** [comment]
@sowasred2012 added Design -1 label as I'm redesigning the takeover. I will let you know when it's ready again.

**Comment by anasereijo** [comment]
@sowasred2012 

-[ amended designs](https://github.com/canonical-web-and-design/web-squad/issues/1174#issuecomment-501216906)
- [illustration](https://assets.ubuntu.com/v1/4ba0e3a6-Joint+Lime-illustration-white.svg)
- illustration on desktop 390px wide
- illustration on mobile 250px wide
- gradient: `background-image: linear-gradient(44deg, #171717 0%, #181818 9%, #262626 34%, #2D2D2D 67%, #383838 88%, #2E2E2E 100%, #393939 100%);
`
- [suru left](https://assets.ubuntu.com/v1/e9f7cb35-left.svg)
- [suru right](https://assets.ubuntu.com/v1/9e4ec700-right.svg)
- [social media ](https://assets.ubuntu.com/v1/b739cc2c-social.jpg)

**Comment by anasereijo** [comment]
@sowasred2012 looks good design wise!

**Comment by anasereijo** [comment]
@WendyS1000 can you please have a look?

**Comment by anasereijo** [comment]
@solazio the PDF isn't downloading so I'm changing the QA label to -1

**Comment by WendyS1000** [comment]
@solazio @sowasred2012 @anasereijo  
1. Where is the PDF at the moment? Is it with Sarah for final review, or is Brand making changes to it? 

2. It also doesn't look like the meta tags been added on this page to be able to display Twitter images on Twitter cards. When I input the url in Twitter's Card Validator here, https://cards-dev.twitter.com/validator, the output will look like this: (it may be incorrect because this is a demo link).

Twitter-Card-Validator-Lime-Telco- 2019-06-14 14-09-23

Here's an example of how a Twitter Card should display:
If you type in https://ubuntu.com/engage/ai-gettingstarted?utm_source=Takeover&utm_medium=Takeover&utm_campaign=CY19_DC_AI_WBN_GettingStartedWithAI into https://cards-dev.twitter.com/validator, it displays like this: (correct). 

Twitter-Card-Validator-AI-webinar-landing-page

By adding this meta data we are making it easier for people to share our content, either by posting the link to Twitter manually or by clicking on Share button (which we intend to add to pages at some point).

Thanks!

**Comment by anasereijo** [comment]
@WendyS1000 the PDF is with Sarah

**Comment by WendyS1000** [comment]
@anasereijo thanks - and the meta tags for Twitter?

**Comment by sowasred2012** [comment]
@WendyS1000 the meta tags are on me - I've just corrected the image meta tag:

Screenshot 2019-06-14 at 14 49 48

**Comment by WendyS1000** [comment]
@sowasred2012 brilliant, thanks very much! 

@sowasred2012 and @solazio please can the Twitter meta data be added to all our /engage page templates (case study, whitepaper, webinar - have I left anything out?). Thibau said he would like this met data to be added to all other pages so that people can share our content easily. This may need discussion because I don't know everything that's involved with a request like this. Thanks!

**Comment by anasereijo** [comment]
@WendyS1000 I believe we already have an [issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/5261) for that

**Comment by WendyS1000** [comment]
@anasereijo excellent!

**Comment by sowasred2012** [comment]
@WendyS1000 @anasereijo looks like the PDF is there now - could I get another review when you have a second pls?

**Comment by anasereijo** [comment]
@sowasred2012 cool! all good
@WendyS1000 can you please double check?

**Comment by WendyS1000** [comment]
@anasereijo, @sowasred2012 I am just double just double checking that the PDF is the correct version (with Sarah) and that Lucia received my form test as expected. Will keep you posted. Thanks!

**Comment by WendyS1000** [comment]
@anasereijo, @sowasred2012, @SirSamTumless this is ready to go live! Thanks!

**Pull request merged**
