### PR TITLE
Add contact form for /kubernetes/managed

### PR DESCRIPTION
**Pull request by bethcollins92**
## Done

- Add contact form for /kubernetes/managed

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/kubernetes/managed
- Follow the 'Talk to us' link and check the contact form against the [copy doc](https://docs.google.com/document/d/1iikqgW0rAFHRN-mAnlUArtF2cDt0OA0C4OheveP120w/edit#)

## Issue / Card

Fixes [#4142](https://github.com/canonical-web-and-design/web-squad/issues/4142)

## Screenshots

image

### CODE REVIEW

**Review by anthonydillon — CHANGES_REQUESTED** [review]
QA: 
There is no padding at the bottom of the form
image

**Comment by anthonydillon** [comment]
@bethcollins92 I have added a few comments to the copy in the copy doc. Also, can you move the "Have we missed something?" field to the previous page as custom field is captured when you switch to the final contact form.

**Comment by bethcollins92** [comment]
Thanks @anthonydillon, made those changes and filed an [issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/9795) to fix the padding

**Comment by anthonydillon** [comment]
Still need to address the "Have we missed something?" field

**Comment by bethcollins92** [comment]
@anthonydillon  Have we missed something is on page 2? 
image

**Review by anthonydillon — APPROVED** [review]
See it now. LGTM :+1:

**Pull request merged**
