### PR TITLE
Fix logo alignment

### PR DESCRIPTION
**Pull request by minkyngkm**
## Done

- Aligned logos and texts center

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/managed/apps
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Please check page against [copy doc](https://docs.google.com/document/d/1fLRWW-Gtslaia2ypSrLJVBxZVHo5FY5Q84o97Gs2-w4/edit)
- Please check the page on smaller screens as well

## Issue / Card

Fixes [#4405](https://github.com/canonical-web-and-design/web-squad/issues/4405#event-5265868395)

## Screenshots
image

image

### CODE REVIEW

**Comment by minkyngkm** [comment]
Since the logos sizes are all different and also their margins are all different in their images, the alignment doesn't look like perfectly good. Was wondering if I need to divide the width in the ratio 3:7 or something. 

Screenshot 2021-09-08 at 9 01 55 am

**Comment by SirSamTumless** [comment]
@long-chung Can you please get back to @minkyngkm?

**Comment by long-chung** [comment]
The ratio of the logos start to go squish horizontally. Is there anyway to control this when scaling down?
Also on tablet the logos are really close too each other and the divider lines go missing.

See screenshots

Screenshot 2021-09-08 at 09 52 41
Screenshot 2021-09-08 at 09 54 39

**Comment by minkyngkm** [comment]
> Also on tablet the logos are

Thanks @long-chung for reviewing 🙏🏻. The height of logos is all `80px` for some reason. But I suppose it's because the original logo sizes' are all different so to manage the size all the logos' height is fixed to `80px` and each width changes proportionally to the 80px So if I remove the fixed 80px, it looks like this - some logos get to be too big and others too small : 
image

**Comment by long-chung** [comment]
@minkyngkm
Heya, on tablet the icons are fine, my comment was more about keeping the dividers until the logos stack.

**Comment by minkyngkm** [comment]
> @minkyngkm
> Heya, on tablet the icons are fine, my comment was more about keeping the dividers until the logos stack.

@long-chung Oh okay. I will try to fix that! 👌🏻 How about the logo and text alignment on mobile? 
Was wondering if I need to divide the width and make the logo and text align all center like this:
132478744-e7acc932-7217-448a-b4fc-b6e1a3507737

**Comment by long-chung** [comment]
@minkyngkm Thats a great idea. It would also solve alignment issues if you range the text left instead of centred on mobile

**Comment by minkyngkm** [comment]
> @minkyngkm Thats a great idea. It would also solve alignment issues if you range the text left instead of centred on mobile

@long-chung Thanks Long! :) I have updated it a bit. Would it look better now? 
Also, regarding the divider line missing on tablet, its because of vanillla think. Please refer to [this](https://vanillaframework.io/docs/examples/patterns/matrix). It goes missing here as well - so I made some logos a bit smaller instead. Please let me know what you think! :)

**Review by bethcollins92 — APPROVED** [review]
LGTM 👍🏼

**Pull request merged**
