### PR TITLE
fix: use side navigation instead of sticky table of contents

### LINKED ISSUE #10838: Add expandable sections to /legal table of contents sticky navs
From @lechsandecki:

Hi team,

The table of contents (on the right) on the new uasd page is not working correctly. I also have an idea that could help improve it further.

[the page] https://ubuntu.com/legal/ubuntu-advantage-service-description

    [the bug] (being addressed in https://github.com/canonical-web-and-design/ubuntu.com/issues/10835)
    [an improvement idea] Could we have collapsable/extendable sub-topics that I could manage dynamically? It could help us make the table of contents shorter.

many thanks
Lech

### PR DESCRIPTION
**Pull request by SaidMarar**
## Done

- This feature add accordions vanilla-framework to table of contents sticky.

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- go to
     - http://127.0.0.1:8001/legal/ubuntu-advantage-service-description
     - http://127.0.0.1:8001/legal/ubuntu-advantage-service-description/ja

## Issue / Card
Fixes #10838 

## Screenshots

toc-accordions

## Help

[QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html) - [Commit guidelines](https://canonical-web-and-design.github.io/practices/workflow/commit-messages.html)

### CODE REVIEW

**Comment by sowasred2012** [comment]
Demo: https://ubuntu-com-10852.demos.haus/legal/ubuntu-advantage-service-description

**Comment by davegoddard42** [comment]
@lechsandecki Looking at the items in the navigation, does each one need a link? For example:

image

Would it be enough to have just "kubernetes" or is it important for both items listed underneath to have their own links? Those sections are very short.

**Comment by davegoddard42** [comment]
Good work on getting this done - thanks a lot @SaidMarar , but I think there's some other things we can tackle here with this navigation.

I would prefer the nav to be on the left, not right of the content. The accordion in Vanilla doesn't allow headers to be discrete links - on click they open the accordion. Having the 'expand' action on the icon only and a link on the work can be a tricky operation to get right. I also think the styling of the items shouldn't be links. 

There is an issue [here](https://github.com/canonical-web-and-design/vanilla-framework/issues/3817) that proposes a left hand navigation component in Vanilla that would be perfect for what we're trying to do here. I'd suggest we solve the sticky scrolling issue, then attempt a better navigation once the component has been added to Vanilla. 

Earliest that work will commence is January. Is this an acceptable time frame @cristinadresch?

**Comment by lechsandecki** [comment]
I agree, that's a great suggestion, Dave. This looks too granular as an
item in the menu - we can cut it short

**Comment by SaidMarar** [comment]
@davegoddard42 Thanks for your feedback :) i think the way how this page was developed, it was supposed to use table of content (a vanilla component) so i just extend it by integrating accordion on it. 
What i did here, i tried to separate the two functionalities from being in one:
1- A button (our icon) that only toggles the submenu.
2- A link with its previous functionality anchoring.
accordion

I don't know if this approach is good for accessibility but it makes user not confused about an element that does two things at the same time.

If not, As you mentioned above we can use the Side Navigation Component instead of using Table of content component.
Example: https://juju.is/cloud-native-kubernetes-usage-report-2021
In this example the side navigation is sticky and has a vertical scroll that shows up when it does not fit with the height, absolutely it will solve the scroll issue.

I'll start integrating side navigation in this page ASAP.

**Comment by SaidMarar** [comment]
@davegoddard42 this is the result of using side navigation, what do you think ? there is little bit of js work to manage clicked menus and update state of active one. I saw the doc pages, they are using the same thing but js is inside HTML script tag ^^

image

**Comment by davegoddard42** [comment]
@SaidMarar I think this looks great. Thanks a lot for all your contributions to this.

**Comment by SaidMarar** [comment]
@davegoddard42 On small screens should we close side navigation after we click on link or we keep it opened ?

**Comment by davegoddard42** [comment]
@SaidMarar Close after click please.

**Comment by SaidMarar** [comment]
> @SaidMarar Close after click please.

Done :)

**Review by sowasred2012 — APPROVED** [review]
This is great, thank you very much @SaidMarar !

**Pull request merged**
