### PR TITLE
Kubernetes landing page refresh

### PR DESCRIPTION
**Pull request by jpmartinspt**
## Done
Kubernetes landing page refresh

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- [List additional steps to QA the new features or prove the bug has been resolved]

### CODE REVIEW

**Comment by anasereijo** [comment]
### 'Public cloud Kubernetes powered by Ubuntu' section

- [ ] can you add the class `u-sv3` to the subtitle so it adds a bit more space below?

logo links and sizing:
- [ ] [Microsoft azure](https://assets.ubuntu.com/v1/22fd6473-MicrosoftAzure_logo.svg): 151x42
- [ ] AWS: 88x52
- [ ] Google Cloud: 104x86
- [ ] IBM cloud: 191x44
- [ ] [oracle cloud logo](https://assets.ubuntu.com/v1/f3be98eb-oracle-cloud-logo.png) 164x86

-----
### 'Kubernetes with Canonical support' section

- [ ] 'Kubernetes with Canonical support' should be `<h2>`
- [ ] can you add the class `u-sv3` to the title/subtitle so it adds a bit more space below?
- [ ] [Microk8s](https://assets.ubuntu.com/v1/1781735b-Microk8s.svg) height:104px
- [ ] [Charmed k8s ](https://assets.ubuntu.com/v1/63a03a52-CharmedK8s.svg) height: 104px
- [ ] add the class `u-sv3` to both images

-----
### FULLY-SUPPORTED KUBERNETES PRIVATE CLOUDS' section

- [ ] [MAAS](https://assets.ubuntu.com/v1/ab9dcc58-maas_black-orange.svg) height: 40px
- [ ] LXD height:40px
- [ ] Joyent height:40px
- [ ] [Rackspace](https://assets.ubuntu.com/v1/ff936628-rackspace.svg) height:40px
- [ ] [Cloudsigma](https://assets.ubuntu.com/v1/760109ef-CloudSigma_Logo_Full.png) height: 50px
- [ ] [Openstack](https://assets.ubuntu.com/v1/314085ad-openstack.svg) height: 40px
- [ ] [vmware](https://assets.ubuntu.com/v1/d584bd83-logo-vmware.svg) height:32px

----

- [ ] 'Fully-managed Kubernetes' image size: 284x200px
- [ ] 'Take control of your Kubernetes' image size: 213x200px
- [ ] 'Integrated cluster management platforms 290x200px
- [ ] logos: follow the design order 
- [ ] can you reduce the space between list and logos?
- [ ] rancher 162x24
- [ ] portainer 137x40
- [ ] azure arc 70x50


----

###  'Full stack K8s services' section

- [ ] can you add the class `u-sv3` to the title/subtitle so it adds a bit more space below?
- [ ] can the subtitle be just in 1 line?
- [ ] add more space above 'Bootstrap your Kubernetes journey'

----

###  'Kubernetes resources' section

- [ ] title should be `<h2>`
- [ ] icon sizes and headings are wrong: you can check an example [here](https://ubuntu.com/security/esm)

----

###  'contac us' section

- [ ] vertically align text and image

**Comment by anasereijo** [comment]
on small screes please hide the following images/logos:
Screenshot 2021-04-29 at 16 26 54
Screenshot 2021-04-29 at 16 27 27
Screenshot 2021-04-29 at 16 27 41
Screenshot 2021-04-29 at 16 27 59
Screenshot 2021-04-29 at 16 28 16
Screenshot 2021-04-29 at 16 28 33
Screenshot 2021-04-29 at 16 28 46
Screenshot 2021-04-29 at 16 29 22

**Comment by jpmartinspt** [comment]
@anasereijo I think I've done it all, thanks for the detailed feedback :)

**Comment by anasereijo** [comment]
I think you forgot to update the following:

### 'Kubernetes with Canonical support' section

- [x] [Microk8s](https://assets.ubuntu.com/v1/1781735b-Microk8s.svg) height:104px
- [x] [Charmed k8s ](https://assets.ubuntu.com/v1/63a03a52-CharmedK8s.svg) height: 104px

-----

- [ ] can we have the 3 logos in the same line as per design? happy to jump 

----

- [ ] headings are still wrong: should be muted as per [example](https://ubuntu.com/security/esm)

Screenshot 2021-04-30 at 10 02 53


Happy to jump on a call to go through this if it's easier.

**Comment by anasereijo** [comment]
+1

**Review by pmahnke — APPROVED** [review]
+1

**Pull request merged**
