### PR TITLE
Change UA page

### LINKED ISSUE #9911: [Dev] Changes to add support portal link, remove sign in line, remove beta banner
As per #9910

### PR DESCRIPTION
**Pull request by albertkol**
## Done

- Remove the "Ubuntu pro on prem" beta invitation banner
- Remove the "You are signed in as {email} [Sign out]" line
- Add a link to the support potal

## QA

- Check the changes above on this link: https://ubuntu-com-9926.demos.haus/advantage

## Issue / Card

Fixes #9911

### CODE REVIEW

**Comment by wgx** [comment]
UX+1

We just need to check https://support.canonical.com/s/ is the correct URL to land people on.. I'll ask around.

**Comment by wgx** [comment]
@albertkol Yep - the URL is correct. 👍🏽

**Comment by carkod** [comment]
I still see the banner _pro on prem_ when I am logged out?

Screenshot 2021-06-23 at 17 39 56

**Comment by wgx** [comment]
@lechsandecki Do you also want the beta banner removed for un-authenticated (public) users?

**Comment by lechsandecki** [comment]
yes and yes! thank you

**Review by ClementChaumel — APPROVED** [review]
Looking good!

**Comment by wgx** [comment]
@albertkol We need to also remove the beta banner for un-authenticated (public) users.

**Comment by albertkol** [comment]
Removed it from both not logged /advantage page and from /advantage/subscribe

**Pull request merged**
