### PR TITLE
Update ua messages good

### PR DESCRIPTION
**Pull request by solazio**
## Done

- Update commands on /advantage

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/advantage
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Make sure the command list has been updated as mentioned in [the issue](https://github.com/canonical-web-and-design/web-squad/issues/1850)

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/1850

## Screenshots

[if relevant, include a screenshot]
image

- Error when personal_account data cannot be retrieved - **You will not be able to see this state**
image

### CODE REVIEW

**Comment by anasereijo** [comment]
@solazio not sure if the positioning is correct in terms of hierarchy as I am not aware of why/how/when this could happen? Maybe @matthewpaulthomas can help if he is aware?

Visually, I would like to see the error box just in one line? 

Thanks

**Comment by solazio** [comment]
> @solazio not sure if the positioning is correct in terms of hierarchy as I am not aware of why/how/when this could happen? Maybe @matthewpaulthomas can help if he is aware?
> 
> Visually, I would like to see the error box just in one line?
> 
> Thanks

@anasereijo happy with this?
image

**Comment by anasereijo** [comment]
@solazio can I see more of the page? It's hard to tell if this version is better by just seeing that section cropped.

Still not sure if needs to be below or  before the title as I said in my previous comment... I think @matthewpaulthomas will be able to help us more on that. Or @pmahnke

**Comment by solazio** [comment]
@anasereijo 
image

**Comment by anasereijo** [comment]
Thanks @solazio. It looks better full width.

**Pull request merged**
