### PR TITLE
Update powerful to scalable in the GSI engagement

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
- Update the copy based on a request in [the copy doc](https://docs.google.com/document/d/1ZweTXyHO9kIU9aE8pw2_Ni_NoBShM_KseY5H2XtGueg/edit).

## QA
- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/gsi-webinar-series
- Check the word has changed

## Issue / Card
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8214

### CODE REVIEW

**Review by cristinadresch — APPROVED** [review]
Looks like you changed it in a couple of files and the demo link wasn't pointing me to the one in the copy doc, but all changes seem right so approving.

**Comment by anthonydillon** [comment]
@cristinadresch yeah there is a lot of duplicated content with engage pages. These changes are for the index pages such as ubuntu.com/engage and ubuntu.com/takeovers.

**Comment by anthonydillon** [comment]
Remember labels :+1:

**Comment by cristinadresch** [comment]
@anthonydillon i cant believe i missed the labels, thats the most fun part of approving stuff! next level will be merging it

**Pull request merged**
