### PR TITLE
Update TCO calculator contact form

### PR DESCRIPTION
**Pull request by bethcollins92**
## Done

- Remove old `tco-calculator.html` as it's been replaced
- Update [contact us](https://docs.google.com/document/d/1n3ExZwFVlw5LyAp7O3CgPthVgx8yRX5-Wg_gBQLf73c/edit?disco=AAAAOSt-wZQ) to have only contact information inputs visible to the user, but:
  - have default values for all the previous [fields](https://docs.google.com/document/d/1n3ExZwFVlw5LyAp7O3CgPthVgx8yRX5-Wg_gBQLf73c/edit#heading=h.q4y1ndq4o59i) 
  - If the user has updated the input fields on the page then use these values instead
- Pass these hidden values to Marketo 

## QA

- View page at: https://ubuntu-com-10527.demos.haus/openstack/pricing-calculator
1.  Click "Get in touch"
2.  Check the default data populates the comment by checking `Comments_from_lead__c.value` in the console returns all the fields and default values
3.  Now change one of the inputs e.g. vCPUs or Number of instances
4. Repeat step 2 and check the updated value is seen in the comment.
5. Fill in the form with test data to check it submits ok

## Issue / Card

Fixes [#4430](https://github.com/canonical-web-and-design/web-squad/issues/4430)

### CODE REVIEW

**Comment by bethcollins92** [comment]
@anthonydillon would you be able to take a look at this please? 

I've added all the fields that existed before as hidden so they can still be concatenated to send in the comments.
Not sure how to QA, I couldn't see the values by checking `Comments_from_lead__c.value` in the console. But locally I console logged `comment.value` from [here](https://github.com/canonical-web-and-design/ubuntu.com/blob/master/static/js/src/dynamic-forms.js#L294) and the values were there. Not sure if I'm missing anything?

**Comment by bethcollins92** [comment]
@anthonydillon I moved the `comment.value = createMessage()` after the modal loaded event is fired, to ensure the `updateFormFields()` function is run and the values are updated _before_ the comment is created. As the values from the inputs are only grabbed when the user clicks "Get in touch" and the `conactModalLoaded` event is fired, we don't need to add event listeners to the inputs.

**Review by anthonydillon — DISMISSED** [review]
Code looks good and works but the submit is failing due to a number of fields missing in Marketo.
https://sentry.is.canonical.com/canonical/ubuntu-com/issues/21346/

**Comment by anthonydillon** [comment]
@caldav could you help here please?

**Comment by pmahnke** [comment]
I have done a bit of work here:

I added `Comment from lead` and `Job title` to the [form](https://engage-sj.marketo.com/?munchkinId=066-EOV-335#/classic/FO4062A1LA1).

@bethcollins92 you need to update `name="jobTitle"` to `name="title"`

@caldav you need to add:

{
'code': '1006', 
'message': 'Field 'support-level' not found'
}, 
{
'code': '1006', 
'message': 'Field 'cloud-achitecture' not found'
},

**Comment by bethcollins92** [comment]
Thanks @pmahnke, done

**Comment by caldav** [comment]
Sorry for missing the pings. I've created both `tcocalc_cloud_architecture__c` and `tcocalc_support_level__c` in the form backend, please use these.

**Comment by bethcollins92** [comment]
@pmahnke I've updated the fields with those names - hope this is correct

**Comment by bethcollins92** [comment]
@anthonydillon your requested changes review is blocking this PR is it ok to dismiss it as Peter has +1'd it?

**Comment by anthonydillon** [comment]
Thanks for the heads up @bethcollins92

**Pull request merged**
