### PR TITLE
Add advantage beta form

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
- Add advantage beta interactive form
- Added a small notification to the top of the page to call users to join the beta

## QA
- Go to /advantage/subscribe
- See that the notification content matches the [content from the brief](https://docs.google.com/document/d/1NoXtzQniQ-puVggi1JDcjUEeVVngKtlmFB86u_FYWBo/edit)
- Click the link
- Check the interactive form matches the [content for the form](https://docs.google.com/document/d/1qrJVP2C1l36WLHRXtBMtF9BwzIkAdLXoKmoNmZZd3Lw/edit#heading=h.dxn10eelvkoc)
- Submit the form and check there are no errors and the XHR request to save2 endpoint contains the form info in the request payload
- I have checked the submission is getting to Marketo

## Issue / Card
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3905

## Screenshots
image

### CODE REVIEW

**Comment by wgx** [comment]
Suggestion, move banner:
image

Sugesstion, embolden the critical sentence in this large-ish paragraph:

image

@lechsandecki

**Comment by anasereijo** [comment]
@anthonydillon I like @wgx's suggestion - could you please do that? giving you a +1 :)

**Comment by wgx** [comment]
LGTM 👍🏽

**Comment by anasereijo** [comment]
👍

**Comment by SirSamTumless** [comment]
@lechsandecki This is good to go with your +1

**Comment by lechsandecki** [comment]
this looks great, thanks! I added a few minor changes in the copy doc: https://docs.google.com/document/d/1qrJVP2C1l36WLHRXtBMtF9BwzIkAdLXoKmoNmZZd3Lw/edit#

The ua client work is not done yet, so we will need to hold on a few days, before putting it live. Thanks for the very quick turnaround. Much appreciated!

**Comment by anthonydillon** [comment]
@lechsandecki thanks, the changes have been applied.

**Comment by lechsandecki** [comment]
this looks great. Thank you!

**Comment by SirSamTumless** [comment]
@wgx to help Lech with copy

**Comment by anthonydillon** [comment]
@lechsandecki any ideas on this one? It's far passed the 12th now.

**Pull request merged**
