### PR TITLE
Add Smart Start takeover

### LINKED ISSUE #8119: [Takeover] Smart Start - Build the Takeover
## Requirements

Please build a takeover  based on this [brief](https://docs.google.com/spreadsheets/d/193Rdm62tRugCxkQ2YBRK2hlP4bctPi_AAuDFz7fvRsU/edit?ts=5f325452#gid=2113339190) and [design](3021):
 
- [ ] build takeover
- [ ] add takeover to `/takeovers/index.html`
- [ ] add takeover to `/index.html`
- [ ] build a [social banner](https://tools.demos.haus/) and use the 1200px x 630px one
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

Note; the Engage page was done, we just need a takeover done for it.

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Add Smart Start takeover

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Reload the page until you see a takeover "Accelerating IoT device time to market"
- Check that it matches [the brief](https://docs.google.com/spreadsheets/d/193Rdm62tRugCxkQ2YBRK2hlP4bctPi_AAuDFz7fvRsU/edit?ts=5f325452#gid=2113339190)

## Issue / Card

Fixes #8119

### CODE REVIEW

**Review by anthonydillon — CHANGES_REQUESTED** [review]
Code looks good but the download is missing from the download page: https://pages.ubuntu.com/Timetomarket_TY.html

**Comment by SirSamTumless** [comment]
https://pages.ubuntu.com/rs/066-EOV-335/images/IoT_Device_time2market_30.06.20.pdf @steverydz Here's the PDF link.

**Comment by steverydz** [comment]
@anthonydillon the PDF is there now

**Comment by SirSamTumless** [comment]
Works for me @steverydz!

**Review by SirSamTumless — APPROVED** [review]

**Pull request merged**
