### PR TITLE
desktop/features - applied suru headings

### LINKED ISSUE #1575: 500 page to VBT

### PR DESCRIPTION
**Pull request by anasereijo**
## Done

- updated hero with suru
-resized image from hero (laptop)

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Check if matches the [design](https://github.com/canonical-web-and-design/web-squad/issues/1574)

## Issue / Card

Fixes #1575

### CODE REVIEW

**Comment by deadlight** [comment]
On medium viewports, it looks like:
image

You can avoid this by changing the col containing the text from `class="col-6"` to `class="col-6 col-medium-4"`

**Comment by anthonydillon** [comment]
@deadlight done

**Comment by deadlight** [comment]
image
Are we fixing the mismatched top/bottom padding?

**Comment by anasereijo** [comment]
@deadlight, @anthonydillon promised me to fix that class so it will be fix across all sections using that same suru. Let's hope he keeps his promises.

**Comment by anthonydillon** [comment]
@anasereijo I have removed the bespoke padding bottom on the half and half strip.

**Comment by anasereijo** [comment]
@deadlight could you please have a final look? thanks

**Pull request merged**
