### PR TITLE
Fix engage thank-you pages and <space>&nbsp;

### LINKED ISSUE #8659: "Ver m´s  ›" should be "Ver más".
## Summary

Related content cards on spanish engage thank-you pages say "Ver m´s  ›" instead of "Ver más".

## Screenshot

Screenshot from 2020-11-04 15-35-54

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

- Fix engage thank-you pages and `<space>&nbsp;`

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/es/kubernetes-despliegue-empresa-manual/thank-you and http://0.0.0.0:8001/engage/pt/vmware-para-o-openstack/thank-you
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- See that the a accute (á) works and 'Whitepaper' are capitalised

## Issue / Card

Fixes #8659

## Screenshots

see a acute
image

see capitalised whitepaper
image

### CODE REVIEW

**Comment by carkod** [comment]
There is also an "n" missing in the Spanish thank you page line 60 templates/engage/shared/_es_thank-you.html -  También

**Comment by SirSamTumless** [comment]
Can you give this a reivew @carkod ?

**Comment by carkod** [comment]
> Can you give this a reivew @carkod ?

Sorry also mentioned that Line 49  should be - Disculpa

**Comment by pmahnke** [comment]
@carkod fixed Disculpa

**Review by carkod — APPROVED** [review]
Thanks! LGTM

**Pull request merged**
