### PR TITLE
Add new kubeflow page

### LINKED ISSUE #2226: UX the copy doc for /kubernetes/managed page

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Add "What is Kubeflow?" page

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/kubeflow/what-is-kubeflow
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Check that the page matches [the copy doc](https://docs.google.com/document/d/1m-96RlGkbzFa1KaGAxYFpY0ztIlsTuViCjXSAlErQlg/edit?pli=1#heading=h.tjha1bhkvpeu)

## Issue / Card

Fixes #2226

### CODE REVIEW

**Comment by anasereijo** [comment]
- [ ] make the diagram 800px wide

- [ ] make 'Ask the experts' a positive button

- [ ] 'Companies involved in Kubeflow' section: remove the light grey background from the logo sections to make these 2 sections look as part of 1
Screenshot 2020-01-23 at 16 04 39

- [ ] 'What makes up Kubeflow?' should be light grey and part of the section below it

- [ ] make 'Who uses Kubeflow?' a `h2` and move the paragraph just next to it. Is there a way to move the logos to the right side (next to the paragraph)?

- [ ] 'How to install Kubeflow' should be light grey

**Comment by steverydz** [comment]
@anasereijo I've addressed all of the above

**Comment by anasereijo** [comment]
nice 👍

**Comment by anasereijo** [comment]
@SirSamTumless this is ready. We have a Marketing label: do you want to send this to anyone in particular or can he push this live?

**Comment by caldav** [comment]
Could we move it in the nav to be after the overview? It worked well for OpenStack.

**Comment by steverydz** [comment]
> Could we move it in the nav to be after the overview? It worked well for OpenStack.

@caldav Sure, done :)

**Comment by anasereijo** [comment]
@caldav do you mind reviewing this? (marketing needed label) merci!

**Comment by pmahnke** [comment]
Let's assume @caldav forgot to change the label... merging.

**Comment by caldav** [comment]
Sorry @anasereijo, I missed your message! The meta description is so-so, I'll propose an update this week, other than that, looking good.

**Pull request merged**
