### PR TITLE
Change the IoT illustration

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Update the IoT hero illustration

## QA
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/internet-of-things
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Check the illustration matches the one from [the design](https://github.com/canonical-web-and-design/web-squad/issues/1459)

## Issue / Card

Fixes #

## Screenshots

[if relevant, include a screenshot]

### CODE REVIEW

**Comment by deadlight** [comment]
The image looks off:
image
It looks like the circle of friends should be in the centre and the lines shouldn't have a gap.

**Comment by deadlight** [comment]
There's also a weird artefact where some of the lines on the right of the image overlap and look too white.

**Comment by anasereijo** [comment]
Karl is right the illustration looks odd. replace with [this one ](https://assets.ubuntu.com/v1/27b51b01-IOT_Ubuntu_devices_inforgrapic.svg) and make it 488px wide. thanks

**Comment by anthonydillon** [comment]
Thanks, updated.

**Comment by anasereijo** [comment]
nice! please push it live asap, thanks

**Pull request merged**
