### PR TITLE
Update /openstack/install with updated instructions

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

- Update /openstack/install with updated instructions
- Thanks to @bovi and #8271

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/openstack/install
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc/edit)

## Issue / Card

Fixes #8271

### CODE REVIEW

**Review by bethcollins92 — COMMENTED** [review]
Not sure if this is a problem but the wording is slightly different to the brief? Other than this looks good.

The brief: 

image

The demo: 

image

**Comment by pmahnke** [comment]
@bethcollins92 good catch, I updated the copy doc.  It read funny as it was.

**Comment by bethcollins92** [comment]
@pmahnke I agree! Further down on the next set of instructions doesn't say "you can" (line 357). Not sure if you'd want to change that also for consistency?

**Comment by pmahnke** [comment]
@bethcollins92 good catch.  Updated

**Review by bethcollins92 — APPROVED** [review]

**Pull request merged**
