### PR TITLE
Update download server power page

### LINKED ISSUE #6624: [ILLUSTRATIONS UPDATE] /download/server/power
few small updates:

Ubuntu for POWER   Download   Ubuntu (1)

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Add suru to /download/server/power hero

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/download/server/power
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Check that the hero has suru

## Issue / Card

Fixes #6624

### CODE REVIEW

**Comment by anthonydillon** [comment]
Looks like it doesn't match the design in the issue. The paragraph should be with the heading and the second strip should be a light one.

**Comment by steverydz** [comment]
@anthonydillon thanks - fixed

**Comment by anasereijo** [comment]
@steverydz looks good! the only thing left to do is to remove the `--highlighted` from the cards

**Comment by steverydz** [comment]
@anasereijo done

**Pull request merged**
