### PR TITLE
Update tables to use vanilla-3.0 patterns

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

- Mostly changing aria-labels to data-headings, Please give them a read to check they make sense and make any changes you think
 appropriate.

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/4856

### CODE REVIEW

**Review by sowasred2012 — CHANGES_REQUESTED** [review]
I think there's been a fundamental misunderstanding here, this PR changes `aria-label` to `data-heading` on `table.p-table--mobile-card`, but the upgrade guide reads:

> The `aria-label` attribute on table cells of the responsive table has been replaced by `data-heading`. This is to ensure information in the cells of the table isn't missed by screen readers. Please replace all `aria-label`'s on `<td>` elements in tables using the `p-table--mobile-card` class.

The [example markup for the mobile card](https://vanillaframework.io/docs/examples/patterns/tables/table-mobile-card) shows more explicitly that `table` elements should retain the `aria-label` attribute, and that table _cells_ are what need to be updated.

**Comment by petesfrench** [comment]
@sowasred2012 I see the mistake I made, I have made the corrections and it should all be right now

**Review by minkyngkm — APPROVED** [review]
@petesfrench LGTM! 👍

**Comment by minkyngkm** [comment]
@petesfrench just wondering if we need to remove `.p-table-expanding__panel` from the `styles.scss` file as we are not using that class any more. 
image

**Pull request merged**
