### PR TITLE
Copy update on /managed

### LINKED ISSUE #10169: [COPY UPDATE] index - "Canonical's Managed Apps"
https://docs.google.com/document/d/1fLRWW-Gtslaia2ypSrLJVBxZVHo5FY5Q84o97Gs2-w4/edit

### PR DESCRIPTION
**Pull request by minkyngkm**
## Done

- Copy update on /managed

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Please check page against [copy doc](https://docs.google.com/document/d/1fLRWW-Gtslaia2ypSrLJVBxZVHo5FY5Q84o97Gs2-w4/edit) and resolve comments

## Issue / Card

Fixes #10169 

## Screenshots

image

### CODE REVIEW

**Comment by anthonydillon** [comment]
@minkyngkm could you confirm we want to replace the mongoDB item instead of adding a new cell for MariaDB.

**Review by anthonydillon — CHANGES_REQUESTED** [review]
LGTM but just need to confirm we want to replace mongoDB.

**Comment by minkyngkm** [comment]
> LGTM but just need to confirm we want to replace mongoDB.

I had to add a new cell for MariaDB instead of replacing the mongoDB cell. Thanks for reviewing @anthonydillon !

**Review by anthonydillon — APPROVED** [review]
LGTM

**Pull request merged**
