### PR TITLE
Switch Django to Flask

### PR DESCRIPTION
**Pull request by nottrobin**
All the content has been reviewed going in, but this is so we can thoroughly QA it.

Fixes https://github.com/canonical-web-and-design/base-squad/issues/686

QA
--

Go through the whole site, check it against live. Especially check the complex bits - /download, /search, /blog, /kubernetes/docs, /legal

**NB: Feel free to QA using the demo link, but note that `/search` won't work on the demo. You'll see a 500 error, which is expected.**

*QAing locally:*

Grab the custom search creds from https://console.cloud.google.com/apis/credentials?project=ubuntu-search-1530889417216

`./run --env SEARCH_API_KEY={credential}`

### CODE REVIEW

**Comment by nottrobin** [comment]
@deadlight and @anthonydillon declare this branch perfect! But let's wait until Monday to merge.

**Comment by anthonydillon** [comment]
Great ok QA :+1:

**Comment by anthonydillon** [comment]
After further testing I have hit an issue:
https://ubuntu-com-canonical-web-and-design-pr-5733.run.demo.haus/blog/cloud-and-server&page=2

**Comment by nottrobin** [comment]
@anthonydillon fixed

**Pull request merged**
