### PR TITLE
Add bottomed suru strip to IoT robotics page

### PR DESCRIPTION
**Pull request by MeltySnow**
## Done

Added bottomed suru strip and image to IoT robotics page.

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/internet-of-things/robotics
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Ensure that the design matches the [specification](https://github.com/canonical-web-and-design/web-squad/issues/1461)

## Issue / Card

Fixes canonical-web-and-design/web-squad#1461

## Screenshots
image

### CODE REVIEW

**Comment by anasereijo** [comment]
@MeltySnow looks great!! 🥇 👍 

just 2 tiny things: 

- [ ] make the text 7 cols and the illustration 5 cols

- [ ] hide the illustration on mobile

**Comment by MeltySnow** [comment]
@anasereijo I've pushed a change that should hopefully address those points.

**Comment by anasereijo** [comment]
@MeltySnow nice! thank you

as we are updating this page could you please remove the robot further down the page?

_how it looks like_
Screenshot 2019-07-26 at 09 44 46

_how it should look like_
Screenshot 2019-07-26 at 09 44 52

**Comment by MeltySnow** [comment]
@anasereijo Done!

**Comment by anasereijo** [comment]
@MeltySnow awesome! thanks

**Pull request merged**
