### PR TITLE
Increase the timeout when linkchecking

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
- Increase the timeout when linkchecking to avoid discourse timeouts

## QA
- Check the code changes look good.
- Run the command locally

### CODE REVIEW

**Comment by bethcollins92** [comment]
What command should I run locally? Do I need to do for each file e.g. `linkchecker --no-follow-url '!https:\/\/ubuntu.com\/ceph\/docs'` ?

**Comment by anthonydillon** [comment]
Sorry, should have explained in QA. Just take one of the commands and run it like it is. You will need to [linkchecker locally](https://github.com/linkchecker/linkchecker). 

If the command works then just check the syntax of the change is the same for all commands.

If you have any trouble we can jump on a call.

**Comment by bethcollins92** [comment]
When I try and run a couple of the commands locally I get an error:  `no matches found: w_[0-9]*`, am I missing something?

**Review by bethcollins92 — APPROVED** [review]
LGTM 👍🏼  - should it have some points / an issue?

**Pull request merged**
