### PR TITLE
Account users/Add labels to mobile table view

### PR DESCRIPTION
**Pull request by petermakowski**
## Done

- add labels to mobile table view
  - create `UsersTableHeader` and `UserCell` with typed `label` prop to make sure they use the same labels

## QA

- go to https://ubuntu-com-10445.demos.haus/advantage/users?test_backend=true and login
- make sure that labels are visible on mobile breakpoint

## Issue / Card

https://github.com/canonical-web-and-design/commercial-squad/issues/282

### Before
image

### After
image

### CODE REVIEW

**Review by carkod — APPROVED** [review]
LGTM

**Comment by carkod** [comment]
@cristinadresch @SirSamTumless this needs designer review, who is available for commercial squad?

**Comment by cristinadresch** [comment]
> @cristinadresch @SirSamTumless this needs designer review, who is available for commercial squad?

@anasereijo are you free for a quick review please?

**Comment by anasereijo** [comment]
@petermakowski this is looking good, thanks! 👍🏻

**Pull request merged**
