### PR TITLE
Refactor release cycle page into tabbed content

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

- Refactored /about/release-cycle content into tabs, according to the [copy doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit)

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: https://ubuntu-com-11162.demos.haus/about/release-cycle
    - Be sure to test on mobile, tablet and desktop screen sizes
- See that the content of the page is now in tabs, and that the tabs work as expected
- Visit:
  - https://ubuntu-com-11162.demos.haus/about/release-cycle#ubuntu
  - https://ubuntu-com-11162.demos.haus/about/release-cycle#ubuntu-kernel-release-cycle
  - https://ubuntu-com-11162.demos.haus/about/release-cycle#openstack-release-cycle
  - https://ubuntu-com-11162.demos.haus/about/release-cycle#kubernetes-release-cycle
- See that the correct tabs are displayed

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/4746

### CODE REVIEW

**Comment by sowasred2012** [comment]
@spencerbygraves could you take a look at this please? I'm still working on some functionality, but would be good to get design feedback in the meantime.

**Comment by spencerbygraves** [comment]
@sowasred2012 I think the first tab could do with some separation in the content, can we please try the "Maintenance and security updates" section in a grey strip as on the [current page](https://ubuntu.com/about/release-cycle)?

Thanks.

**Comment by sowasred2012** [comment]
@spencerbygraves could you take another look at this one please?

**Review by steverydz — APPROVED** [review]
LGTM 👍

**Comment by nmav** [comment]
Great work!

**Comment by nmav** [comment]
One comment the top paragraph doesn't seem to include Kubernetes and openstack as in the copydoc

**Comment by sowasred2012** [comment]
@nmav ah yes - updated!

**Pull request merged**
