### PR TITLE
Add Canonical and Dell AI webinar page

### PR DESCRIPTION
**Pull request by jpmartinspt**
## Done
Add Canonical and Dell AI webinar page

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/workstations-journey-to-ai
- Check the [copy](https://docs.google.com/document/d/1qFj7Q1lAQpVCKOFjlJz0S6VKy9ElJ-sy2aS3xPF_e04/edit#)

## Issue / Card

Fixes #https://github.com/canonical-web-and-design/web-squad/issues/4067

### CODE REVIEW

**Comment by anasereijo** [comment]
Screenshot 2021-04-27 at 10 43 34
Screenshot 2021-04-27 at 10 45 29

**Comment by jpmartinspt** [comment]
@anasereijo updated.

**Comment by anasereijo** [comment]
@jpmartinspt you forgot to change the "Explore the best open source platforms and tools that help to work on large and varying datasets" to `<h4>`. Giving you a +1 anyway as it's not a blocker

**Comment by jpmartinspt** [comment]
@anasereijo I changed it, hard refresh page might be cached.

**Comment by bethcollins92** [comment]
@jpmartinspt I've left a comment in the copy doc as all 4 of the register links are pointing to the same place - the Part 1 data pipelines webinar and I'm not sure this is intentional. Everything else LGTM - I'll give it a +1 once she gets back to us

**Comment by jpmartinspt** [comment]
@bethcollins92 since there was no reply on the copy just yet, I replaced the links with with disabled buttons, in case we want to get this out before we have links.

**Comment by SirSamTumless** [comment]
@lindseylopez Please can you provide the links ASAP?

**Review by SirSamTumless — APPROVED** [review]

**Comment by SirSamTumless** [comment]
LGTM!

**Comment by lindseylopez** [comment]
Hi Sam, this is @Katie Brim (Elston) ***@***.***> request.
So looping her in here.

**Pull request merged**
