### PR TITLE
update /public-cloud based on copy doc changes

### LINKED ISSUE #6215: [COPY UPDATE] index - "Public cloud"
**Please note; this should go live on the Weds 4/12**

Please update index - "Public cloud" from the [copy doc](https://docs.google.com/document/d/1ZzUIh9Tfz5SvkrHyo4-izzmUjRka1Tn0UQisKcXGEPA/edit?usp=drivesdk)

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

- Updated /public-cloud based on the [copy doc](https://docs.google.com/document/d/1ZzUIh9Tfz5SvkrHyo4-izzmUjRka1Tn0UQisKcXGEPA/edit#heading=h.gec9pmwcxl6m)

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/public-cloud
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Check that the page matches the copy doc, and the page looks good.

## Issue / Card

Fixes #6215

### CODE REVIEW

**Comment by anasereijo** [comment]
hero:

- [ ] make it `p-strip--suru-topped`

logo cloud:

- [ ] make it light grey background (and then reverse the colours on the rest of the page)

Ubuntu Server on public cloud vs Ubuntu Pro on public cloud

- [ ] can we make this into 2 cards next to each other to compare?

Ready to get started?:

- [ ] put aws logo on the right side https://assets.ubuntu.com/v1/a82add58-profile-aws.svg

**Comment by anasereijo** [comment]
@sowasred2012 few changes

Ubuntu on Public Clouds   Ubuntu

**Comment by hatched** [comment]
A couple small improvements please :-)

Screen Shot 2019-12-04 at 10 01 26 AM

**Comment by sowasred2012** [comment]
@hatched just updated - what do you think?

**Comment by hatched** [comment]
Thanks @sowasred2012 looks good - any chance we could get a highdpi version of that dashboard photo?

**Pull request merged**
