### PR TITLE
Prepare buttons on cube microcerts now link the the courseware

### LINKED ISSUE #9953: Deep links for Study Labs content and changing the URL for the Study labs
We would like this change to go live on July 1. This change should only apply to the Study Lab("Prepare") buttons/links, the Exam("Take" button) URLs are *not* changing.

Please change the "Prepare" buttons next to each Microcertifcation to the links below which match the Exam to the topic the "Prepare" button leads the user to. Additionally, we would like the "Prepare" button at the top under "Refresh your knowledge" to be removed.

The general form of the links is "https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2F" + "exam_shortname" + "%2F%3Fchild%3Dfirst"

The specific links and the exam shortname they match are below.

admintasks    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fadmintasks%2F%3Fchild%3Dfirst
commands    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fcommands%2F%3Fchild%3Dfirst
devices    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fdevices%2F%3Fchild%3Dfirst
juju    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fjuju%2F%3Fchild%3Dfirst
kernel    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fkernel%2F%3Fchild%3Dfirst
maas    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fmaas%2F%3Fchild%3Dfirst
microk8s    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fmicrok8s%2F%3Fchild%3Dfirst
networking    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fnetworking%2F%3Fchild%3Dfirst
package    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fpackage%2F%3Fchild%3Dfirst
security    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fsecurity%2F%3Fchild%3Dfirst
shellscript    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fshellscript%2F%3Fchild%3Dfirst
storage    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fstorage%2F%3Fchild%3Dfirst
sysarch    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fsysarch%2F%3Fchild%3Dfirst
systemd    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fsystemd%2F%3Fchild%3Dfirst
virtualisation    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fvirtualisation%2F%3Fchild%3Dfirst

The generic link to the Study Lab course should be:
https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourse%2F

I believe this is used on the /cube/study page.

---
*Reported from: https://ubuntu.com/cube/microcerts*

### PR DESCRIPTION
**Pull request by jpmartinspt**
## Done
Prepare buttons on cube microcerts now link the the courseware

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Check the prepare buttons link to the appropriate sections of the study labs course(see #9953)

## Issue / Card

Fixes #9953

### CODE REVIEW

**Comment by jpmartinspt** [comment]
@KellenRenshaw you can QA the deep links work in this demo once possible.

**Comment by SirSamTumless** [comment]
@KellenRenshaw any update on this?

**Comment by KellenRenshaw** [comment]
@jpmartinspt Tested on the demo platform. The links work as expected. Many thanks!

**Comment by jpmartinspt** [comment]
@SirSamTumless @carkod I don't want to approve my own PR, but this is good to go. Feel free to approve and merge after standup.

**Review by SirSamTumless — APPROVED** [review]

**Pull request merged**
