### PR TITLE
Add meta image to the homepage

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Add meta image to the homepage

## QA
- Go to https://www.opengraph.xyz/url/https:%2F%2Fubuntu-com-9890.demos.haus%2F/
- Check it looks better then https://www.opengraph.xyz/url/https:%2F%2Fubuntu.com/

## Issue / Card
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9864

### CODE REVIEW

**Review by carkod — APPROVED** [review]
LGTM. Also QAed [FB debugger](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fubuntu-com-9890.demos.haus)

**Comment by anasereijo** [comment]
@anthonydillon looks good [here](https://www.opengraph.xyz/url/https:%2F%2Fubuntu-com-9890.demos.haus%2F/)  but the [here](https://www.opengraph.xyz/url/https:%2F%2Fubuntu.com/) looks like this:
Screenshot 2021-06-14 at 11 55 49

**Comment by anthonydillon** [comment]
Yes, that is the fix. The QA steps are to check the first link is better then the second (live now)

**Comment by anasereijo** [comment]
lgtm then

**Pull request merged**
