### PR TITLE
Update customerInfo object before API call

### LINKED ISSUE #9194: Cannot change address in the shop
Once an address is set in a first purchase, I cannot change it in a subsequent purchase. All requests made to the backend contain the original address that was set during the first purchase. The request that gets sent to ua-contracts only contains the first, unmodified address.

Steps to reproduce:
- Make a purchase
- Make another purchase and try to replace the address somehow
- Watch the request logs

### PR DESCRIPTION
**Pull request by ClementChaumel**
## Done

- Fixed a bug where the backend would be called with an outdated address

## QA

- https://ubuntu-com-9222.demos.haus/advantage/subscribe?test_backend=true
- log in
- Make a purchase
- Make another purchase and try to replace the address somehow
- Watch the request logs

## Issue / Card

Fixes #9194

### CODE REVIEW

**Comment by alnvdl** [comment]
I tested this here, and the address change is working now, thanks!
It'd be nice to have tests for this modal/form to avoid regressions like these.

**Review by alnvdl — APPROVED** [review]
I tested this here, and the address change is working now, thanks!
It'd be nice to have tests for this modal/form to avoid regressions like these.

**Review by anthonydillon — APPROVED** [review]
LGTM :+1:

**Comment by anthonydillon** [comment]
@ClementChaumel I agree could you add a test for this?

**Pull request merged**
