### PR TITLE
Build Raspberry Pi page

### LINKED ISSUE #8472: [20.10 raspberry pi] - build the /raspberry-pi page
[brief](https://docs.google.com/document/d/1v5XWz2Pwi1u_8nj0BUJg-6NKKBXEj6U70uzJlboUEJQ/edit?ts=5f86ec35#)
[copy doc](https://docs.google.com/document/d/1XS8KyKQnQdgY9NJfxHMs_9ql4sPOTRj0yweunMPoOdM/edit#)

### PR DESCRIPTION
**Pull request by bethcollins92**
## Done

- Build `/raspberry-pi` page

**Known difference**:
- Waiting on link for "Follow the tutorial"

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/raspberry-pi
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Check page against [copy doc](https://docs.google.com/document/d/1XS8KyKQnQdgY9NJfxHMs_9ql4sPOTRj0yweunMPoOdM/edit#heading=h.alvyav8qzr5r)

## Issue / Card

Fixes #8472

### CODE REVIEW

**Comment by meralonso** [comment]
@bethcollins92 [this image ](https://assets.ubuntu.com/v1/ac0294f7-Ubuntu-Screens-for-Raspberry-Pi.png) is missing from the second section but overall looks good

**Comment by meralonso** [comment]
This section has disappeared @bethcollins92 has it been a request from MK?

Screenshot 2020-10-21 at 16 58 16

**Comment by bethcollins92** [comment]
@meralonso Yes, it was requested in the copy doc to remove it

**Review by albertkol — APPROVED** [review]
:+1:

**Pull request merged**
