### PR TITLE
update ebook layouts

### LINKED ISSUE #6676: /download/server/provisioning - Update eBook section
Last year we A/B tested the old aubergine design vs a new light grey design. The winning version was the [light grey strip](https://github.com/canonical-web-and-design/ubuntu.com/blob/d45b26330b0cad70cc8e943bd92cddbc7e73c530/templates/download/shared/_get_ebook_v3.html). 

Please update the ebook section with the new design. Any questions please let me know or ask @caldav regarding content and links.

_should be something like this:_
Screenshot 2020-02-17 at 10 47 06

---
*Reported from: https://ubuntu.com/download/server/provisioning*

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

Updated the layout of two ebook strip partials

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/download/server/provisioning
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- See that the layout looks OK and complies with the [brief](https://github.com/canonical-web-and-design/ubuntu.com/issues/6676)
- Visit /download/intel-iei-tank-870
- See that the layout looks OK and complies with the [brief](https://github.com/canonical-web-and-design/ubuntu.com/issues/6676)

## Issue / Card

Fixes #6676 

## Screenshots
Before:
FireShot Capture 026 - Get MAAS to run your physical cloud - Download - Ubuntu - Ubuntu - localhost

FireShot Capture 027 - Install Ubuntu Core on an Intel IEI TANK 870 - Ubuntu - localhost

After:
FireShot Capture 024 - Install Ubuntu Core on an Intel IEI TANK 870 - Ubuntu - localhost

FireShot Capture 025 - Get MAAS to run your physical cloud - Download - Ubuntu - Ubuntu - localhost

### CODE REVIEW

**Comment by anasereijo** [comment]
few changes:

- [ ] the strip doesn't need to be `is-deep`

- [ ][ in my design](https://ubuntu.com/download/server/thank-you?country=GB&version=18.04.4&architecture=amd64) (and I believe that is also in the code example I provided you) there is 1 col empty between the ebook and the form

- [ ] "Server provisioning: what Network Admins and IT pros need to know" - make it `h4`

**Comment by anasereijo** [comment]
awesome! thanks

**Comment by anasereijo** [comment]
I'm really sorry! It's great but then I realised that in the [example](https://ubuntu.com/download/server/thank-you?country=GB&version=18.04.4&architecture=amd64) the left col is 7 and the form is 4. Can you just do the same and then it's perfect?

**Comment by sowasred2012** [comment]
@anasereijo this is ready to review again, it includes the second ebook section 😄

**Comment by anasereijo** [comment]
Thanks @sowasred2012 looks great!

**Pull request merged**
