### PR TITLE
Build kernel index page

### LINKED ISSUE #5683: [Kernel] Build ubuntu.com/kernel
Build the five pages that were sketched in [Ubuntu-design#120](https://github.com/CanonicalLtd/Ubuntu-design/issues/120) and [Ubuntu-design#121](https://github.com/CanonicalLtd/Ubuntu-design/issues/121):

URL|Title + copydoc
-|-
ubuntu.com/kernel|[Ubuntu kernels from Canonical](https://docs.google.com/document/d/1XLdk2Slh4vi4AjGnatcK1BmJGmMNKIjN27KwbTwG5iI/edit)

I’ve proposed fixes for the worst, but not all, of the language issues in the source documents. Ideally each copydoc would be reviewed by someone doing pair-editing with a kernel engineer for accuracy.

This issue might need converting to an epic for building each page separately. If so, take care that the “Kernel” navigation ribbon is coherent at each step.

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Add /kernel index page

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/kernel
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- See that the page matches the [copy doc](https://docs.google.com/document/d/1XLdk2Slh4vi4AjGnatcK1BmJGmMNKIjN27KwbTwG5iI/edit)

**Note:** 
- The meta description is missing from the copy doc
- There is a link to a whitepaper in the copy doc which doesn't exist so isn't in this page for now
- There are links to other /kernel pages which don't exist yet so aren't in this page for now

## Issue / Card

Fixes #5683

### CODE REVIEW

**Comment by steverydz** [comment]
@anasereijo I've updated to make it look a bit nicer (I hope). Could do with some design advice for the "Identifying a kernel" section though.

@pmahnke @SirSamTumless I've removed any links to whitepapers or other /kernel pages. Do you think this will be OK?

https://ubuntu-com-canonical-web-and-design-pr-6534.run.demo.haus/kernel

**Comment by anasereijo** [comment]
### Hero section:

- [ ] use suru: `p-strip--suru`

- [ ] use this illustration: https://assets.ubuntu.com/v1/3b5dc41b-Kernel_white.svg","white: https://assets.ubuntu.com/v1/3b5dc41b-Kernel_white.svg

- [ ] I think the hero looks quite copy heavy. Can we move the 2nd paragraph (about the team and process) to another section and give it a title? @matthewpaulthomas 

### Identifying a kernel section:

- [ ] on @matthewpaulthomas's [wireframe](https://docs.google.com/document/d/1K1zryld1ytWcrfocnEXTn_GoJNvVdOkkbnwI2A9VffI/edit#) this section is called 'Kernerl naming and versioning'

- [ ] I think the code block looks weird being full width. Can we make it the same width as the text?

- [ ] do we have to repeat the number of parameter? see below:
Screenshot 2020-02-03 at 15 25 02

- [ ] Can we move the _"1 Canonical adds..."_ below the stepped list?

### Kernel security - I don't see this section in the wireframe? (maybe i'm blind)

**Comment by steverydz** [comment]
>  on @matthewpaulthomas's wireframe this section is called 'Kernerl naming and versioning'

Surely the copy doc takes precedence here?

> do we have to repeat the number of parameter? see below:

I agree it's a bit redundant but removing the number from the text would just say `Parameter` for every item - or we'd need to use a different pattern instead of the stepped list?

> Kernel security - I don't see this section in the wireframe? (maybe i'm blind)

All the copy on this page was taken from the [copy doc](https://docs.google.com/document/d/1XLdk2Slh4vi4AjGnatcK1BmJGmMNKIjN27KwbTwG5iI/edit#heading=h.fvbs0r9oprp6) - surely that's the most up-to-date content rather than the wireframe?

**Comment by anasereijo** [comment]
> > on @matthewpaulthomas's wireframe this section is called 'Kernerl naming and versioning'
> Surely the copy doc takes precedence here?

Sorry about that. Yes just follow the copydoc

> 
> > do we have to repeat the number of parameter? see below:
> 
> I agree it's a bit redundant but removing the number from the text would just say `Parameter` for every item - or we'd need to use a different pattern instead of the stepped list?

Just checked the copydoc and Matthew suggested something else


> > Kernel security - I don't see this section in the wireframe? (maybe i'm blind)
> 
> All the copy on this page was taken from the [copy doc](https://docs.google.com/document/d/1XLdk2Slh4vi4AjGnatcK1BmJGmMNKIjN27KwbTwG5iI/edit#heading=h.fvbs0r9oprp6) - surely that's the most up-to-date content rather than the wireframe?
You are right, sorry!

**Comment by pmahnke** [comment]
@steverydz can you take one more pass, I cleaned up the copy doc.

The parameter section is much simplier now.

I also broke the top text into a new strip ... the new 'The Ubuntu Kernel Team' section could be white and get ride of the suru to light strip thing.

**Comment by steverydz** [comment]
Thanks @pmahnke. I've updated to the latest copy doc.

**Comment by steverydz** [comment]
@pmahnke @anasereijo this is ready for review

**Comment by anasereijo** [comment]
thanks @steverydz looks good

**Comment by matthewpaulthomas** [comment]
>  I think the hero looks quite copy heavy. Can we move the 2nd paragraph (about the team and process) to another section and give it a title? @matthewpaulthomas

Sorry I didn’t see this until today. I think the solution to this would have been for the page not to have a “hero” at all.  It’s a technical document, not a brochure page.

**Pull request merged**
