### PR TITLE
Update feature coverage copy

### PR DESCRIPTION
**Pull request by ClementChaumel**
## Done

- Update feature coverage section (ESM Apps) copy to the [copydoc](https://docs.google.com/document/d/1UqL8YJH9ywvOXnrt3syY0U8fiOakfAGWmLS9uerwAWk/edit?ts=6076a9df#) 

## QA

- go here https://ubuntu-com-9572.demos.haus/advantage/subscribe?test_backend=true&esm_apps=true

## Issue / Card

Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9486
and https://github.com/canonical-web-and-design/web-squad/issues/4029

## Screenshots

image

### CODE REVIEW

**Comment by ClementChaumel** [comment]
After discussing with Ana we agreed that the list within a list looked a bit weird.
Here are some alternative proposals, please let us know what you think @elioqoshi @wgx @lechsandecki 
Current:

1:
image

2:
image

3:
image

**Comment by lechsandecki** [comment]
good catch! I like option 3 with bold text

**Comment by elioqoshi** [comment]
@ClementChaumel are you considering a career in UX?

I agree, Option 3 seems the best balanced one.

**Comment by anasereijo** [comment]
@ClementChaumel let me know when demo is updated and I'll +1 it

**Comment by anasereijo** [comment]
🥇 🥇 LGTM

**Review by albertkol — APPROVED** [review]
:+1:

**Pull request merged**
