### PR TITLE
New page /robotics/esm

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

- New page /robotics/esm

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/robotics/esm
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Compare to the [copy doc](https://docs.google.com/document/d/1oiz_006n9U1Ya50wdSkKIyj_jsxSr92FdCpkDU4kpHs/edit?ts=606301c9#)

## Issue / Card

Fixes [#4001](https://github.com/canonical-web-and-design/web-squad/issues/4001)

### CODE REVIEW

**Comment by anasereijo** [comment]
- [ ] typo in 'PARTNERSHI~~O~~P'
- [ ] 'DELIVERED IN PARTNERSHIP WITH' section: I think this is taking too much space for just 1 logo. I suggest the following:
Screenshot 2021-04-22 at 14 48 22

[openrobotics logo](https://assets.ubuntu.com/v1/3e9ad582-openrobotics-logo-stacked.png) width:250px

- [ ] 'Benefits of ROS ESM' section. Can you do the following? (similar to [Financial services page](https://ubuntu.com/financial-services))
ROS Extended Sec


- [ ] learn more section:

Screenshot 2021-04-22 at 15 01 39

**Comment by anasereijo** [comment]
Thanks for making these changes, @pmahnke 

You forgot to take the bullets from the learn more list, but that is not a blocker - giving you a +1

Screenshot 2021-04-23 at 15 46 05

**Review by ClementChaumel — APPROVED** [review]
:+1:

**Comment by pmahnke** [comment]
@anasereijo I missed that... removed

image

**Pull request merged**
