### PR TITLE
Add contract details to the expanding name

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
- Added expandable information to the contract name
- Display the account name as a table header.

## QA
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/advantage
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- It's unlikely you have enterprise contracts to test
- Check the code and screenshot is ok

## Issue / Card
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/6155

## Screenshots
Screenshot_2019-12-06 Ubuntu Advantage for Infrastructure Ubuntu

### CODE REVIEW

**Comment by matthewpaulthomas** [comment]
The text looks good. Unfortunately the alignment has gone wonky:

6240-advantage-subscription-details highlighted

- Subscription name should be left-aligned with the account name above
- Baselines of all the cells should be the same
- The details should be in a key-value table with keys right-aligned, similar to the ESM instructions

**Comment by anthonydillon** [comment]
@matthewpaulthomas Do you want it like this?
image

**Comment by anthonydillon** [comment]
@matthewpaulthomas @steverydz ready for another review if you could please

**Comment by matthewpaulthomas** [comment]
@anthonydillon No, don’t change the font — just right-align the labels, left-align the data. That will make it easier to see, at a glance, whether the dates are the same or what their difference is. (As I mentioned above, it will also be consistent with the ESM instructions.)

**Comment by anthonydillon** [comment]
Updated: 
image

**Comment by matthewpaulthomas** [comment]
Please right-align the labels. Thanks.

**Comment by anthonydillon** [comment]
@matthewpaulthomas Thing its there now:
image

**Comment by matthewpaulthomas** [comment]
ಠ_ಠ

6240-advantage-subscription-details-again

**Comment by anthonydillon** [comment]
@matthewpaulthomas What you think? 
image

**Pull request merged**
