### PR TITLE
Build tutorial template

### LINKED ISSUE #6206: [Tutorials] Apply homepage design

### LINKED ISSUE #6207: [Tutorials] Apply tutorial design

### LINKED ISSUE #6210: [Tutorials] Create basic tutorial section

### LINKED ISSUE #6342: Build pagination for tutorials homepage
This will be done once https://github.com/canonical-web-and-design/ubuntu.com/issues/6286 is complete

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Built tutorial page template and tutorial homepage template

### Tutorials homepage
- Go to https://ubuntu-com-canonical-web-and-design-pr-6284.run.demo.haus/tutorials
- Check that it matches [the design](https://app.zeplin.io/project/5df26dadead180a5c29b569d/screen/5dfa10d6d30a77171fd01cbe) (**note**: search and filters has not been built yet)

### Tutorial page
- Go to https://ubuntu-com-canonical-web-and-design-pr-6284.run.demo.haus/tutorials/tutorial-install-ubuntu-desktop
- Check that it matches [the design](https://app.zeplin.io/project/5df26dadead180a5c29b569d/screen/5df26deeecb6bcafd2a5d3ee)

## Issue / Card
- Fixes #6206
- Fixes #6207 
- Fixes #6210
- Fixes #6342

### CODE REVIEW

**Comment by steverydz** [comment]
@anasereijo could you give this an informal design review? https://ubuntu-com-canonical-web-and-design-pr-6284.run.demo.haus/tutorials/tutorial#overview

Note that I've only put the first three sections in so section four onwards is just blank pages, but there should be enough there.

**Comment by anasereijo** [comment]
nice work @steverydz 👍 just tiny things

- [ ] sidebar nav: the font on the active state should be regular as per my design (not the number though)

- [ ] below the image there is a link: _40f91c0b-bionic-desktop.png1022x767 193 KB_ I don't that should be there

- [ ] footer: please use a shorter version of the footer as per design

**Comment by anasereijo** [comment]
@steverydz on mobile can you make the sidebar nav as what we have on [MAAS docs](https://maas.io/docs)?

**Comment by steverydz** [comment]
@anasereijo The following has been done and demo is updated:

- [x] sidebar nav: the font on the active state should be regular as per my design (not the number though)
- [x] below the image there is a link: _40f91c0b-bionic-desktop.png1022x767 193 KB_ I don't think that should be there **(this is a html dump so we don't have control over the content - @tbille is working on a parser that should prevent this kind of thing)**
- [x] footer: please use a shorter version of the footer as per design
- [x] sidebar acts as maas.io/docs on mobile view

**Comment by anasereijo** [comment]
@steverydz looking good, thanks for doing all changes so quickly.

On the mobile view can you please:

- [ ] add a hr to separate the dropdown from the rest of the page?

- [ ] align the following

Screenshot 2019-12-17 at 11 35 29

**Comment by anasereijo** [comment]
### Tutorials Landing page:

- [ ] hero section: can you make the intro copy an `p` instead of `h4`? same for the link

- [ ] cards: make sure you are using the same colours as per my design (greys and aubergine too)

- [ ] cards: is the spacing a vanilla pattern? in my version the content looks tidier wasting much less space.

- [ ] sticky search bar: please check my design for when it becomes sticky. I reduced the top and bottom paddings

- [ ] pagination is starting at page 2

- [ ] @matthewpaulthomas do you think we should have pagination or infinite scroll? If we have the sticky search bar I think I prefere having infinite scroll, but I would like to know your opinion

**Comment by anasereijo** [comment]
@steverydz 

- [ ] annoying request: how easy is changing the hero text from `col-7` to `col-6`? Not sure how quickly it is as this is like a templated suru?

- [ ] cards: category can you make the text `#111111`

**Comment by steverydz** [comment]
@anasereijo I've done it all but the sticky header height which I'm working on now

**Comment by steverydz** [comment]
@anasereijo @tbille @anthonydillon This PR is ready to be reviewed and merged into the `tutorials` feature branch on the ubuntu.com repo. It fixes all the initial build issues other than the search and filters.

**Comment by anasereijo** [comment]
## Desktop

### Homepage

- [ ] search is missing

- [ ] tutorial date is missing from the cards

### Tutorial

- [ ] when opening a tutorial from the homepage it doesn't load the tutorial page from the top edge - it hides the nav (see image below)

Screenshot 2020-01-10 at 14 36 14

- [ ] when clicking from part 2 to part 3 it also hides the nav and top part of the page. It works fine from 1 to 2 though...

- [ ] part 2:  "have several tutorials" looks like a link but doesn't take you anywhere

- [ ] part 4 (and others with same content): `p-notification--information` isn't displaying correctly (see below)

Screenshot 2020-01-10 at 14 41 51

how it should look like

Screenshot 2020-01-10 at 14 44 21

- [ ] part 11 (end of tutorial): "Finding help" should be `h4`

- [ ] part 11 (end of tutorial): Ask Ubuntu, Ubuntu Forums, IRC-based support should be external links and not displayed as a `ul` list.
how it should look like:

Screenshot 2020-01-10 at 14 47 24

- [ ] part 11 (end of tutorial): Feedback section is missing

- [ ] footer is not properly aligned with the grid (see below)

Install Ubuntu desktop   Ubuntu

## Mobile

### Tutorial

- [ ] on iPad Pro can the footer be at the bottom of the screen if the content is shorter than the screen size? (see below) nor sure if it will look ok or not but would like to explore (what's your opinion?)

Screenshot 2020-01-10 at 14 52 57

- [ ] iPad (768x1024): can you put the 3 links in the same line (see below)

Screenshot 2020-01-10 at 14 56 01

- [ ] small screens: there is now link to go back to tutorials homepage in the nav. Can you try to add Tutorials in the secondary nav just before the tutorials tile? 
Screenshot 2020-01-10 at 14 59 06

- [ ] iPad (768x1024): when opening a tutorial from the homepage it doesn't load the tutorial page from the top edge - it hides the nav (as per desktop)

**Comment by steverydz** [comment]
@anasereijo 

## Desktop

### Homepage

> search is missing

There's no backend for the search right now so removed it from the UI for the time being.

> tutorial date is missing from the cards

We don't have the tutorial date in the metadata. As we aim to keep the tutorials up to date this shouldn't be required IMO.

### Tutorial

> when opening a tutorial from the homepage it doesn't load the tutorial page from the top edge - it hides the nav

> when clicking from part 2 to part 3 it also hides the nav and top part of the page. It works fine from 1 to 2 though...

I've made an issue for these: https://github.com/canonical-web-and-design/ubuntu.com/issues/6359

> part 2: "have several tutorials" looks like a link but doesn't take you anywhere

> part 4 (and others with same content): `p-notification--information` isn't displaying correctly (see below)

> part 11 (end of tutorial): "Finding help" should be `h4`

> part 11 (end of tutorial): Ask Ubuntu, Ubuntu Forums, IRC-based support should be external links and not displayed as a ul list.

These are all content issues and should be fixed whilst importing the tutorials by editing the content in discourse.

> part 11 (end of tutorial): Feedback section is missing

I've made an issue for this: https://github.com/canonical-web-and-design/ubuntu.com/issues/6360

> footer is not properly aligned with the grid (see below)

Fixed

## Mobile

### Tutorial

> on iPad Pro can the footer be at the bottom of the screen if the content is shorter than the screen size? (see below) nor sure if it will look ok or not but would like to explore (what's your opinion?)

I don't have a strong opinion on this. We don't do this across the site and as the footer is global any change here will have an impact on the rest of the site so will have to be handled carefully. I've made a ticket so we can explore this aside from the tutorials project:

> iPad (768x1024): can you put the 3 links in the same line (see below)

I've made an issue for this as not related to Tutorials: https://github.com/canonical-web-and-design/ubuntu.com/issues/6357

> small screens: there is now link to go back to tutorials homepage in the nav. Can you try to add Tutorials in the secondary nav just before the tutorials tile?

I've made an issue for this: https://github.com/canonical-web-and-design/ubuntu.com/issues/6361

> iPad (768x1024): when opening a tutorial from the homepage it doesn't load the tutorial page from the top edge - it hides the nav (as per desktop)

This will be addressed in the issue that also covers the same issue on desktop (https://github.com/canonical-web-and-design/ubuntu.com/issues/6359)

**Pull request merged**
