### PR TITLE
Update illustrations on kubeflow install page

### LINKED ISSUE #6468: [ILLUSTRATIONS UPDATE] /kubeflow/install
Please update install - "Install Kubeflow on Charmed Kubernetes (CDK)" from the [copy doc](https://docs.google.com/document/d/1KVyyvZsDyrfoi5tK2m5SLWs9YuHg9hgqVz0c8cWHsf8/edit?usp=drivesdk)

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Updated the illustrations on /kubeflow/install

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/kubeflow/install
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Check that the illustrations are the same as in the [copy doc](https://docs.google.com/document/d/1KVyyvZsDyrfoi5tK2m5SLWs9YuHg9hgqVz0c8cWHsf8/edit#heading=h.pt6iw0mepowo)

## Issue / Card

Fixes #6468

### CODE REVIEW

**Comment by anasereijo** [comment]
- [ ] I have one illustration to add the hero section of this page (check copy doc). Please make it similar size and placement as this one: [https://ubuntu.com/kubernetes/install](https://ubuntu.com/kubernetes/install)

- [ ] this section doesn't seem to be updated:

Screenshot 2020-01-28 at 16 55 51

**Comment by steverydz** [comment]
@anasereijo hero image added. The "Learn more about AI..." section was updated in another PR which has now merged so you should see it updated in the demo now.

**Comment by barrymcgee** [comment]
# [Codecov](https://codecov.io/gh/canonical-web-and-design/ubuntu.com/pull/6495?src=pr&el=h1) Report
> Merging [#6495](https://codecov.io/gh/canonical-web-and-design/ubuntu.com/pull/6495?src=pr&el=desc) into [master](https://codecov.io/gh/canonical-web-and-design/ubuntu.com/commit/63f0318ea1d3ba7f864cc8fe277a286d3513f05c&el=desc) will **not change** coverage by `%`.
> The diff coverage is `n/a`.

**Comment by anasereijo** [comment]
Looks good, but can you please vertically align text and illustration?

Screenshot 2020-01-29 at 11 15 19

**Comment by steverydz** [comment]
@anasereijo done

**Comment by anasereijo** [comment]
lgtm

**Pull request merged**
