### PR TITLE
Update illustrations and minor text updates on /pricing/devices

### LINKED ISSUE #6531: [ILLUSTRATIONS UPDATE] /pricing/devices
Please update devices - "Ubuntu IoT and Devices - plans and pricing" - v1.0 from the [copy doc](https://docs.google.com/document/d/1uiKNaT59tk2rvjuM24vpqVblcNO90PmE4wUlq9A9Rsk/edit?usp=drivesdk)

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

- Update illustrations and minor text updates on /pricing/devices
- Updated call sales include to optionally have a border and fixed up /livepatch to use it

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/pricing/devices and http://0.0.0.0:8001/livepatch
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Compare to the [copy doc](https://docs.google.com/document/d/1uiKNaT59tk2rvjuM24vpqVblcNO90PmE4wUlq9A9Rsk/edit#)

## Issue / Card

Fixes #6531

### CODE REVIEW

**Comment by anasereijo** [comment]
/pricing/devices

- [ ] change contact us banner to white background

**Comment by pmahnke** [comment]
@anasereijo fixed, added a new white color option.

**Comment by anasereijo** [comment]
> @anasereijo fixed, added a new white color option.

Looks good, thanks! 👍 do you think we should have these banners in our ubuntu.com/_docs?

**Comment by pmahnke** [comment]
@deadlight you didn't approve the code.

**Pull request merged**
