### PR TITLE
Add the OpenStack project chart to what is OpenStack page

### LINKED ISSUE #10052: Add the OpenStack project chart to what is OpenStack page
## Summary
Add the How big is OpenStack project chart to the what is OpenStack page.

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Add the OpenStack project chart to what is OpenStack page

## QA
- Open the demo
- Go to /openstack/what-is-openstack
- Jump to the "How big is the OpenStack project?" section
- See the OpenStack chart

## Issue / Card
Fixes #10052 

## Screenshots
image

### CODE REVIEW

**Comment by anasereijo** [comment]
@anthonydillon can you create a demo link please?

**Comment by anthonydillon** [comment]
@anasereijo Sure, demo here: https://ubuntu-com-10053.demos.haus/openstack/what-is-openstack

**Review by petesfrench — APPROVED** [review]

**Comment by petesfrench** [comment]
LGTM :+1:

**Comment by anasereijo** [comment]
@anthonydillon can you please change that section to look like the following:

- [ ] I move the legend to the right: [replace graph](https://assets.ubuntu.com/v1/ab82625a-Statista_figure1.svg) 
- [ ] graph's` width: 680px;`
- [ ] add padding between graph and text

Screenshot 2021-07-21 at 14 27 43

**Comment by anthonydillon** [comment]
@anasereijo done, switching the charts on small screens.

**Comment by anasereijo** [comment]
PERFECT 🥇

**Comment by anasereijo** [comment]
@petesfrench please review this again

**Review by petesfrench — APPROVED** [review]

**Comment by petesfrench** [comment]
All good! :+1:

**Comment by SirSamTumless** [comment]
@tytus-kurek we're going to merge this if that's fine.

**Comment by tytus-kurek** [comment]
@SirSamTumless LGTM

**Pull request merged**
