### PR TITLE
Update /download/iot page

### LINKED ISSUE #6613: [ILLUSTRATIONS UPDATE]  /download/iot
### **Hero**

- [x] suru: `p-strip--suru-topped `

### **Raspberry Pi**

- [x] update image https://assets.ubuntu.com/v1/a999bb5f-Raspberry+Pi+4.png

**Supported platforms:**

- [x] can you make this section look like the following:

Screenshot 2020-02-10 at 16 25 56

### **Ubuntu Core**

- [x] can you make this section look like the following:

Screenshot 2020-02-10 at 16 26 02

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Update /download/iot

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/download/iot
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Check that the changes requested in [the issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/6613) have been made

## Issue / Card

Fixes #6613

### CODE REVIEW

**Comment by anasereijo** [comment]
how easy it is to change the height of each logo? they look too small comparing to the design

**Comment by steverydz** [comment]
@anasereijo easy - what heights do you want?

**Comment by anasereijo** [comment]
@steverydz cool, you make them all `height: 45px;`

**Comment by steverydz** [comment]
@anasereijo done

**Comment by anasereijo** [comment]
@steverydz looks good!

**Pull request merged**
