### PR TITLE
Fix 'version/status' not being retained between pages on cve-search

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

- Fixes 'version/status' not being retained between pages on cve-search

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- Check that the filter parameters are retained between pages, specifically when there is more than one version/status.

## Issue / Card

Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10799

## Help

[QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html) - [Commit guidelines](https://canonical-web-and-design.github.io/practices/workflow/commit-messages.html)

### CODE REVIEW

**Review by carkod — APPROVED** [review]
LGTM

**Comment by petesfrench** [comment]
@carkod I've changed the fix for this to be a little more robust, can you check it actually works and doesn't break other pagination as I have to change a helper function

**Comment by petesfrench** [comment]
@carkod I also had to move it down a line so the linter would pass

**Comment by carkod** [comment]
> @carkod I also had to move it down a line so the linter would pass

It's still not passing, can you do it with black? Look into the `package.json` file, there is a format-python command, so that means you can do `dotrun format-python`

**Review by carkod — APPROVED** [review]
LGTM

**Pull request merged**
