### PR TITLE
Switch to using postgres in local dev

### PR DESCRIPTION
**Pull request by nottrobin**
QA
--

Follow postgres instructions in the readme

Go to /security/notices, see it works.

### CODE REVIEW

**Comment by nottrobin** [comment]
Oh.... this will break demos :(

**Comment by nottrobin** [comment]
I wonder if there's an easy way to support both?

**Comment by jpmartinspt** [comment]
I would say leave the .env to point to sqlite. And leave instructions to setup postgres. Most people that dev on ubuntu don't care about using postgres at all.

**Comment by nottrobin** [comment]
OK I've updated it to provide specialist postgres instructions, so that the `./run` will continue to work for demos.

**Pull request merged**
