### PR TITLE
update /internet-of-things illustrations

### LINKED ISSUE #6639: [ILLUSTRATIONS UPDATE] /internet-of-things
**Hero:**

- [x] remove `is-deep`

- [x] replace illustration with: https://assets.ubuntu.com/v1/049b4cc6-ubuntu+core+18+circular+white.svg 350px wide

**Logo strip**

- [x]  is there a way to reduce the bottom spacing a bit? It's taking too much space

Screenshot 2020-02-12 at 16 36 53

**Private App Store included**

- [x] remove `is-deep`

**Snaps for security**

- [x] remove `is-deep`

- [x] core logo to be 150px wide

**Update Control**

- [x] add illustration: https://assets.ubuntu.com/v1/a43d61ae-update+control.svg

**Look who’s leading**

- [x] remove `is-deep`

**From prototype to production on all major platforms**

- [x] remove `is-deep`

**best for developers**

- [x] https://assets.ubuntu.com/v1/061edebb-developer.svg width 140px

**Let’s work together**

- [x] light grey background

- [x] [illustration](https://assets.ubuntu.com/v1/c4b290c8-Contact+us.svg) 280px wide

- [x] make button positive

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

Updated /internet-of-things illustrations according to [issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/6639)

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/internet-of-things
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- See that the page complies with the comments in the [issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/6639)

## Issue / Card

Fixes #6639

### CODE REVIEW

**Comment by anthonydillon** [comment]
That linkchecker is almost always going to fail from now on now that we have tutorials in the mix. We could ignore it as we need with docs, etc.

**Comment by sowasred2012** [comment]
> That linkchecker is almost always going to fail from now on now that we have tutorials in the mix. We could ignore it as we need with docs, etc.

@anthonydillon would it fail because they're unpublished/changed regularly? Or what would cause that to happen? In this case it's pointing out something that seems to be a legitimate issue: https://github.com/canonical-web-and-design/ubuntu.com/issues/6649

**Comment by anthonydillon** [comment]
Oh that's good it found a true error but I find that we hit intermittent timeouts.

**Comment by pmahnke** [comment]
I fixed the link [here](https://discourse.ubuntu.com/t/creating-custom-lxd-images/13970)

**Comment by anasereijo** [comment]
some things were missed:

- [ ]  core logo to be 150px **wide**

- [ ] Update Control: add illustration: https://assets.ubuntu.com/v1/a43d61ae-update+control.svg

- [ ] best for developers: https://assets.ubuntu.com/v1/061edebb-developer.svg width 140px

**Comment by anasereijo** [comment]
👍

**Pull request merged**
