### PR TITLE
Secondary nav fixes

### PR DESCRIPTION
**Pull request by lyubomir-popov**
## Done

Fix spacing issues with the secondary nav

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- Verify secondary nav looks ok

### CODE REVIEW

**Comment by anasereijo** [comment]
@lyubomir-popov Is this just about the sec nav or is it also the nav dropdown? Asking this because on the demo the dropdown looks very different from what we currently have.

The sec. nav looks much better with font size 16px 👍I'm just wondering what can we do to make it look better on mobile now:

Screenshot 2019-06-10 at 11 28 21

**Comment by lyubomir-popov** [comment]
@anasereijo just the secondary nav. also this is not a redesign, just fixes in order to migrate ubuntu.com onto vanilla 2.0.

**Comment by lyubomir-popov** [comment]
@anthonydillon do you mean between search and primary dark grey nav? this pr is only about the light grey secondary nav.

**Comment by anasereijo** [comment]
> @anasereijo just the secondary nav. also this is not a redesign, just fixes in order to migrate ubuntu.com onto vanilla 2.0.

Ok makes sense. Can we just left align the sec nav elements on mobile?

**your demo:**

Screenshot 2019-06-10 at 11 34 59

**what we currently have:**

Screenshot 2019-06-10 at 11 35 04

**Comment by lyubomir-popov** [comment]
I've cleaned up the css a bit. I've also reduced the space between items in half, as a partia lremedy to the 3 rows of links on some pages. The padding it uses in this pr matches side padding in buttons, tabs, etc, it is just applied on one side of the element instead of both. Effectively, this reduces it in half.

**Comment by lyubomir-popov** [comment]
@anasereijo @anthonydillon this is ready for another look.

**Comment by deadlight** [comment]
@lyubomir-popov the nav isn't spaced correctly at mobile:
image

**Comment by lyubomir-popov** [comment]
@deadlight this is only about the light grey subnav. the dark grey one will be fixed with a subsequent p. trying to keep things small and reviewable.

**Comment by deadlight** [comment]
@lyubomir-popov ah, sorry. I misunderstood the scope.

**Pull request merged**
