### PR TITLE
Remove logos section and update number

### PR DESCRIPTION
**Pull request by ClementChaumel**
## Done

- Removed Walmart, Spotify, and Netflix logos
- Changed  "3-4.5%" to "3-6%" 

## QA

- go to https://ubuntu-com-9438.demos.haus/gcp
- Check that the logos are gone and the numbers updated correctly

## Issue / Card

Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9437

## Screenshots

image

### CODE REVIEW

**Review by anthonydillon — APPROVED** [review]
Code looks good. Might want a border between the second more. Up to Ana.

**Comment by anthonydillon** [comment]
Also can you update the copy doc with the new percentage and comment on the logos please.

**Review by carkod — APPROVED** [review]
LGTM @anasereijo any design input?

**Comment by anasereijo** [comment]
> Code looks good. Might want a border between the second more. Up to Ana.

@anthonydillon is right! It will look better if the hero section has a line separating it from the below section

**Comment by anasereijo** [comment]
@ClementChaumel 👍

**Pull request merged**
