### PR TITLE
Build the ESM page ready for the advantage release

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Rebuild the ESM page without links to advantage for now.

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/esm
- See that the copy matches [the copy doc](https://docs.google.com/document/d/1RBZX3PJPvODxRlcnIS10Ii4SkIMH5Fm74EmsMQ0cnic/edit)
- Check it matches [the design](https://user-images.githubusercontent.com/36884067/64698699-4722e780-d49b-11e9-9dd0-d2af30f81352.jpg)

## Issue / Card
Fixes https://github.com/canonical-web-and-design/base-squad/issues/707

### CODE REVIEW

**Comment by anasereijo** [comment]
- [ ] [ITstrategen logo](https://assets.ubuntu.com/v1/3e31f0f5-ITstrategen+logo.svg) should be

- [ ] put the logo inside a white box (so when we have another case study it's just replacing the logo or this white background with an image) this white box should be 2 col wide (around 270x172)

- [ ] keep 1 col empty between white box and text

- [ ] case study title should be h4

- [ ] case study [icon](https://assets.ubuntu.com/v1/3100aa6a-case-study-08.svg)

- [ ] few fixes on suru see image below:

Ubuntu Extended Security Maintenance   Ubuntu

**Comment by anthonydillon** [comment]
@anasereijo Are you sure this image is correct? 
Screenshot_2019-09-13 Ubuntu Extended Security Maintenance Ubuntu

**Comment by anthonydillon** [comment]
@anasereijo Updated

**Comment by anasereijo** [comment]
- [ ] case study banner: you repeat "case study" in the title.please remove it

- [ ] sorry maybe I didn't explain this well but "ITstrategen keeps their applications secure with ESM" should be the `h4` and "Case study" next to the icon should `muted heading` as it was before

**Comment by matthewpaulthomas** [comment]
- [ ] You can’t, and won’t ever, “Get ESM now” “Free for personal use” by going to buy.ubuntu.com. The only way to do that is to go to `/advantage` once it exists. So that’s where the button should point (and therefore it shouldn’t have an external-link emblem).

Apart from that, and Ana’s comments, this looks good to me.

**Comment by anthonydillon** [comment]
@anasereijo addressed your comments

@matthewpaulthomas If I have to leave the links/buttons going to buy.u.com what should the text be?

**Comment by anthonydillon** [comment]
@anasereijo make the icon smaller and aligned the title.

**Comment by matthewpaulthomas** [comment]
@anthonydillon If you need to land this before `/advantage` is promoted to the general public, then:
- drop/comment-out the “And it’s free for personal use.” sentence
- drop/comment-out the whole “Free for personal use” block including the separator.

**Comment by anthonydillon** [comment]
@matthewpaulthomas thanks done.

**Pull request merged**
