### PR TITLE
WIP add /pricing/devices page

### LINKED ISSUE #5865: [New page] devices - "Ubuntu IoT and Devices - plans and pricing"
This is a new page request from Galem. It outlines the prices for the IOT and devices. There are some unresolved comments, but we have been told; _"Most of the open comments are requests for clarifications, or require information that we don't have yet. It is Mark who requested me to publish it."_

- [Copy doc](https://docs.google.com/document/d/1uiKNaT59tk2rvjuM24vpqVblcNO90PmE4wUlq9A9Rsk/edit?usp=drivesdk)
- [Trello Card](https://trello.com/c/nMOPV0GZ/419-devices-plan-and-pricing)

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

- Added a new page at /pricing/devices, based on this [copy doc](https://docs.google.com/document/d/1uiKNaT59tk2rvjuM24vpqVblcNO90PmE4wUlq9A9Rsk/edit#heading=h.l83dv5879ajz)

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- Visit: http://0.0.0.0:8001/pricing/devices
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- See that the page matches the [copy doc](https://docs.google.com/document/d/1uiKNaT59tk2rvjuM24vpqVblcNO90PmE4wUlq9A9Rsk/edit#heading=h.l83dv5879ajz), and is laid out correctly.

## Issue / Card

Fixes #5865

### CODE REVIEW

**Comment by sowasred2012** [comment]
@anasereijo @pmahnke I've updated the markup based on the changes Ana made to the copy doc - things outstanding that I can see are:
- [ ] Ubuntu certified logo is missing
- [ ] The section featuring "Beyond BSPs" looks odd - should that also be an image?

Anything else you think needs tweaking?

**Comment by anasereijo** [comment]
@sowasred2012 sorry didn't had a change to relook at this but in the meantime I added a comment with the Certified Ubuntu image and fixed that "Beyond BSPs" section

**Comment by anasereijo** [comment]
@sowasred2012 there are a few things to fix and many of the headings weren't matching the copydoc. See it below:

- [ ] part I



- [ ] part II



- [ ] part III



- [ ] part IV



- [ ] part V



- [ ] part VI



- [ ] part VII

**Comment by sowasred2012** [comment]
Closing this PR - rebased master after the performance workshop work, which has messed things up. Created a new, clean PR here: https://github.com/canonical-web-and-design/ubuntu.com/pull/5900

**Pull request closed without merging**
