### PR TITLE
Update for the 20.04.2.0 desktop respin

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

- Update for the 20.04.2.0 desktop respin
- Added a variable for this
- **note, the file isn't in place, so it will not download**

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/download/desktop and http://0.0.0.0:8001/download/alternative-downloads
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- See that it points to the 20.04.2.0 download

### CODE REVIEW

**Comment by anthonydillon** [comment]
## Two points
The download button in the mega menu is still downloading 20.04.2 only:
image

The BitTorrent titles still need the new variable:
image

**Review by anthonydillon — CHANGES_REQUESTED** [review]
Comment above

**Comment by pmahnke** [comment]
@anthonydillon thanks, I think the mega menu is fine, it is still 20.04... I fixed the torrent link though.

**Comment by anthonydillon** [comment]
Sorry I meant the link itself is to https://releases.ubuntu.com/20.04.2/ubuntu-20.04.2-desktop-amd64.iso which will 404 once `.0` is out.

**Comment by pmahnke** [comment]
@anthonydillon ah, right, missed that.  It wouldn't 404, but get you the old version that was broken.

**Comment by anthonydillon** [comment]
Ah I thought it might as https://releases.ubuntu.com/20.04.2/ubuntu-20.04.1-desktop-amd64.iso fails

**Comment by pmahnke** [comment]
@anthonydillon can you approve? it is ready.

**Review by anthonydillon — APPROVED** [review]
LGTM

**Pull request merged**
